### ISSUE TITLE
Reply to review after deleting answer not possible

### ISSUE THREAD

**Issue by krisbr** [mozilla/addons#158] opened 2016-07-11 21:10 UTC
I've accidentally deleted my existing reply to a review instead of updating it. Now I'm can't write another reply. As soon as I click the "Send" button I just get the message that a error occured

**Comment by wagnerand** [comment] 2016-07-11 21:19
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/242940/

**Comment by EnTeQuAk** [comment] 2016-07-12 06:00
The problem here is hat `reply_to` is a unique field which is now already "used" by the deleted reply and thus cannot be reused. It's a bit sad, does anyone know why we cannot have multiple replies to a review by design? Especially with this scenario here in mind this is a weird decision

**Comment by krisbr** [comment] 2016-07-12 06:23
Why can't this unique field be deleted when you delete the reply? 
In this specific case the reviewer added a few suggestions for my add-on and now I can't reply to them and unfortunately there is no other way to communicate with him.

**Comment by EnTeQuAk** [comment] 2016-07-12 07:21
The thing is, the delete is only a soft delete so we keep the original
data and that's why we also keep the link to the reply. I am honestly
not sure if this has to be that way but we'll find out :)
 
 
On Tue, Jul 12, 2016, at 08:23 AM, krisbr wrote:
> Why can't this unique field be deleted when you delete the reply?
>  In this specific case the reviewer added a few suggestions for my add-
>  on and now I can't reply to them and unfortunately there is no other
>  way to communicate with him.
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>
 

Links:

  1. https://github.com/mozilla/addons/issues/158#issuecomment-231948167
  2. https://github.com/notifications/unsubscribe/AAIfGXxliNwg1iUgO0x2mjLhnFt1RyqZks5qUzL3gaJpZM4JJyQE

**Comment by jvillalobos** [comment] 2016-07-12 14:45
We keep track of deleted reviews so we can undelete them. This is meant to allow admins to reverse incorrect moderation by the reviewer team.

I don't know the implications here, but could the new reply overwrite the old one? If that's an easy fix, I would be in favor of it. Otherwise this could wait until we redo the ratings feature, but that would probably happen next year.

**Comment by krisbr** [comment] 2016-07-12 17:19
If it's possible to undo the deleting, I would be glad if you could do that (torpedo@tu-darmstadt.de).

**Comment by EnTeQuAk** [comment] 2016-07-12 18:00
> I don't know the implications here, but could the new reply overwrite the old one?

That should work and could be relatively easy. I was wondering if we should restrict that "recovery" to the exact user but I feel like that would kill any possibility for someone else to reply if someone deleted his reply.

Only implication would be that you cannot restore that old reply anymore but given that there's a new one I feel like that's okay.

I can take a look at this but I'd say it's low priority.

**Comment by CanisLupus** [comment] 2016-08-12 10:47
This also happened to me. I deleted my answer and found that now there's no way to add a new reply or just get the deleted reply back and change it, which means that there's now a single review of my add-on that doesn't have an answer.

I'd be okay with a way of either overwriting the reply or undeleting it (or at least warning us that there's no chance to reply again, but that is less than ideal).

Just my two cents, so that maybe this issue is considered a bit more important. I think it is, actually, as it negatively affects the developer<->user relationship.

**Comment by diox** [comment] 2016-09-27 10:08
It should have been fixed in 188b5099789d6bbc1463a8eccedfe67dd1ffb061, which was pushed to prod last week. I'll submit a PR to add a couple unit tests covering this use case.

**Comment by CanisLupus** [comment] 2016-09-27 10:27
That's great news! But does it mean that it's live already? Because I've just tried to reply to the review I mentioned (the one where I deleted the reply) and still got the "Oops! We had an error." message.

Daniel

**Comment by diox** [comment] 2016-09-27 10:55
Ah, sorry, I was wrong, it has not been pushed yet. It should be live in less than 12 hours.

**Comment by CanisLupus** [comment] 2016-09-29 20:51
I think it took a bit more than that. ;) But I tried again just now and was finally able to reply! I really appreciate this fix, @diox. :) Thanks!

**Closed** 2016-09-29 21:50 UTC
Labels: in progress, triaged
