### ISSUE TITLE
Add To Collection - Cannot search the list

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons#677] opened 2018-03-29 03:23 UTC
### Describe the problem and steps to reproduce it:
When clicking the Add To Collection drop down, there is no way to search the list of collection names in the list (I have over 120, so it is not always easy to find the one I want (or more than one with similar names, different purposes). 

And with the names not sorted, there is no alternative

### What happened?
Unable to type to search the list.  (BUT note, sorting does not replace the need to be able to search the list).

### What did you expect to happen?
To be able to type to search the Add To Collection list, like was possible in the older design of this list.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

See related issues:
Add To Collection - List not sorted by name -- https://github.com/mozilla/addons/issues/676

**Comment by smayer97** [comment] 2018-03-29 03:45
Additional related issues:
Add To Collection - No indicator showing which collection(s) the add-on already belongs to   -- https://github.com/mozilla/addons/issues/678
Add To Collection - There is no link to open collection from list of collections -- https://github.com/mozilla/addons/issues/679

NOTE: Without all these 4 changes to re-implement the original design, the 'new' Add To Collection has VERY LIMITED usefulness.

**Comment by jvillalobos** [comment] 2018-04-09 22:16
This would only be useful to a handful of users who have tons of collections (and https://github.com/mozilla/addons/issues/676 already helps), so I think anything remotely complex to fix this issue should be out of the question. It would be overkill to have a collections search API just for this, for example. If we can do some simple client-side filtering, maybe it's worth doing. I wouldn't object to closing this due to edge case-iness, though.

**Comment by smayer97** [comment] 2018-04-10 09:48
Just in case it is not clear...just seeking that the list can respond to the FIND function in Firefox... and ideally respond to just typing to initiate that search. 

I do not know what would be involved to make this happen but I am hoping it is not a difficult thing.

**Comment by EnTeQuAk** [comment] 2018-07-26 09:45
Closing as duplicate of https://github.com/mozilla/addons-server/issues/8926

**Closed by EnTeQuAk** 2018-07-26 09:45 UTC

**Comment by smayer97** [comment] 2018-07-26 10:34
Not sure how this is a duplicate of https://github.com/mozilla/addons-server/issues/8926. Also, not sure if an API is needed to make this happen. Again, simply desire for the text in the drop down menu to respond to the FIND function in FireFox.

**Comment by smayer97** [comment] 2019-11-28 07:22
Ok, re-filed here: https://github.com/mozilla/addons-frontend/issues/8996
