### ISSUE TITLE
Where is the button to add favorites and add-ons?

### ISSUE THREAD

**Issue by Sietgo** [mozilla/addons#218] opened 2016-09-18 11:07 UTC
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment] 2016-09-18 11:10
Could you please explain where you are encountering the issue and provide a bit more detail? I'm not sure what you're referring to 😄

**Comment by Sietgo** [comment] 2016-09-18 11:13
Please return the back button under the addition of favorites to the collection.

**Comment by andymckay** [comment] 2016-11-08 01:14
Dupe of mozilla/addons-server#2264

**Closed by andymckay** 2016-11-08 01:14 UTC

**Comment by smayer97** [comment] 2017-03-22 05:37
For those following this thread, please be sure to follow at the link for the DUPE above...
