### ISSUE TITLE
want my toolbar on my phone 

### ISSUE THREAD

**Issue by Mugzyhaley** [mozilla/addons#435] opened 2017-07-05 22:23 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment] 2017-07-05 22:28
Closing due to lack of information.

Please add information to your issue including the error you encountered, a URL (if applicable), and/or steps to reproduce.

If you are looking for a desktop add-on to be made available on your phone, please contact the add-on developer directly.

**Closed by tofumatt** 2017-07-05 22:28 UTC

**Comment by Mugzyhaley** [comment] 2017-07-13 21:10
Im trying to figure out how to use the add ons on the phone on mozilla and
firefox im not understanding how it works on mobile phone

**Comment by tofumatt** [comment] 2017-07-13 21:30
Which toolbar (what is the name of it) and what is the link to the add-on?
