### ISSUE TITLE
Enhancement: Allow exact search

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#821] opened 2018-10-23 15:08 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

The current search system often ignores search terms or substitutes its own.

For example, as I've previously reported, searching for "scrolljacking" yields many results which affect scrolling but don't mention scrolljacking.

Searching for exact phrases such as "kill autoscroll" or "kill smart scroll" yields results which lack the exact phrase. Some contain kill, some contain autoscroll, some contain neither word part of the search term.

(I disable smart scroll and autoscroll in browser prefs, but some web pages overrule these prefs, and I need to overrule these pages to avoid migraine-inducing scroll effects.)

### What happened?

Apart from the failed searches, I'm not sure what happens. It's possible that the search tools are truncating search terms, or splitting search terms and then dropping terms until they get enough results.

### What did you expect to happen?

Searches should return results containing the actual search terms.

This may also help users searching for an extension by name.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I think #798 is part of the problem. Trying to get more results which don't contain the actual search terms leads to an overflow of results which don't contain the actual search terms.

An easily-visible option to switch between similar search and exact search might help.

**Comment by diox** [comment] 2018-10-23 16:02
This is a duplicate of https://github.com/mozilla/addons-server/issues/6837 which will be fixed in production this week. With the fix enabled locally, all examples work when there is an exact name match.

> An easily-visible option to switch between similar search and exact search might help.

We want to avoid cluttering the UI with such features.

**Closed by diox** 2018-10-23 16:02 UTC
