### ISSUE TITLE
Web-Extension - Error: Validation was unable to complete successfully due to an unexpected error.

### ISSUE THREAD

**Issue by ntinkler-calendly** [mozilla/addons#938] opened 2019-03-04 17:26 UTC
### Describe the problem and steps to reproduce it:
1. Create a zip of my extension using my standard system zip (not adm-zip).  Alternatively, create a crx file using chrome to pack the web-extension. (Both fail)
2. Upload the file to https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed
3. I receive a generic failure message with no helpful information.  Message below - 
Sorry, we couldn't load your WebExtension.
Error: Validation was unable to complete successfully due to an unexpected error.

Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU

### What happened?
The upload failed with a generic error and absolutely no information about what happened.

### What did you expect to happen?
The upload should have succeeded or given me meaningful feedback about what failed and why.

### Anything else we should know?
This extension loads just fine through "about:debugging" with no warnings or errors. 

The compressed extension is only ~800kb, and the uncompressed extension is only ~2.5mb. It's fairly small. 

The extension is not minified or obfuscated, although it does contain a moderately large vender.js (1.2mb)

Full extension is attached.
[firefox.zip](https://github.com/mozilla/addons/files/2927482/firefox.zip)

**Comment by wagnerand** [comment] 2019-03-04 18:06
Duplicate of #896

**Closed by wagnerand** 2019-03-04 18:06 UTC
