### ISSUE TITLE
Self-assigned addon is stuck at "Awaiting Review" status

### ISSUE THREAD

**Issue by quinguyenhuu** [mozilla/addons#1317] opened 2021-04-14 00:33 UTC
### Describe the problem and steps to reproduce it:
My addon is stuck at "Awaiting Review" status since 4 days. I have created an issue serveral days ago, but i cannot add more comments to it so i create this new issue. I give some comments but no one replied it. 
![image](https://user-images.githubusercontent.com/9970827/114637411-780c7380-9cf3-11eb-91e5-5fe9fafce115.png)

### What happened?
I updated my addon and uploaded a new verson including the source code as the supporter wants it. I uploaded 4, 5 days ago but didn't hear anything.

### What did you expect to happen?
I hope that my addon can be reviewed quickly or let me know what is still wrong in my addon. Because it took pretty long time on reviewing.

### Anything else we should know?
![image](https://user-images.githubusercontent.com/9970827/114637261-14824600-9cf3-11eb-84a8-f0acf975fa65.png)

**Comment by diox** [comment] 2021-04-14 09:28
This is not a bug. Opening new issues won't fix it or make reviewers reply any faster. Please don't do that.

**Closed by diox** 2021-04-14 09:28 UTC
