### ISSUE TITLE
[Bug]: Un-blocklisting version that was blocklisted with the force-disable add-on option leaves the version in an unreviewed state with no way to enable it again

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#15104] opened 2024-10-21 09:47 UTC
### What happened?

For an add-on's version that we blocklisted (along with the force-disable add-on option in AMO admin) and want to unblocklist and re-enable the version
- We delete the corresponding `blocklist/block` record
- We force-enable the add-on in AMO reviewer tools

Issue: The add-on is force-enabled but the version un-blocklisted stays in an `unreviewed` state with no reviewer action to un-reject the version. 

### What did you expect to happen?

For an add-on's versions un-blocklisted and add-on force-enabled, there should be an option to "un-reject" versions that would allow us to republish versions when that's desirable. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1158)

**Comment by wagnerand** [comment] 2024-10-22 14:46
The "Unreject" action was not available, so I had to change the status of the version and file manually in django-admin.

@abhn you mentioned the actions and their order on slack, can you paste that here (best to remove actual dates, we are mostly interested in the order)

**Comment by abhn** [comment] 2024-10-22 15:05
Here we go. 

- force-disabled the add-on on AMO
- force-enabled the add-on on AMO and content approved. Add-on was auto-approved.

\<some time passed\>

- blocked the add-on (with the force-disable action on django-admin)
- deleted the blocklist entry for the add-on (and its version)
- force-enabled the add-on on AMO

Add-on's version is in an `unreviewed` state with no option option to "unreject".

**Comment by diox** [comment] 2024-10-31 12:19
> In the triage meetings the theory we came up with was that blocklist disable add-on functionality is not using the `force_disable()` method and rather manually altering the add-on `status`.
> 
> Which is at least partially true, see https://github.com/mozilla/addons-server/blob/51959ad6687c09e140a7d6c979a1ccb44ad7f657/src/olympia/blocklist/utils.py#L227-L230 ; the problem is though, we should have gone through `disable_versions_for_block()` before reaching that point, which does call `reject_multiple_versions()` like a normal reviewer action would, so there is something else wrong here... We'll probably need to reproduce locally to understand.

The problem is, when we call `reject_multiple_versions()` as part of the blocklisting, this is not considered a human review, it doesn't set a human review date. So the `unreject` action (which, for listed, is only for the latest version) is unavailable.

If we had properly gone through `force_disable()` that should not matter, because force-enabling it would reset the correct statuses. So that's probably the way to go.

**Comment by diox** [comment] 2024-10-31 13:21
> If we had properly gone through `force_disable()` that should not matter, because force-enabling it would reset the correct statuses. So that's probably the way to go.

Actually, while we probably want to go through `force_disable()` to get proper activity logging, backups set up etc, that wouldn't help for this problem, because we reject the versions first, so by the time we force disable the add-on, the versions are already disabled, so we would record disabled as their previous status, so when the add-on would be force-enabled again, they still would stay disabled.

We do `reject_multiple_versions()` first so that the email being sent correctly states which versions were rejected - if they would have been disabled first as part of the force disable, they wouldn't be included. 

The real issue is that the `reject_multiple_versions()` is explicitly set as not coming from a human, but we only allow unreject for listed for the latest version, if it has been reviewed by a human.

So on top of using `force_disable()`, we need to either:
- Allow unrejecting on listed channel even for a version not marked as having been reviewed by a human
- Consider the automatic rejection of versions blocked as having been made by a human

**Comment by KevinMind** [comment] 2024-11-04 13:19
@diox it seems in the PR we opted for number 2. Is that true? Can you clarify why we chose this path. Is there a good reason not to allow unrejecting on listed channel regardless of the humanness of the original rejection?

The scenario at play here seems exceedingly complex and it at least naively seems simpler to remove the condition rather than fulfill it, so I would think we'd prefer that approach unless there's a good reason not to. Can you fill in the blanks for posterity?

**Comment by diox** [comment] 2024-11-07 16:50
STR should be:
- Block an add-on with listed version with force-disable action
- Unblock that add-on entirely
- Force-enable that add-on

At this point the versions should be rejected still but in the listed review page you should have the option to unreject them, and once you do the add-on should be back to normal.

**Closed** 2024-11-07 16:50 UTC

**Comment by ioanarusiczki** [comment] 2024-11-08 13:30
The initial problem is fixed (took a while to figure it out).
Interesting is that I could not reproduce it on -stage with a [listed version approved manually](https://reviewers.addons.allizom.org/en-US/reviewers/review/1032061)

I got the case on stage when unreject is not available and the version is in a weird state.
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1032067
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1027315 -> this would be with the[ long version ](https://github.com/mozilla/addons/issues/15104#issuecomment-2429542014) added by @abhn 

So I tried on dev and I could not reproduce this
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634022
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634018 

I've something about unlisted versions though on dev that I don't understand, I did block, delete block, force enable and unreject and the versions were disabled for auto-approval unlike stage where they're auto-approved.

Dev 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/634021
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/634019
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/634020 

Stage 
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1032065
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1032063

**Comment by diox** [comment] 2024-11-08 14:04
> Interesting is that I could not reproduce it on -stage with a [listed version approved manually](https://reviewers.addons.allizom.org/en-US/reviewers/review/1032061)

Yes, that was only for auto-approved versions. Because the bug originally came from the fact that these versions were never marked as having been reviewed by a human, and on the listed channel, that is one of the requirements for unreject action to be available (others being that the add-on is not disabled/deleted, and, on the listed channel, that it's the latest version).

**Comment by diox** [comment] 2024-11-08 14:07
> I've something about unlisted versions though on dev that I don't understand, I did block, delete block, force enable and unreject and the versions were disabled for auto-approval unlike stage where they're auto-approved.

That is an interesting side-effect. We are now considering the rejection caused by the block as coming from a human. That causes us to force the flag disabling approval until the next approval to be set, and the unreject action doesn't seem to unset it on its own.

@abhn & @wagnerand to comment on whether this is a problem or not.

**Comment by abhn** [comment] 2024-11-08 15:22
Shouldn't there be an unreject action even if the rejection was caused by a human? Reviewers may also have to unreject versions that was rejected by human action. Or am I understanding the problem incorrectly here?

**Comment by abhn** [comment] 2024-11-08 16:18
> causes us to force the flag disabling approval until the next approval to be set, and the unreject action doesn't seem to unset it on its own.

I think that's alright and not too big of an issue. 

I'm assuming we could just unset that (disable-auto-approval-until-next-manual-approval) flag manually if we want to let the add-on auto-approve.

**Comment by diox** [comment] 2024-11-08 16:54
Yes, you'll be able to flip that flag as usual.
