### ISSUE TITLE
[Bug]: Not receiving response emails

### ISSUE THREAD

**Issue by SuperSamSam-code** [mozilla/addons#14941] opened 2024-08-02 13:57 UTC
### What happened?

The addon review team has replied to me twice already as I can see for the mozilla addons platform however I never received the emails. Nor in spam or main inbox and I can't view those answers from the platform itself. 
Thanks

<img width="720" alt="image" src="https://github.com/user-attachments/assets/4ef406fa-52e7-4ecb-979a-531527e21ec9">

### What did you expect to happen?

Receive via email juste like the other interactions the messages from the review team

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-960)

**Comment by wagnerand** [comment] 2024-08-06 14:34
Duplicate of https://github.com/mozilla/addons/issues/14944.

**Closed by wagnerand** 2024-08-06 14:34 UTC
Labels: needs:info
