### ISSUE TITLE
[Reviewer Tools] 403 Forbidden on File Redirect

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#445] opened 2017-07-19 07:05 UTC
Often enough, there are 403 Forbidden messages when trying to open a file directly.

Link:
```
Download manifest.json
https://addons.mozilla.org/en-US/firefox/files/browse/685159/file-redirect/manifest.json
```
Result:
`https://addons.cdn.mozilla.net/en-US/firefox/files/browse/685159/file-serve/manifest.json?token=66........52`

**Comment by diox** [comment] 2017-07-19 10:07
I've seen that as well, also on dev. I haven't been able to identify the cause, it was happening intermittently for me.

Since the 403 is served by nginx and happens on cdn domain I figure it's an ops issue ? /cc @bqbn for input.

Note: we're talking about file redirects from the file viewer, and we're logged in with the required permissions when accessing it (the file viewer itself works - it's just the download link that does not)

**Comment by bqbn** [comment] 2017-07-19 18:15
So the application redirects ```/en-US/firefox/files/browse/685159/file-redirect/manifest.json``` (known as A hereinafter) to ```/en-US/firefox/files/browse/685159/file-serve/manifest.json``` (known as B hereinafter), however, according to the current configuration [1], B is not specifically captured and will be served by the default rule [2], which is 403.

Can you provide a URL that is similar to A but is returning 200, for me to compare? Otherwise, if there is no such a working URL, I suspect we need to either figure out the correct URL that A is supposed to be redirected to, or, file a bug to add a new Nginx config to capture B.

[1] https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L35-L168
[2] https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L122-L124

**Comment by diox** [comment] 2017-07-19 18:52
From the same extension, this one works:
* https://addons.mozilla.org/en-US/firefox/files/browse/660890/file-redirect/webextension/background.js redirects to https://addons.cdn.mozilla.net/en-US/firefox/files/browse/660890/file-serve/webextension/background.js?token=d32859d8-d5ee-46b9-81c3-3ddd656cba13

This one does not:
* https://addons.mozilla.org/en-US/firefox/files/browse/660890/file-redirect/webextension/manifest.json redirects to https://addons.cdn.mozilla.net/en-US/firefox/files/browse/660890/file-serve/webextension/manifest.json?token=e05add38-4a1c-4cf9-8614-15b28de61042 (403)

Not entirely sure whether it's happening for all json files or if it's just a coincidence. Now that I'm trying to reproduce I can only see it with json files, but that may be an accident.

**Comment by jasonthomas** [comment] 2017-07-19 18:54
I would recommend using https://addons-dev.allizom.org/en-US/firefox/files/browse/253397/ once logged in. You can replicate the issue by selecting `mainfest.json` on the left side and then click on `Download manifest.json` link.

The `Download background.js` for that extension seems to work fine so I think it's related to our CDN restrictions we have in place which currently do not allow the CDN to serve `json`. It could be as simple as adding `json` to https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L104-L106 because as far as I can tell this content is served via addons-server HttpResponseSendFile which makes use of nginx X-Accel-Redirect [1][2][3][4].

[1] https://github.com/mozilla/addons-server/blob/293cba80462eb242c2f0fe11cacb6fd67399ac3b/src/olympia/files/views.py#L179-L191
[2] https://github.com/mozilla/addons-server/blob/293cba80462eb242c2f0fe11cacb6fd67399ac3b/src/olympia/amo/utils.py#L596-L611
[3] https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/
[4] https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L72-L75

**Comment by diox** [comment] 2017-07-19 18:57
Right, I just noticed this is served by `X-Accel-Redirect`. The view we use can return 403 on its own but our 403 should be different, so I believe @jasonthomas is right and that's due to a CDN restriction affecting json files only.

**Comment by bqbn** [comment] 2017-07-20 20:34
I just submit a PR for this (see above).

Does anyone have a theory why this suddenly becomes an issue? It looks like ```json``` is not in the list of allowed file suffixes from the beginning (i.e. year 2015). Did we recently start to use ```json``` as file suffix?

**Comment by diox** [comment] 2017-07-20 20:51
I blame the rise of webextensions :) They use a `manifest.json` file as the manifest with all core info about the extension, as opposed to an `install.rdf` in legacy extensions. Furthermore, downloading those files is not necessarily something reviewers do very often, as they can be viewed fine in the file viewer itself.

**Comment by bqbn** [comment] 2017-07-20 23:09
The fix is on -dev and -stage. Can someone help verify it before we get it on -prod?

**Comment by diox** [comment] 2017-07-21 00:00
I can confirm that it's fixed for me on dev.

**Comment by erosman** [comment] 2017-07-21 04:31
> Furthermore, downloading those files is not necessarily something reviewers do very often, as they can be viewed fine in the file viewer itself.

Often, we copy sections of code to include in the review response for reference.

The display includes +/- and other characters that have to be manually removed. For that reason, using `Download manifest.json` in order to get the raw code is required. :)

**Comment by vcarciu** [comment] 2017-07-21 08:04
Verified as fixed on stage too with https://addons.allizom.org/en-US/firefox/files/browse/320329/

**Comment by erosman** [comment] 2017-07-21 16:29
New 403 Forbidden situation ... file without extension (definitely need to see it since it does show in the validator 3.0mb)

`https://addons.mozilla.org/en-US/firefox/files/browse/686986/file/resources/cmudict#top`

**Comment by diox** [comment] 2017-07-21 16:39
As a workaround, can't you download the entire xpi file directly instead ?

**Comment by erosman** [comment] 2017-07-21 18:15
> As a workaround, can't you download the entire xpi file directly instead ?

Sure.. that is what we do but then we wont have access to review tools (although in this case it was too large to load anyway)

Then that would mean downloading the entire XPI of this version and previous version and compare locally.

**Comment by bqbn** [comment] 2017-07-21 19:54
How often is the case that a file has no extension and is also smaller than the 1MB threshold? I don't want to handle the no-extension case in Nginx if it doesn't happen too often tbh.

Also if you only review one version of a file, then there should be no +/- characters and the copying of section of code doesn't include them. However, if you compare and show 2 versions of a file at the same time, +/- characters are expected because those show where the differences are between the 2 versions. 

I think the easiest way to get the raw code of a file is just to show one version of that file (e.g. leaving one of the two drop-down menu to be blank), in which case you don't have to download the file to get its raw code.

**Comment by bqbn** [comment] 2017-10-05 01:27
The changes in https://github.com/mozilla-services/cloudops-deployment/pull/919 have landed in -prod a couple months ago.

**Closed by bqbn** 2017-10-05 01:27 UTC
Labels: component: reviewer tools, state: verified fixed, triaged
