### ISSUE TITLE
Visual gap in the package structure and files for reviewers.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons#479] opened 2017-09-07 17:16 UTC
### Describe the problem and steps to reproduce it:
The right section of reviewer's file viewer doesn't list the package structure properly.

### What happened?
Going to any add-on /files/browse/ and /files/compare/ urls on AMO shows the tree structure with 212 pixels between each entries. For example : https://addons.mozilla.org/en-US/firefox/files/browse/713456/

### What did you expect to happen?
There should not be such a huge gap between the listed files and directories in this section.

### Anything else we should know?
This CSS height property seems to create the issue : 
.featured li, .theme-grid li {
    height: 212px;
}

By removing this height property, the issue goes away.

**Comment by wagnerand** [comment] 2017-09-07 17:45
Thanks for the report, this is a dupe of https://github.com/mozilla/addons-server/issues/6323

**Closed by wagnerand** 2017-09-07 17:45 UTC
