### ISSUE TITLE
not able to downloads from FF's own addon page

### ISSUE THREAD

**Issue by sorrymo4** [mozilla/addons#1020] opened 2019-05-04 19:58 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
My old addons were mostly disabled by your new signature policy.  So I went to the FF addons page and tried to install the apps from there.
### What happened?
Every addon that I wanted, didn't download.  I always get the error "Download failed. Please check your connection.".  There is nothing wrong with my connection.
### What did you expect to happen?
addons to be installed

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by J0WI** [comment] 2019-05-04 20:23
This is a duplicate of #1013.
Please refer to https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Closed** 2019-05-04 21:56 UTC
