### ISSUE TITLE
Implement a way to browse through "Compatible with Firefox 57+" add-ons

### ISSUE THREAD

**Issue by Ken-Saunders** [mozilla/addons#376] opened 2017-04-21 07:28 UTC
[I just saw this](https://github.com/mozilla/addons-server/pull/5198/commits/f6da2b8ee800112bd2a4c58c26435e7559087a92)

Please disregard

First of all, we (add-on enthusiasts/users) send out sincere thanks to the AMO team for the "Compatible with Firefox 57+" label.

Since AMO is adding the code below, can a tag be attached to it so that users can browse through add-ons marked as such (through a specific tag search)?
 span class="is-webextension" title="This add-on is built with new technology that is compatible with Firefox 57 and beyond." Compatible with Firefox 57+ /span

If not that, perhaps there's another way.
There must be an automated way to achieve this.

I believe that giving users a head start on learning about, and using what's already available that will work with Firefox 57 would help to ease the anxiety of losing what will not when that time comes.

As a multiple add-on user and big fan of them, right now when I visit AMO, I pretty much only see things that aren't worth using since there is a chance that it won't be usable at all in a few months. 

Being able to browse through an ever-growing list of "safe" add-ons could help to inspire more confidence and optimism for users.

Plus, in all honesty, I'm tired of reading about what we won't have all over the Internet. 

[Example Page](https://addons.mozilla.org/en-US/firefox/addon/disconnect/) showing "Compatible with Firefox 57+"
![amo-fx-57](https://cloud.githubusercontent.com/assets/1267130/25267286/1f6b105a-2642-11e7-9076-a84bfeb84f56.png)

**Comment by Ken-Saunders** [comment] 2017-04-21 07:36
Perhaps a specific AMO in-site search could be attached to a label, or button.
[Like this one](https://www.startpage.com/do/dsearch?query=site%3A+https%3A%2F%2Faddons.mozilla.org+%22Compatible+with+Firefox+57%2B%22&cat=web&pl=opensearch&language=english_uk)

**Comment by diox** [comment] 2017-04-21 09:43
There will be a "firefox57" tag added to all these add-ons this week (since yesterday it's been added to compatible add-ons at approval time, we just need to run the task to add it to existing ones).

Closing this issue as duplicate of https://github.com/mozilla/addons-server/issues/4974 where we talk about this.

**Closed by diox** 2017-04-21 09:43 UTC
