### ISSUE TITLE
complementos mas valorados 

### ISSUE THREAD

**Issue by LMBFENIX** [mozilla/addons#601] opened 2017-12-24 19:03 UTC
### Describe the problem and steps to reproduce it:
grammar in spanish falta la "**V**" en complementos mas alorados  es complementos mas  Valorados

### What happened?
falta la letra  V  ( alorados )

### What did you expect to happen?
Valorados

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![imagen](https://user-images.githubusercontent.com/34817666/34328674-40f69646-e8c4-11e7-9c43-122d1818da4f.png)
![1](https://user-images.githubusercontent.com/34817666/34328684-a157935a-e8c4-11e7-853d-3365ceeb73ac.png)

**Comment by andymckay** [comment] 2018-01-03 17:16
Thank you for reporting this.

I believe the problem is the missing "v". The translation has been updated from pontoon according to this:

https://github.com/mozilla/addons-frontend/blob/master/locale/es/LC_MESSAGES/amo.po#L419

When the next release of AMO happens this should be fixed.

The next release is tomorrow at 9am PST.

Please check the website sometime after that to see the update.

**Closed by andymckay** 2018-01-03 17:16 UTC

**Comment by kumar303** [comment] 2018-01-03 17:24
> The next release is tomorrow at 9am PST.

To give QA more time on our pre-holiday bucket of code changes, the next release got moved to Thursday Jan 11th at 9am PST.
