### ISSUE TITLE
Can't Have Emoji on Release Note

### ISSUE THREAD

**Issue by Riajyuu** [mozilla/addons#918] opened 2019-02-19 08:14 UTC
### Describe the problem and steps to reproduce it:
1. submit new addon file
2. add emoji to release note string

### What happened?
AMO returns error

### Anything else we should know?
Also happen if edit from dashboard

**Comment by diox** [comment] 2019-02-19 10:27
Hi,

This is a duplicate of https://github.com/mozilla/addons-server/issues/8923 which we're working on and will be fixed soon. Follow that issue for more updates.

**Closed by diox** 2019-02-19 10:27 UTC
