### ISSUE TITLE
addons.mozilla.org recommended extensions random sorting problem

### ISSUE THREAD

**Issue by philip-pirrip** [mozilla/addons#1109] opened 2019-10-02 13:15 UTC
From https://addons.mozilla.org/en-US/firefox/extensions/ go to "See more recommended extensions" https://addons.mozilla.org/en-US/firefox/search/?recommended=true&sort=random&type=extension
Resuly: four pages listing 85 extensions, in random order. But every of the four pages seems to be generated randomly over and over again, and you always get a mix of the addons you've already seen.

**Comment by wagnerand** [comment] 2019-10-02 13:19
Duplicate of #1074

**Closed by wagnerand** 2019-10-02 13:19 UTC
