### ISSUE TITLE
Add-on validation hangs if your add-on's archive contains a top-level folder.

### ISSUE THREAD

**Issue by dutts** [mozilla/addons#231] opened 2016-09-28 08:25 UTC
### Describe the problem and steps to reproduce it:

Steps
- Create an archive of my /addon folder which contains my addon code.
- Go the the manage my submissions page.
- Upload the zip to the submissions page https://addons.mozilla.org/en-US/developers/addon/nomorvom/versions#version-upload
### What happened?
- The upload completed 100%, but then hangs until cancelled on the Validation stage.
### What did you expect to happen?
- I originally reported this as a [bug](https://github.com/mozilla/addons/issues/230) as it looked like we were seeing a reoccurence of old validation delays, but it turned out to be user error (sorry, I will close the bug off). I had created an archive containing a folder rather than the code itself.
- I would expect this is quite easy to detect and fail validation on? I ended up going back to the [docs ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension) before noticing the error of my ways.
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment] 2016-10-25 12:50
A warning is shown that no install.rdf or manifest.json can be found the first time you upload. However for subsequent uploads the validation steps appears to have hung - See also mozilla/addons#252 which describes the same problem.

We need to fix this so the error is always shown.

**Comment by tofumatt** [comment] 2016-10-26 16:22
I've got a train trip coming up, I'll take a look at this on the train 😄

**Comment by muffinresearch** [comment] 2016-10-27 10:37
Thanks @tofumatt

**Comment by tofumatt** [comment] 2016-10-28 12:51
Wondering if this is a RabbitMQ issue (as mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1135471), because when I validate this locally I get an error about not determining add-on type.

**Comment by muffinresearch** [comment] 2016-10-28 13:11
> Wondering if this is a RabbitMQ issue (as mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1135471), because when I validate this locally I get an error about not determining add-on type.

What about the second time? I see the hanging locally after the second time I run the same xpi.

**Comment by tofumatt** [comment] 2016-10-28 13:37
Ah, I started with just the linter but I'll try the server once I'm in
London.

- tofumatt

**Comment by muffinresearch** [comment] 2016-11-08 09:37
@tofumatt any news on this?

**Comment by tofumatt** [comment] 2016-11-08 09:40
Sorry, no, been focused on front end but I'll take another look today.

- tofumatt

**Comment by tofumatt** [comment] 2017-01-18 18:48
I just tested this locally on master and on prod (addons.mozilla.org) and couldn't reproduce it; the original error was that uploading a zip with the add-on in a top-level folder would fail the first time then afterward hang. Seems now I consistently get this error:

<img width="975" alt="screenshot 2017-01-18 18 42 42" src="https://cloud.githubusercontent.com/assets/90871/22078014/6f55bd7c-ddae-11e6-9e53-a4bf95dfb6f3.png">

Which is correct. We might've solved this from checks elsewhere and forgot to test it again.

Closing as fixed, but if you're still encountering this issue please upload the exact add-on you're using and I'll take another look!

**Closed by tofumatt** 2017-01-18 18:48 UTC
Labels: in progress, priority two, triaged
