### ISSUE TITLE
Allow SVG icons

### ISSUE THREAD

**Issue by Dreamsorcerer** [mozilla/addons#1257] opened 2020-10-03 15:28 UTC
### Describe the problem and steps to reproduce it:
When changing the "add-on icon", it says only PNG and JPG are supported and won't allow me to use an SVG.

### What did you expect to happen?
It should be possible to use an SVG as an icon.

**Comment by jvillalobos** [comment] 2020-10-05 17:12
Closing as duplicate of https://github.com/mozilla/addons-server/issues/4161

**Closed by jvillalobos** 2020-10-05 17:12 UTC
