### ISSUE TITLE
personnas themes don't function.

### ISSUE THREAD

**Issue by bevdaily** [mozilla/addons#559] opened 2017-11-20 21:14 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
 i apply theme. click on new tab. no theme. or i apply theme. close browser. reopen later. no theme.
how do i fix this?

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment] 2017-11-20 22:33
Which theme were you trying to apply? Can you please specify the exact steps you followed?

**Comment by bevdaily** [comment] 2017-11-22 17:45
I clicked on personas plus icon on my toolbar then clicked on animated kitty cat and the same appeared. However, the same does not stay when I do either clicking on a new tab or closing the browser and re-opening later

May God's grace be in your life today!

**Comment by muffinresearch** [comment] 2018-01-04 20:11
@bevdaily thanks for the info. Would you be able to expand on the steps you're taking even more?

Ideally the steps you provide should explain how I can reproduce your issue without any prior knowledge at all. You'll need to include as much information as possible.

If possible include screenshots, since a picture can be a quicker way to explain what's going on.

If this problem is actually an issue with a particular add-on e.g: personas plus then please contact the support [1] for that specific add-on since this issue tracker is only for supporting users on the addons.mozilla.org website and not for the support of individual add-ons.

[1] https://discourse.mozilla.org/t/support-personas-plus/6766

**Comment by muffinresearch** [comment] 2018-02-01 14:47
Closing this issue in lieu of further information. Please re-open if you have additional info.

**Closed by muffinresearch** 2018-02-01 14:47 UTC
Labels: needs: info
