### ISSUE TITLE
Suggestion: Prioritise WebExtensions in Addon Search

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#369] opened 2017-04-07 05:52 UTC
Just an Idea ....

Since Firefox has prioritise WebExtensions over other types of addons, it could be an idea to prioritise them in search results to some extent, especially for FF53+ users.

I trust there is already a plan in motion to mark WebExtensions on AMO and searches.

**Comment by diox** [comment] 2017-04-07 09:48
https://github.com/mozilla/addons-server/issues/4974 will highlight them, but we could certainly boost them in searches, yes, that's a good idea.

**Comment by jvillalobos** [comment] 2017-04-07 16:27
That's planned for later in the transition process (Q3, I think), but we might as well keep this bug open for then.

**Comment by Caspy7** [comment] 2017-07-02 04:10
I was going to file a bug, but don't want to create unnecessary noise.

Is it planned to allow users to *explicitly* search for only webextension-based addons?
Is there any reason we cannot enable this right now? I've seen multiple requests for this and would like it myself.
I've encountered several users who are thinking ahead, mulling what they want to do about Firefox 57. Should they switch browsers or are there replacements for their favorites? This could help.

(Right now adding firefox57 to a search does prioritize webextensions.)

**Comment by yfdyh000** [comment] 2017-07-02 10:36
@Caspy7 With https://github.com/mozilla/addons-server/issues/5277 and "Compatible for" in future. With firefox57 tag for now.

**Comment by jvillalobos** [comment] 2017-07-03 17:08
This is a duplicate of https://github.com/mozilla/addons-server/issues/5433 (it was filed earlier, but I forgot about it). It's already done, but we haven't decided on timing yet.

**Closed by jvillalobos** 2017-07-03 17:08 UTC
Labels: triaged

**Comment by erosman** [comment] 2017-07-03 17:31
Good one...

Just for fun.....

This one was filed Apr 7
5433 was filed May 18 (which makes 5433 a duplicate) :)
