### ISSUE TITLE
[Bug]: ReviewerActionReason has invalid validation rules

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#14915] opened 2024-07-18 15:47 UTC
### What happened?

We have loose restrictions on the ReviewActionReason [model](https://github.com/mozilla/addons-server/blob/03b6e5078cfe077e59e310076a2ed2277cc13040/src/olympia/reviewers/models.py#L701-L702)

But strict restrictions on the admin form. This leads to being able to create reasons via django that are not visible in reviewer tools and or wouldn't pass admin validation.

### What did you expect to happen?

We should have consistent validation for the model regardless of where it is created from unless there are special reasons to differ in admin for example. I don't think there are in this case.

~Additionally, there are no default reasons included in our `make initialize` command meaning any new environment cannot reject versions when a reason is required.~ https://github.com/mozilla/addons/issues/14930

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-926)

**Comment by diox** [comment] 2024-07-23 14:53
You can create an active `ReviewerActionReason` with no canned response ; it wouldn't show up in reviewer tools.

@eviljeff thinks it should be fixed at the model level by making either blocked or canned response mandatory. It should then (hopefully!) apply to the admin automatically.

As mentioned in the description, we should also create default ones at initialize time.

**Comment by wagnerand** [comment] 2024-07-23 14:56
> Additionally, there are no default reasons included in our make initialize command meaning any new environment cannot reject versions when a reason is required.

We could also split this off into a separate ticket if that introduces notable additional work. On top of creating ReviewActionReasons, we also need to create CinderPolicies and link the two together.

**Closed** 2024-07-31 15:37 UTC
Labels: component:reviewer_tools, repository:addons-server

**Comment by ioanarusiczki** [comment] 2024-08-06 06:54
I tried to add new review action reasons in  [reviewactionreason](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/reviewactionreason/) and I've noticed that:

- a cinder policy is mandatory (for -stage too if I checked). Is that expected?
- canned response or canned block response is now required 
![a reason](https://github.com/user-attachments/assets/cabdcb8c-9df7-479b-8b8f-c4e4a2d045e3)

- when adding [canned response](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/reviewactionreason/36/change/) the new reason is present in [rev tools pages](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/628016)
- when adding [canned block reason](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/reviewactionreason/35/change/) this will show up in a [blocksubmission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/690/change/)
- or it can show up in rev tools or blocksubmissions with canned response and canned block response. [ Example](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/reviewactionreason/37/change/)

**Comment by eviljeff** [comment] 2024-08-06 09:33
> * a cinder policy is mandatory (for -stage too if I checked). Is that expected?

I didn't change it, but it appears to have been the case since https://github.com/mozilla/addons/issues/9474

**Comment by ioanarusiczki** [comment] 2024-08-06 10:45
I can save the review action reason without adding a Cinder policy when I uncheck "Is active" but then I would not have this reason in rev tools or blocklisting. Hmmm , not making sense yet, even if I'm reading https://github.com/mozilla/addons/issues/9474

**Comment by eviljeff** [comment] 2024-08-06 10:50
> I can save the review action reason without adding a Cinder policy when I uncheck "Is active" but then I would not have this reason in rev tools or blocklisting. Hmmm , not making sense yet, even if I'm reading #9474

From my reading of #9474, that seems to be the intended behaviour, but I didn't work on that issue.

**Comment by ioanarusiczki** [comment] 2024-08-06 10:59
Ah ok, I was thinking what if there would be reasons to be added and not be necessarily Cinder related. Nevermind! Thanks!
