### ISSUE TITLE
All the add-ons are corrupt

### ISSUE THREAD

**Issue by theyearwas1778** [mozilla/addons#1224] opened 2020-08-03 18:35 UTC
### Describe the problem and steps to reproduce it:
All of the add-ons I try to install are corrupt. I search for an add-on, but when I try to install it, it halts installation because the add-on is corrupt. 

### What happened?
The add-on did not install.

### What did you expect to happen?
I expected the add-on to install.

### Anything else we should know?
Your add-ons appear to be broken, or else my particular install of Nightly is. I don't know which.

**Comment by wagnerand** [comment] 2020-08-03 18:44
Can you try in a new profile?

**Comment by theyearwas1778** [comment] 2020-08-03 19:06
Tried it and nope, no joy.

**Comment by wagnerand** [comment] 2020-08-03 19:39
Could you
1. Go to `about:config`, flip the preference `extensions.logging.enabled`
2. Open the Firefox Browser Console (from the _Web Developer_ submenu in the Firefox Menu or _Tools_ menu if you display the menu bar or are on macOS)
3. Try to install an extension from addons.mozilla.org
3. Copy and paste the log entries from the browser console here?

Thanks for your help!

**Comment by theyearwas1778** [comment] 2020-08-03 19:43
No, I cannot. My technical expertise is pretty darn limited. I thought this
was where you went for help. My bad.

**Comment by wagnerand** [comment] 2020-08-03 20:36
Sorry about that! The error message can show up for a number of reasons, and seeing the actual logging information helps us identify the root cause.

**Comment by caitmuenster** [comment] 2020-08-03 21:43
@theyearwas1778 Sorry you're experiencing this. :/ As @wagerand mentioned, there are a few things that can trigger this error and it can be a little tricky to narrow them down. I'll add two more diagnostic questions: 

* Are you running any antivirus software? 
* Is your operating system's clock correct?

**Comment by theyearwas1778** [comment] 2020-08-03 23:42
Yes, I am, and no, it wasn't. And the problem still isn't fixed. I've given
up and gone back to Firefox proper.

**Comment by caitmuenster** [comment] 2020-08-05 15:46
Syncing your operating system's clock and/or disabling the antivirus software may fix this problem -- those are two of the more common reasons why this error gets triggered. Good luck!

**Comment by wagnerand** [comment] 2020-08-26 12:51
Closing for now. Please feel free to reopen if you have more information.

**Closed by wagnerand** 2020-08-26 12:51 UTC
