### ISSUE TITLE
WebExtension beta view on AMO shows graphs and numbers incorrectly

### ISSUE THREAD

**Issue by nodeticswww** [mozilla/addons#1213] opened 2020-06-24 20:54 UTC
Open your WebExtension page on AMO (replace yourCoolAddOn with the actual addon name):

https://addons.mozilla.org/en-GB/firefox/addon/yourCoolAddOn/statistics/beta/?last=365

Look at the numbers and the graphs (they are WAY off).

Then compare it to the old dashboard that shows the correct values:

https://addons.mozilla.org/en-GB/firefox/addon/yourCoolAddOn/statistics/?last=365

--
Also if you open the "By Application" view you see funny versions like "Firefox 4.15", "Firefox 6.1", "Firefox 10.0" and graphs are broken.

"By Add-on version" view shows some version with the name "null".

I understand that this is beta but as such it's not useful.

**Comment by diox** [comment] 2020-06-24 21:11
[The blog post](https://blog.mozilla.org/addons/2020/06/10/improvements-to-statistics-processing-on-amo/) explains why there might be some differences in data. If you see massive differences with your add-on, or weird data, then you need to tell us what the add-on is so that we can investigate more.

**Comment by nodeticswww** [comment] 2020-06-24 21:24
Well for example the beta view shows 50 % fewer users for Cookiebro than the old view (drops from 10 000+ to 4 500+ in the daily peak). That's so big difference that the numbers become meaningless. 

For Feedbro the daily peak user count drops from 68 000+ to 43 000+.

I don't know the statistics but I'm guessing quite many people have telemetry turned off.

**Comment by jvillalobos** [comment] 2020-06-24 21:31
There's an expectation that the numbers will be different. All numbers, new and old, have their pros and cons and there's no _true_ user count to compare to.

The issue with the broken charts and the wonky versions can be seen here:

![Screenshot_2020-06-24 Cookiebro - Cookie Manager Statistics Dashboard Add-ons for Firefox](https://user-images.githubusercontent.com/62568/85629679-889e1100-b62f-11ea-8702-b9d8d4edfb1a.png)

I think it's fallout from the fix in bug 1644088, which initially had some odd data and it looks like some of it wasn't totally cleaned up.

**Comment by nodeticswww** [comment] 2020-06-24 21:50
If this is the final implementation, the wording on the actual WebExtension page should not state "N users". It should say something like "N users with telemetry enabled" as numbers will take a nose dive and the figures have very little to do with the actual user count.

This would help to clear the confusion which will arise when some popular add-ons suddenly appear to lose even millions of users. 

Out of curiosity, what do the numbers look like for uBlock Origin (currently showing 5,5 million users with the old data)? Because I'm betting vast majority of people who has installed uBlock Origin is also savvy enough to turn off telemetry.

**Comment by willdurand** [comment] 2020-06-25 08:16
> There's an expectation that the numbers will be different. All numbers, new and old, have their pros and cons and there's no _true_ user count to compare to.
> 
> The issue with the broken charts and the wonky versions can be seen [here](https://addons.mozilla.org/addon/cookiebro/statistics/beta/usage/applications/?last=365):
> 
> ![Screenshot_2020-06-24 Cookiebro - Cookie Manager Statistics Dashboard Add-ons for Firefox](https://user-images.githubusercontent.com/62568/85629679-889e1100-b62f-11ea-8702-b9d8d4edfb1a.png)
> 
> I think it's fallout from the fix in bug 1644088, which initially had some odd data and it looks like some of it wasn't totally cleaned up.

cc @jklukas , this seems related to something we fixed in the v1 table.

**Comment by jklukas** [comment] 2020-06-25 13:59
I will take a look. I agree this looks like perhaps an artifact of an incorrect backfill. I will see if I can characterize the problem in the underlying table and will backfill if that looks like it will clear up the problem.

**Comment by jklukas** [comment] 2020-06-25 14:59
I've verified in the backend table that there are 4 dates with entries for these suspicious app versions. It very much sounds like an error in backfill. I should be able to have this cleaned up by EOD unless we uncover some new issue with the underlying raw data.

**Comment by jklukas** [comment] 2020-06-25 17:47
Backfill is complete and looks to be successful. I no longer see "6.1" appearing as an app_version in the table, for example.

**Comment by jvillalobos** [comment] 2020-06-25 22:21
Yes, I can confirm this is fixed, thanks @jklukas 

![Screenshot_2020-06-25 Cookiebro - Cookie Manager Statistics Dashboard Add-ons for Firefox](https://user-images.githubusercontent.com/62568/85801242-adfa5000-b6ff-11ea-937b-a82ef477fe9e.png)

We don't have any plans to change what we call the stat in listing pages, but maybe in the future we can add a link or a tooltip that explains how they are calculated.

**Closed by jvillalobos** 2020-06-25 22:21 UTC
