### ISSUE TITLE
all of the add-ons adblock can't be installed. it gives me an error massage. 

### ISSUE THREAD

**Issue by ariellewin11** [mozilla/addons#1022] opened 2019-05-04 20:13 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Every adblock in the addons is broken. It says that it can't be installed because it's broken.

### What happened?
It happened in every one I tried, I tried more than 20.

### What did you expect to happen?
To add an adblocker

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
In an Android phone.

**Comment by J0WI** [comment] 2019-05-04 20:23
This is a duplicate of #1013.
Please refer to https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Closed** 2019-05-04 21:56 UTC
