### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by daveyknits** [mozilla/addons#937] opened 2019-03-04 16:46 UTC
Not sure why I am getting an unexpected error on the general passing.  I have tested the add-on and I am attempting to get it signed for our user base to install.  
![screen shot 2019-03-04 at 11 44 58 am](https://user-images.githubusercontent.com/6126498/53748288-0eaeab00-3e73-11e9-84eb-48ab49ca6a8a.png)

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
_New Version of self distributed Add On _

* Whether your add-on is listed or unlisted.
_Unhlisted_

* The URL where you submitted the add-on.
_https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted_

* The approximate time you submitted the add-on, with timezone.
11:40 AM EST
[gizmo2-firefox.zip](https://github.com/mozilla/addons/files/2927346/gizmo2-firefox.zip)

**Comment by wagnerand** [comment] 2019-03-04 17:17
Duplicate of #896

**Closed by wagnerand** 2019-03-04 17:17 UTC

**Comment by daveyknits** [comment] 2019-03-04 17:23
@wagnerand - I have my manifest.json in the root folder of the zip.  What am I missing here?

**Comment by wagnerand** [comment] 2019-03-04 18:05
@daveyknits That is not what I see from the uploaded file:

```
$ unzip -l gizmo2-firefox.zip
Archive:  gizmo2-firefox.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  03-04-2019 17:31   firefox/
     6148  03-04-2019 17:16   firefox/.DS_Store
        0  03-04-2019 17:32   __MACOSX/
        0  03-04-2019 17:32   __MACOSX/firefox/
      120  03-04-2019 17:16   __MACOSX/firefox/._.DS_Store
        0  03-01-2019 20:38   firefox/dist/
      297  03-01-2019 20:38   firefox/dist/update.xml
     6148  03-04-2019 17:20   firefox/dist/.DS_Store
        0  03-04-2019 17:32   __MACOSX/firefox/dist/
      120  03-04-2019 17:20   __MACOSX/firefox/dist/._.DS_Store
      758  03-04-2019 17:31   firefox/manifest.json
        0  03-01-2019 19:56   firefox/src/
     6148  03-01-2019 19:57   firefox/src/.DS_Store
        0  03-04-2019 17:32   __MACOSX/firefox/src/
      120  03-01-2019 19:57   __MACOSX/firefox/src/._.DS_Store
        0  03-01-2019 20:21   firefox/src/js/
      730  03-01-2019 20:21   firefox/src/js/background.js
   339478  03-01-2019 16:31   firefox/src/js/jquery.js
     1107  03-01-2019 16:31   firefox/src/js/gizmo.js
        0  03-01-2019 19:56   firefox/src/img/
     1176  03-01-2019 17:27   firefox/src/img/gizmo48.png
        0  03-04-2019 17:32   __MACOSX/firefox/src/img/
      480  03-01-2019 17:27   __MACOSX/firefox/src/img/._gizmo48.png
     6148  03-01-2019 19:56   firefox/src/img/.DS_Store
      120  03-01-2019 19:56   __MACOSX/firefox/src/img/._.DS_Store
      429  03-01-2019 17:30   firefox/src/img/gizmo16.png
      480  03-01-2019 17:30   __MACOSX/firefox/src/img/._gizmo16.png
     1727  03-01-2019 17:26   firefox/src/img/gizmo128.png
      480  03-01-2019 17:26   __MACOSX/firefox/src/img/._gizmo128.png
---------                     -------
   372214                     29 files
```

**Comment by daveyknits** [comment] 2019-03-04 18:23
>  758  03-04-2019 17:31   firefox/manifest.json 
That is the root of the /firefox folder where all assets are stored.

**Comment by wagnerand** [comment] 2019-03-04 18:24
The `manifest.json` file needs to be at the root of the zip file, not in a subfolder (`firefox/`).

**Comment by daveyknits** [comment] 2019-03-04 18:54
Ahhh... I see what I was doing wrong.   I was compressing on the folder level - not all items within the folder. 

Thanks!
