### ISSUE TITLE
LeechBlock is gone

### ISSUE THREAD

**Issue by Mojotechnical** [mozilla/addons#1543] opened 2023-12-03 01:26 UTC
Leech block has disappeared from the list of available add-ons. I contacted the developer and he said that you guys have not added it to the list. Is there any way we can figure out what's going on with that?

**Comment by diox** [comment] 2023-12-04 09:58
Hi,

Leechblock is still available: https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng/

If you are talking about Firefox for Android, the author has released a new version (1.6) that is not marked as compatible with Firefox for Android. AMO only considers the latest version when determining whether or not an add-on supports something, so that's why it no longer shows up on Android. It's up to the developer to release a version that works for both Firefox Desktop and Android if they want to support both.

In the future Firefox for Android might support installation from previous versions like it's possible on Desktop, allowing users to install the latest version that was compatible with Android (1.5.8 at the moment). This is not currently supported, though users who already have it installed will keep it.

Closing as it's not a bug, it's up to the developer.

**Closed by diox** 2023-12-04 09:58 UTC

**Comment by Mojotechnical** [comment] 2023-12-04 19:18
There was no resolution for this issue. Bleach block no longer exists on
Android firefox. This is not a developer issue. I directly contacted the
developer. He said you guys removed it and don't bother communicating with
him the reasons so there's nothing you can do to facilitate resolution.
