### ISSUE TITLE
Mismatch between rating/review count in header and actual rating/reviews on search plugin

### ISSUE THREAD

**Issue by mikini** [mozilla/addons#87] opened 2016-04-09 12:12 UTC
Hi there.

I was tricked into installing a meta service search add-on (Twitter - All-in-one Internet Search (SSL & TLS)) using a service at https://aiois.com/ from AMO. While studying the details of the add-on on AMO I noticed that it is listed in the heading as having 18 reviews and a 5 star rating but no reviews or ratings is listed in the review section.

Find that particular add-on at; https://addons.mozilla.org/en-US/firefox/addon/internet-search-twitter/

Looking further into aiois' add-on offerings it seem like they are all developed by an entity called binaryappdev (https://addons.mozilla.org/en-US/firefox/user/binaryappdev/) which also exclusive offer aios search plugins, 136 in total. Every single one of the 20+ add-ons I've checked all have  reviews (varying from 2 and up) and 5 star rating in the header and no reviews listed in the review section. 

I've checked a number of other add-ons and they all match up nicely with number of reviews and plausible ratings. I've also tried connecting using a clean ff profile to see if the pages were modified by a rogue add-on locally at my machine, but I see the same numbers from there.

I can only suspect that they are doing some kind of trickery to AMO systems to boost their add-on installations and drive users to their search site.

Haven't looked that much into what they actually do at aiois.com/binaryappdev.com, it seems murky and it is not something I would use but they might have a plausible user base. I however found them mentioned as a browser hi-jacker at https://www.zemana.com/en-US/removal-guide/how-to-remove-aiois.com-browser-hijacker.

HTML cut-out of the relevant parts of the internet-search-twitter AMO page:
```
<a class="scrollto" id="reviews-link" href="#reviews">
          <span itemprop="ratingCount">18</span> user reviews        </a>
```
```
<section id="reviews" class="primary island c">
  <h2>Reviews</h2>
        <div class="review no-reviews">
      <h3>
        This add-on has not yet been reviewed.
                  <a id="add-first-review" href="/en-US/firefox/addon/internet-search-twitter/reviews/add">
            Be the first!
          </a>
              </h3>
    </div>
</section>
```
Page header of internet-search-twitter add-on showing 18 user reviews and 5 star rating:
![screenshot from 2016-04-09 13-50-54](https://cloud.githubusercontent.com/assets/1330166/14403549/58ac70e4-fe5b-11e5-81a9-08b0d3c6071d.png)
Review section of internet-search-twitter add-on showing no user reviews and no star rating counts:
![screenshot from 2016-04-09 13-50-59](https://cloud.githubusercontent.com/assets/1330166/14403555/94805f9a-fe5b-11e5-898f-9cd710d3f031.png)

**Comment by brampitoyo** [comment] 2016-04-11 00:23
> I can only suspect that they are doing some kind of trickery to AMO systems to boost their add-on installations and drive users to their search site.

Paging @jvillalobos who might know more about these guys and can take action.

Ideally, AMO should have as few bad add-ons like this as possible, and I reckon there are some metrics we can leverage to tell good add-ons from spammy ones: what’s the add-on’s uptake like (too fast for a normal add-on)? Does it receive reviews in a shady way (no comment, all five-stars)?

**Comment by jvillalobos** [comment] 2016-04-12 18:06
It's possible that those reviews were deleted recently, and the star rating and count haven't been updated yet. I don't think this is due to any malicious manipulation.

**Comment by wagnerand** [comment] 2016-07-20 09:28
Sounds like a dupe of https://github.com/mozilla/addons-server/issues/1618

**Closed** 2016-07-20 09:28 UTC
Labels: triaged
