### ISSUE TITLE
Daily user count/number of downloads dropped to zero on 2017/01/12

### ISSUE THREAD

**Issue by mikel2000** [mozilla/addons#310] opened 2017-01-15 08:45 UTC
Daily user count and number of downloads on addons.mozilla.org dropped to zero on 12th of January. Please check e.g. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30.

**Comment by EnTeQuAk** [comment] 2017-01-15 10:35
Closing as duplicate of #309 which is more of a problem of stats not being populated correctly. Once that's fixed it'll be for all of the missing days.

**Closed by EnTeQuAk** 2017-01-15 10:35 UTC
