### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by webextensions** [mozilla/addons#1188] opened 2020-04-06 18:45 UTC
[extension-firefox.zip](https://github.com/mozilla/addons/files/4440197/extension-firefox.zip)

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
**This error occurred during the submission of a new version of an existing add-on**

* Whether your add-on is listed or unlisted.
**The add-on is listed at https://addons.mozilla.org/en-US/firefox/addon/live-editor-for-css-less-sass/**

* The URL where you submitted the add-on.
**https://addons.mozilla.org/en-GB/developers/addon/live-editor-for-css-less-sass/versions/submit/**

* The approximate time you submitted the add-on, with timezone.
**Approx 6:40 PM , 06-April-2020 (UTC time)**

**Comment by webextensions** [comment] 2020-04-06 18:49
![error-in-publishing-new-version](https://user-images.githubusercontent.com/12482916/78594157-d5582400-7858-11ea-87d8-57548c5a195b.png)

**Comment by spoji** [comment] 2020-04-08 01:50
Running web-ext@4.1.0  on this package locally works fine. It shows a proper log with 
`errors          0              
notices         3              
warnings        34`

However, It took around 25 seconds on my local machine. I tried to submit a modified version of the package by removing the huge minified 3.24MB scripts\3rdparty\sass\sass.sync.min.js file and it worked fine. 

My best guess here is that this package hits the validator timeout put in place on the prod server while trying to parse this huge file.

**Comment by webextensions** [comment] 2020-04-17 11:16
@spoji 
Thank you for testing. Would we need to tag someone to make the change for increasing the timeout limit?

Previously, I used to load that sass.sync.min.js file remotely (like in the currently published version). But recently, I was asked to include it along with the extension code itself (by one of the add-on code reviewers). Hence, this issue came up.

**Comment by diox** [comment] 2020-04-17 12:22
Actually a duplicate of https://github.com/mozilla/addons-linter/issues/2506 - the linter is running out of memory parsing that file.

**Comment by diox** [comment] 2020-04-20 11:42
Closing as duplicate of https://github.com/mozilla/addons-linter/issues/2506 - we have tested a fix on the ops side (giving the linter slightly more heap memory) and this will be deployed soon.

**Closed by diox** 2020-04-20 11:42 UTC

**Comment by webextensions** [comment] 2020-04-20 19:40
@diox 
Thank you :-)
