### ISSUE TITLE
"Add to Favorites" lost (with new AMO Style?)

### ISSUE THREAD

**Issue by RainerBielefeld** [mozilla/addons#89] opened 2016-04-14 13:25 UTC
At the *SeaMonkey Internet Suite Blog* (Unofficial News in English language) user "duncanjdiii" [complained](https://unofficialseamonkeynews.wordpress.com/2016/04/09/new-style-at-amo/#comment-14 "Blog Comment)") that he is no longer able to add an add-on to his [Favorite Add-Ons Collection](https://addons.mozilla.org/en-US/firefox/collections/mine/favorites). The *Collections* Pulldown only has an item to **view** that collection, but not to add the current add-on. The link [is on the page](https://unofficialseamonkeynews.wordpress.com/2016/04/09/new-style-at-amo/#comment-15 "See Screenshot"), but the Style does not allow access. Unfortunately [Markus Jaritz](mailto:me@designakt.at) did not answer to my request for the old Style sheet, so I was not able to test whether that function really became lost with the new style.

**Comment by wagnerand** [comment] 2016-04-14 13:40
This is a dupe of https://github.com/mozilla/addons-server/issues/2013#issuecomment-202909497

**Closed by wagnerand** 2016-04-14 13:40 UTC

**Comment by smayer97** [comment] 2016-05-04 07:17
An add-on has been created to fill the gap and restore these links to the AMO site. Check it out here: 
https://addons.mozilla.org/en-GB/firefox/addon/add-to-collection/

Now how to get Mozilla to restore this functionality to the site permanently?

For all those interested, go download this Add-on, and show support for it by writing a positive review. Then spread the word!

**Comment by smayer97** [comment] 2016-05-04 07:19
Also, you may want to add you voice to the discussion here: 
https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/18

**Comment by smayer97** [comment] 2016-05-04 07:38
Also, add your voice to the discussion here: https://github.com/mozilla/addons-server/issues/2264
They seem to be paying attention to this thread.

**Comment by smayer97** [comment] 2017-03-22 05:37
Why were these closed? 
Why was it deliberate? What is the point of removing such important functionality?
WIthout, Firefox is not much different than Chrome, et. al...

Please reconsider!
