### ISSUE TITLE
Null themes appearing on designer profile pages

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons#952] opened 2019-03-13 17:57 UTC
This issue surfaced on MaDonna's[ profile page](https://addons.mozilla.org/en-US/firefox/user/6199839/). 

As you browse through "Themes by MaDonna," you might see 3 themes that have 0 users: 

![MadonnasThemes-Null](https://user-images.githubusercontent.com/23342476/54301930-2a096c80-457d-11e9-81bc-107ae48c9daf.png)

Note, when I first tested this, I was presented with those same three themes in that order when I clicked through more pages of themes by MaDonna. I haven't been able to consistently reproduce that issue. 

When you click on those themes, you hit [this page](https://addons.mozilla.org/en-US/firefox/addon/null/): 

![Screen Shot 2019-03-13 at 10 46 23 AM](https://user-images.githubusercontent.com/23342476/54301984-44434a80-457d-11e9-9fb5-6f6fc8dfe779.png)

When you try to edit the theme, you see this: 

![Screen Shot 2019-03-13 at 10 47 04 AM](https://user-images.githubusercontent.com/23342476/54302062-676dfa00-457d-11e9-9cac-f5567aba4ddf.png)

Note: MaDonna can't update these themes, either. 

Is there a way to permanently remove themes that are registered as "null" so they aren't presented to users, or get them into a state where MaDonna can edit them and fix the metadata?

**Comment by jvillalobos** [comment] 2019-03-13 20:48
Looked into this and found that there are [60 themes that have status Approved but no slug](https://sql.telemetry.mozilla.org/queries/61859/source). I think that's what's causing the problem. Most of them are MaDonna's (duh), and maybe they're showing up now because of the static theme migration.

Assuming they weren't working before and we aren't creating new themes in that state, I think bulk deletion is the way to go.

**Comment by eviljeff** [comment] 2019-03-14 10:36
I'm going to need a link to the page where the themes appear - there are 1690 pages of MaDonna themes in her profile to click through.

> Assuming they weren't working before and we aren't creating new themes in that state

with the new id we can track back to the LWT via the `migrated_personas` table (not in redash unfortunately) if we want to confirm the LWT was missing it's slug too - you're probably right though.

> I think bulk deletion is the way to go.

If you want, or I could write some sql that set the slug to something like `a<id>` and have ops run it.

**Comment by willdurand** [comment] 2019-03-14 15:03
Marked it as p3 but feel free to change the priority.

**Comment by caitmuenster** [comment] 2019-03-14 19:14
> I'm going to need a link to the page where the themes appear - there are 1690 pages of MaDonna themes in her profile to click through.
> 
She and I have both seen them appear on her user profile page (https://addons.mozilla.org/en-US/firefox/user/6199839/), but I haven't been able to reliably reproduce it since filing this bug. 

You can also see them when you click on one of MaDonna's themes -- they are suggested in the "More Themes" pane. Here's an example from https://addons.mozilla.org/en-US/firefox/addon/first-mountain-snow-by-m-donna/ taken just now: 

![More null themes by MaDonna](https://user-images.githubusercontent.com/23342476/54384775-47f4d100-4652-11e9-992c-29e59ff88e25.png)

And here https://addons.mozilla.org/en-US/firefox/addon/aspiring-to-be-green-madonna/ (added bonus: duplicate referrals to null themes): 

![Duplicate referrals to null themes](https://user-images.githubusercontent.com/23342476/54384912-9b671f00-4652-11e9-9e45-0a1b7c997771.png)

**Comment by eviljeff** [comment] 2019-03-15 18:51
Thanks, I was able to get the add-on id and access it on devhub but it's not fixable through there because the edit function seems to rely on loading the existing details via the slug 😒 

https://bugzilla.mozilla.org/show_bug.cgi?id=1535485 might allow us to poke around in sql.telemetry to confirm about the previous LWT missing it's slug, but assuming @jvillalobos's assumption is correct what do we want to do?  Delete them or fix them by giving them a temporary slug that the authors can change?

**Comment by jvillalobos** [comment] 2019-03-15 21:08
I can confirm that the 60 themes [had their original slug broken](https://gist.github.com/jvillalobos/8c57aec776aa8c7087947fa1c2e1db27). It sounds like they've always been broken and there's no value in keeping them.

**Comment by eviljeff** [comment] 2019-03-18 11:43
@wagnerand is going to use django admin to delete them.

(So having ops run `delete from addons where slug IS NULL and status=4 and addontype_id=10;` is avoided)

**Comment by wagnerand** [comment] 2019-03-18 11:56
Done.

```
mysql> SELECT a.id AS `Theme ID`, a2.id AS `LWT ID`, au.user_id AS `Author`
    -> FROM addons AS a
    -> JOIN addons_users AS au ON (a.id = au.addon_id)
    -> JOIN migrated_personas AS mp ON (a.id = mp.static_theme_id)
    -> JOIN addons AS a2 ON (mp.lightweight_theme_id = a2.id)
    -> WHERE a.status = 4 AND a.slug IS NULL AND a2.slug IS NULL;

Empty set (0.99 sec)
```

**Closed by wagnerand** 2019-03-18 11:56 UTC
Labels: component: themes, priority: p3
