### ISSUE TITLE
Wrong number of reviews in the link to extension review page

### ISSUE THREAD

**Issue by rakoczy** [mozilla/addons#433] opened 2017-06-29 16:19 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
The site reports a number of reviews which is different than real number of reviews shown after entering reviews page.
### What happened?
I have entered the following page
https://addons.mozilla.org/en-US/android/addon/360-internet-protection/
then tapped the link named READ ALL 19 REVIEWS and on the page there were only 12 of them under the header "All written reviews". 
### What did you expect to happen?
I have expected 19 reviews.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment] 2017-06-29 17:32
This is a duplicate of https://github.com/mozilla/addons-server/issues/5643 - the difference is that 7 of the 'reviews' don't contain any text, only a star rating, so they're not displayed.

**Closed by eviljeff** 2017-06-29 17:32 UTC
