### ISSUE TITLE
[Task][Task definition WIP]: Content review queue to behave like a queue

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#15070] opened 2024-10-09 13:19 UTC
### Description

As a add-ons content reviewer, I'd like the content review queue to behave more like a queue (items sorted in ascending order of the timestamp they entered the queue) so that we can avoid a random-ish order of items in the queue and get to items in a consistent-timely manner. 

<img width="150" alt="image" src="https://github.com/user-attachments/assets/1063dfb8-83e7-40f0-8492-2cb6f6a74c7a">

## Note about the WIP
We couldn't think of one best way to best arrange the content review queue but have some ideas. 
1. Add-ons are arranged in order of the update of their content (makes the most intuitive sense to a reviewer)
Drawback - Update to content of add-ons with a large audience may stay online for a long(er) time before a content reviewer gets to them. 
2. [Kind of a mitigation to 1.] Add-ons are arranged in order of the update of their content, and the updates to contents of already listed add-ons are delayed until the content reviewer has had a chance to look at them
Drawback - Delays in processing time for updates to be live for established add-ons, resulting in friction.

(I'm creating this ticket to put down the thoughts we already have to start a discussion on how to improve the queue ordering. The requirement definition is still very much missing)

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] TODO
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1121)

**Comment by abhn** [comment] 2024-10-17 12:58
Yep, `both this new column (created datetime of an add-on) and the existing last-updated column should be sortable.` this will cover the use-case of seeing add-ons arranged in a predictable and stable order. 

In case of multi-page content review queue (which doesn't happen often, but still), we'd like the whole queue to be sorted by sort-column actions (and not just add-ons in the current view), (ideally) with a unique URL for each queue sort order to be able to bookmark, and refresh after processing entries.

**Comment by wagnerand** [comment] 2024-10-17 14:41
> In case of multi-page content review queue (which doesn't happen often, but still), we'd like the whole queue to be sorted by sort-column actions (and not just add-ons in the current view), (ideally) with a unique URL for each queue sort order to be able to bookmark, and refresh after processing entries.

To my understanding, that is the default behavior, at least it's what is happening for the other queues as well. Feel free to add a comment to other ticket if it's of concern.

Closing as duplicate of #15077.

**Closed by wagnerand** 2024-10-17 14:41 UTC
Labels: needs:info, repository:addons-server
