### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by i88i** [mozilla/addons#951] opened 2019-03-13 06:02 UTC
[alerter-ebus-ff.zip](https://github.com/mozilla/addons/files/2959960/alerter-ebus-ff.zip)

I am getting an error under "General Tests":
Error: Validation was unable to complete successfully due to an unexpected error.

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
New add-on

I am getting an error under "General Tests":
Error: Validation was unable to complete successfully due to an unexpected error.

* Whether your add-on is listed or unlisted.
Listed

* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.
PDT, Los Angeles, 22:30

**Comment by wagnerand** [comment] 2019-03-13 10:06
Duplicate of #896

**Closed by wagnerand** 2019-03-13 10:06 UTC
