### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by toonytoontoony** [mozilla/addons#411] opened 2017-05-30 09:09 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment] 2017-05-30 09:12
Closing due to lack of information.

Please add information to your issue including the error you encountered, a URL (if applicable), and steps to reproduce.

**Closed by tofumatt** 2017-05-30 09:12 UTC

**Comment by toonytoontoony** [comment] 2017-06-03 01:02
Thanks
