### ISSUE TITLE
French dictionary can’t be downloaded from Thunderbird

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/addons#126] opened 2016-06-03 02:24 UTC
STR:
In Thunderbird 45:
- Edit a new message
- Select text
- Right-click, language, add more dictionaries
- Try to download the French dictionary from the AMO page

Actual result:
The link to download the dictionary is: https://addons.mozilla.org/fr/thunderbird/addon/dictionnaires-fran%C3%A7ais/ (404)

If you open the same AMO page in Firefox (https://addons.mozilla.org/fr/thunderbird/language-tools/), the link is:
https://addons.mozilla.org/fr/thunderbird/addon/dictionnaire-fran%C3%A7ais1/ (correct link)

More details in https://bugzilla.mozilla.org/show_bug.cgi?id=1277477

**Comment by wagnerand** [comment] 2016-06-03 09:24
Dupe of https://github.com/mozilla/addons-server/issues/2823

**Closed by wagnerand** 2016-06-03 09:24 UTC
