### ISSUE TITLE
AMO reports of mconley's Thunderbird addons as "Works with Firefox undefined - undefined"

### ISSUE THREAD

**Issue by dholbert** [mozilla/addons#103] opened 2016-04-29 19:47 UTC
STR:
 1. Visit https://addons.mozilla.org/en-US/firefox/user/mike_conley/
 2. Hover over one of his Thunderbird add-ons, and read the text under the Download Now button.

ACTUAL RESULTS:
Disclaimer says:
>    Works with Firefox undefined - undefined

...which makes no sense. (The add-on is for Thunderbird, not Firefox; and AMO shouldn't be printing "undefined" in a user-facing string.)

**Comment by dholbert** [comment] 2016-04-29 19:57
![screenshot](https://cloud.githubusercontent.com/assets/426803/14927953/dc27cc76-0e09-11e6-8a60-24c42c7a4d5b.png)

**Comment by dholbert** [comment] 2016-04-29 19:59
(CC @mikeconley in case he's interested)

**Comment by mikeconley** [comment] 2016-04-29 20:17
Finally, I'm a test case!

**Comment by jvillalobos** [comment] 2016-04-29 21:50
This is an [old bug](https://bugzilla.mozilla.org/show_bug.cgi?id=800090). I'll close the original since we're moving away from Bugzilla.

**Comment by andymckay** [comment] 2016-04-29 22:01
Its a dupe of mozilla/addons-server#1599, its a problem when you have add-ons for a particular platform (eg Thunderbird) and then view them in another user agent (eg Firefox). Closing in favour of the other bug.

**Closed by andymckay** 2016-04-29 22:01 UTC
