### ISSUE TITLE
"Problem Retrieving Review Notes" on Addon Version History

### ISSUE THREAD

**Issue by nickcorrieri** [mozilla/addons#312] opened 2017-01-17 18:37 UTC
### Describe the problem and steps to reproduce it:

When logged in as a Developer and Managing your Addon,
Click any review notes from the "Versions" page of addons, in either Chrome or Firefox, you will see this error.

(example url: https://addons.mozilla.org/en-US/developers/addon/...../versions

### What happened?

Error message appears, with api endpoint (and json response) in place of where Version Review Notes would go for an APPROVED / public addon, as well as a draft/rejected version

(truncated full error)
````
We had a problem retrieving review notes

/api/v3/addons/addon/672364/versions/1990836/reviewnotes/, OK, {"count":3,"next":null,"previous":null,"results":[{"id":7990588,"action":"approved","action_label":"Ap................. (truncated)
....
````
### What did you expect to happen?

Notes rendered in view.

### Anything else we should know?
Mac - latest stable releases of Chrome, Firefox.

**Comment by muffinresearch** [comment] 2017-05-08 14:15
This sounds like a dupe of https://github.com/mozilla/addons-server/issues/5093, however please re-open if this is still a problem.

**Closed by muffinresearch** 2017-05-08 14:15 UTC
