### ISSUE TITLE
Unable to download any add-ons

### ISSUE THREAD

**Issue by katherinegb** [mozilla/addons#978] opened 2019-05-04 00:42 UTC
I can't download any add-ons, instead I keep getting "Download failed. Please check your connection." error message despite which add-ons I try to download. My connection is fine.
<hr/>

Follow https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 for updates

**Comment by fgimenezm** [comment] 2019-05-04 00:45
Same here. Also getting isntalled addons disabled due to failed verification.
Just tried to install Ghostery from the catalog and got this on browser console:
```
1556930525854	addons.xpi-utils	WARN	Add-on firefox@ghostery.com is not correctly signed.

1556930525862	addons.xpi	WARN	Download of https://addons.mozilla.org/firefox/downloads/file/1752924/ghostery_privacy_ad_blocker-8.3.3-an+fx.xpi?src=dp-btn-primary failed: signature verification failed
```

**Comment by davidmichaelhale** [comment] 2019-05-04 00:47
Getting same issue. Said all of my add-on's weren't verifiable all of a sudden. Was recommended to try "refreshing" Firefox, well now it won't even let me download any like above says, and all of my add-on's (and their settings I assume) are gone.

**Comment by katherinegb** [comment] 2019-05-04 00:48
Yes! The exact same thing happened to me with my previously installed add-ons. Glad it's not just me, I guess.

**Comment by Kas1894** [comment] 2019-05-04 00:48
Same issue as @davidmichaelhale and the others, with the behavior of the addons being marked as "unverifiable".  I think it happened after an update of some sorts?

OS: Windows 10 Ver. 1809
Firefox Version: was using Firefox Beta version 67.x, tried downgrading to stable 66.0.3 to see if that fixes the issue, but no dice.

**Comment by Kas1894** [comment] 2019-05-04 00:50
Possibly related to issue #851?

**Comment by rmrfmss** [comment] 2019-05-04 00:51
exact same issue here. can't download addons, i receive a `Download failed. Please check your connection.` message whenever i try to.

os: linux from scratch 8.4, gentoo 17.0/ ~amd64
firefox ver: 60.5.2-esr, 66.0.3, 65.0.2

**Comment by jobymatwick** [comment] 2019-05-04 00:53
Same here All but 2 addons were disabled and i cant download new ones.

**Comment by Kas1894** [comment] 2019-05-04 00:54
I tried to reproduce @fgimenezm saw on the browser console (assuming the F12 developer tools?), but mine showed this:

`[GA: ON] set 
Object { dimension: "dimension4", value: "TAAR_COHORT_INCLUDED" }
BigInteger.js:27
[GA: ON] set 
Object { dimension: "dimension5", value: "TAAR-LITE-AB" }
BigInteger.js:27
Setting add-on status BigInteger.js:27
Add-on "firefox@ghostery.com" not found so setting status to UNINSTALLED; exact error: Error: Addon not found BigInteger.js:27
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Recommendations Shown","eventAction":"recommended","eventLabel":"Ghostery – Privacy Ad Blocker"} BigInteger.js:27
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs Started","eventAction":"addon","eventLabel":"Ghostery – Privacy Ad Blocker"} BigInteger.js:27
[install] Adding listener for onDownloadStarted BigInteger.js:27
[install] Adding listener for onDownloadProgress BigInteger.js:27
[install] Adding listener for onDownloadEnded BigInteger.js:27
[install] Adding listener for onDownloadCancelled BigInteger.js:27
[install] Adding listener for onDownloadFailed BigInteger.js:27
[install] Adding listener for onInstallStarted BigInteger.js:27
[install] Adding listener for onInstallProgress BigInteger.js:27
[install] Adding listener for onInstallEnded BigInteger.js:27
[install] Adding listener for onInstallCancelled BigInteger.js:27
[install] Adding listener for onInstallFailed BigInteger.js:27
Events to handle the installation initialized. BigInteger.js:27
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs Download Failed","eventAction":"addon","eventLabel":"Ghostery – Privacy Ad Blocker"} BigInteger.js:27
Error: 
`
It just spits out a blank error.

**Comment by david-alleyn** [comment] 2019-05-04 00:55
This happened to me as well.

**Comment by fgimenezm** [comment] 2019-05-04 00:55
> 
> 
> I tried to reproduce @fgimenezm saw on the browser console (assuming the F12 developer tools?), but mine showed this:
> 
> `[GA: ON] set Object { dimension: "dimension4", value: "TAAR_COHORT_INCLUDED" } BigInteger.js:27 [GA: ON] set Object { dimension: "dimension5", value: "TAAR-LITE-AB" } BigInteger.js:27 Setting add-on status BigInteger.js:27 Add-on "firefox@ghostery.com" not found so setting status to UNINSTALLED; exact error: Error: Addon not found BigInteger.js:27 [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Recommendations Shown","eventAction":"recommended","eventLabel":"Ghostery – Privacy Ad Blocker"} BigInteger.js:27 [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs Started","eventAction":"addon","eventLabel":"Ghostery – Privacy Ad Blocker"} BigInteger.js:27 [install] Adding listener for onDownloadStarted BigInteger.js:27 [install] Adding listener for onDownloadProgress BigInteger.js:27 [install] Adding listener for onDownloadEnded BigInteger.js:27 [install] Adding listener for onDownloadCancelled BigInteger.js:27 [install] Adding listener for onDownloadFailed BigInteger.js:27 [install] Adding listener for onInstallStarted BigInteger.js:27 [install] Adding listener for onInstallProgress BigInteger.js:27 [install] Adding listener for onInstallEnded BigInteger.js:27 [install] Adding listener for onInstallCancelled BigInteger.js:27 [install] Adding listener for onInstallFailed BigInteger.js:27 Events to handle the installation initialized. BigInteger.js:27 [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs Download Failed","eventAction":"addon","eventLabel":"Ghostery – Privacy Ad Blocker"} BigInteger.js:27 Error: `
> It just spits out a blank error.

There is a "browser console". CTRL-SHIFT-J activates in on my firefox (which is in spanish but I guess the hotkey should be the same)

**Comment by Floogen** [comment] 2019-05-04 00:57
Exact same issue as @davidmichaelhale here. Attempting to install plugins gives the the same error message as @rmrfmss said. 

I tried to download one my missing extensions directly and was given an error of "the add-on downloaded from this could not be installed because it appears to be corrupt".

Seems to be pretty similar to issue #851

**Comment by codeman38** [comment] 2019-05-04 00:58
Experiencing this as well. All of my extensions in my main profile are marked as "___ could not be verified for use in Firefox and has been disabled". Trying to remove them and reinstall them gives "Download failed. Please check your connection." I even tried creating a clean profile and installing [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/?src=search), and got the error even then.

(Firefox 66.0.3, MacOS 10.14.4)

**Comment by grahamperrin** [comment] 2019-05-04 00:58
https://pastebin.com/SdbKaSDa output from curl, does this help?

**Comment by jacobschaer** [comment] 2019-05-04 01:00
I'm having the same problem with all addons. Manually downloaded a couple that had been disabled and Firefox fails saying they're corrupt.

**Comment by Kas1894** [comment] 2019-05-04 01:02
@fgimenezm Ah, thanks. Didn't know that was a think

Paste of the entire output from loading the page to trying to download Ghostery below. 

https://pastebin.com/W9tyKFSw

**Comment by Kas1894** [comment] 2019-05-04 01:05
Maybe this is a certificate/signing error of some sorts? That might explain why some add-ons are suddenly being marked as "unverifiable".

The only add-on that escaped unscathed for me is [Privacy Pass](https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/).

**Comment by MatrixPeckham** [comment] 2019-05-04 01:08
Chiming in with the same issue. I only use 2 addons and they both were disabled and I get the same "please check connection" error when I try to re-download them. My addons were Adblock Plus and Reddit Enhancement Suite (RES).

**Comment by codeman38** [comment] 2019-05-04 01:08
I noticed this error in the log from installing Tree Style Tab, which smells very strongly of #851:

```1556931683822	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing variable_color_icons: An unexpected property was found in the WebExtension manifest.```

**Comment by brensurio** [comment] 2019-05-04 01:09
I'm having this issue too. ABP is basically my drugs, I can't go on without it. Containers also don't work.

**Comment by grahamperrin** [comment] 2019-05-04 01:09
For a session that does nothing more than attempt to add a featured extension https://addons.mozilla.org/en-GB/firefox/addon/malwarebytes/?src=featured that was last updated 23 days ago: 

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Sat  4 May 2019 02:06:47 BST
FreeBSD 13.0-CURRENT r346795 GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 66.0.3_2,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % firefox -p titsup

(firefox:45278): Gtk-WARNING **: 02:07:18.037: gtk_window_present_with_time() should not be called with 0, or GDK_CURRENT_TIME as a timestamp, the timestamp should instead be gathered at the time the user initiated the request for the window to be shown
1556932042882   addons.xpi-utils        WARN    Add-on undefined is not correctly signed.
1556932042882   addons.xpi-utils        WARN    Add-on undefined is not correctly signed.
1556932042883   addons.xpi      WARN    Download of https://addons.mozilla.org/firefox/downloads/file/1738961/malwarebytes_browser_extension-1.0.44-an+fx.xpi?src=dp-btn-primary failed: Error: Cannot find id for addon /tmp/tmp-lia.xpi(resource://gre/modules/addons/XPIInstall.jsm:1319:19) JS Stack trace: loadManifest@XPIInstall.jsm:1319:19
JavaScript error: , line 0: Error: 
```

**Comment by Kas1894** [comment] 2019-05-04 01:16
I agree that it's probably very much related to #851. In my logs, when I look at the js file mentioned here:
```
"Got install event for unknown install 7 amWebAPI.js:54
    receiveMessage jar:file:///C:/Program Files/Mozilla Firefox/omni.ja!/components/amWebAPI.js:54"
```
The code block it highlights states the following:

```js
 case MSG_INSTALL_EVENT: {
        let install = this._installMap.get(payload.id);
        if (!install) {
          let err = new Error(`Got install event for unknown install ${payload.id}`);
          Cu.reportError(err);
          return;
        }
```
Looks to be related to the payload id.

**Comment by alexisfrjp** [comment] 2019-05-04 01:16
Same here, I had the 66.0.2 installed from the first day and only 30min ago, all my addons (found on the official firefox website) have been disabled and all their data removed!
Seems to be a Firefox issue to have all the same issue at the same time.

**Comment by grahamperrin** [comment] 2019-05-04 01:21
ℹ

---- 

OK folks, I see (in IRC) that a Product Manager is aware of the wide impact. tl;dr

> … it's being handled quickly

I suggest limiting the number of "Me too" comments here and/or under #851

Thanks

**Comment by martinm1000** [comment] 2019-05-04 01:21
> Maybe this is a certificate/signing error of some sorts? That might explain why some add-ons are suddenly being marked as "unverifiable".

Its quite possible, over on reddit some people might have hit this earlier (I don't know their timezone) and some of them had their clock time wrong.

**Comment by leycec** [comment] 2019-05-04 01:22
Mozilla just locked #851 as "spam." Expect similar treatment here shortly.

**Comment by brianhenk** [comment] 2019-05-04 01:22
I reported this in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1548983

**Comment by Kas1894** [comment] 2019-05-04 01:23
I hope they publish a postmortem, regardless of what happens. Would be interesting to hear what actually happened.

**Comment by diox** [comment] 2019-05-04 01:25
I'm locking this like I did in #851 because no new information is being added. We're aware and we're working on it.

**Comment by diox** [comment] 2019-05-04 11:44
From [discourse](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/13):
> We rolled-out a fix for release, beta and nightly users on Desktop. The fix will be automatically applied in the background within the next few hours, you don’t need to take active steps.
>
> In order to be able to provide this fix on short notice, we are using the Studies system. You can check if you have studies enabled by going to Firefox Preferences -> Privacy & Security -> Allow Firefox to install and run studies.
>
> You can disable studies again after your add-ons have been re-enabled.
>
> We are working on a general fix that doesn’t need to rely on this and will keep you updated.

**Closed** 2019-05-04 13:32 UTC

**Comment by diox** [comment] 2019-05-04 14:30
blog post: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
