### ISSUE TITLE
Addon not signed if strict_min_version is too old

### ISSUE THREAD

**Issue by vaindil** [mozilla/addons#338] opened 2017-02-27 21:47 UTC
### Describe the problem and steps to reproduce it:

I used `web-ext sign` (with the appropriate credentials) to sign an addon. My manifest included this:

```json
"applications": {
  "gecko": {
    "id": "8a148ff1-f802-4021-9fc0-f50f66f584fd@jetpack",
    "strict_min_version": "36.0"
  }
}
```

### What happened?

The addon passed validation with zero warnings/errors and was listed as approved on the dashboard, but it was not signed. The CLI returned this:

> sign: Error: The XPI was processed but no signed files were found. Check your manifest and make sure it targets Firefox as an application.

### What did you expect to happen?

The addon should have been signed.

### Anything else we should know?

The problem was that `strict_min_version` was too old for WebExtensions support. Once I changed that to `45.0` the addon passed and was signed as expected. A better error message would be great.

**Comment by andymckay** [comment] 2017-02-27 22:18
@cgrebs, this check is done in add-ons server I believe, not the linter?

**Comment by wagnerand** [comment] 2017-02-27 22:24
I would assume so. I ran `web-ext lint` against the file in question and did not get any errors or warnings, just an unrelated notice (`PROP_VERSION_TOOLKIT_ONLY`).

**Comment by muffinresearch** [comment] 2017-05-05 09:50
Possibly a dupe of https://github.com/mozilla/addons-linter/issues/931

**Comment by vasilicamihasca** [comment] 2017-05-23 09:40
This is not a dupe of mozilla/addons-linter#931 because that bug seems to be fixed.
Tried to submit on AMO-dev using Firefox 55.0a1 (2017-05-22) a webextension ([apply-css.zip](https://github.com/mozilla/addons/files/1021650/apply-css.zip)) as described in the first comment (strict_min_version=36.0) and noticed the following:
- no error is displayed at validation
- the platform checkboxes are disabled 
- the submission process could not be continued because at least one platform must be checked 

See attached screenshot:
![2017-05-23_1234](https://cloud.githubusercontent.com/assets/18114210/26348185/98c20f36-3fb4-11e7-8903-5f60b83dc17a.png)

**Comment by diox** [comment] 2017-09-11 13:43
https://github.com/mozilla/addons-server/commit/0bd3683522c03edf8f97707d7f7fcc9d67320f1d should have fixed this, as part of the fix for https://github.com/mozilla/addons-server/issues/6188

**Comment by diox** [comment] 2017-09-11 13:45
Actually, no, never mind, it still fails at the platforms step as described in https://github.com/mozilla/addons/issues/338#issuecomment-303346160 :(

**Closed** 2017-09-11 16:10 UTC
Labels: in progress, state: pull request ready, triaged
