### ISSUE TITLE
Unable to reply to review

### ISSUE THREAD

**Issue by nE0sIghT** [mozilla/addons#800] opened 2018-10-01 18:32 UTC
### Describe the problem and steps to reproduce it:
Go to own extension reviews page.

### What happened?
No "answer" button available for reviews.

### What did you expect to happen?
"Answer" button must be available for reviews of owned extensions.

### Anything else we should know?
Reproduced at https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/reviews/;
Screenshot:
![selection_044](https://user-images.githubusercontent.com/3389586/46308123-e112bc80-c5c9-11e8-9547-7d971fbd938e.png)

**Comment by kumar303** [comment] 2018-10-01 18:46
Hi, thanks for filing a bug. I can't reproduce this with my own developer account. Are you sure that you signed in with this [exact user account](https://addons.mozilla.org/en-US/firefox/user/nE0sIghT/)? I mean, I can see that there is a bug here somehow because it shows *Edit my reply* on the developer response.

**Comment by nE0sIghT** [comment] 2018-10-01 20:30
@kumar303 

Yes, I'm sure. Here is screenshot.
Just tell me if I can somehow help to debug this issue.

![selection_045](https://user-images.githubusercontent.com/3389586/46313980-59817980-c5da-11e8-85ff-ec4ee9ebf356.png)

**Comment by nE0sIghT** [comment] 2018-10-01 20:32
@kumar303 

There is some bug I see at https://addons.mozilla.org/en-US/firefox/user/nE0sIghT/:
One time I get to this page I see screen posted above.
Another time I see that:

![selection_046](https://user-images.githubusercontent.com/3389586/46314093-a9f8d700-c5da-11e8-8692-24a5bfc1d211.png)

**Comment by nE0sIghT** [comment] 2018-10-01 20:38
For what I see now - I have 2 emails bound to extensions as "Owner".
And looks like - there are 2 accounts for both email with one nick name.

From one account (marked as "Listed") I can answer to reviews. From another account - I can not. Hovewer some time ago I answered using this account without problems.

**Comment by kumar303** [comment] 2018-10-01 22:02
Thanks for the detailed info. I see what's happening now. We have another bug open to track this so I'm closing this one but we will fix it shortly. You can press the subscribe button on https://github.com/mozilla/addons-frontend/issues/6475 to follow updates.

**Closed by kumar303** 2018-10-01 22:02 UTC
