### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by JimNV** [mozilla/addons#1396] opened 2022-03-08 15:34 UTC
Please attach a copy of your add-on, and fill in the following information:

[nvis-firefox-extension.zip](https://github.com/mozilla/addons/files/8207488/nvis-firefox-extension.zip)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

Submission of a new add-on.  This add-on works without problems when tested as a Temporary Add-on.

* Whether your add-on is listed or unlisted.

Not listed, yet.

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.

March 8, at about 16:33 CET

**Comment by JimNV** [comment] 2022-04-13 10:59
Anyone? This is really annoying - would appreciate a proper error message.  Cheers.

**Comment by diox** [comment] 2022-04-13 11:30
Hi,

Sorry we missed your report earlier. This is a duplicate of https://github.com/mozilla/addons/issues/1403 which we are working on.

**Closed by diox** 2022-04-13 11:30 UTC
