### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by bmarotta** [mozilla/addons#469] opened 2017-08-12 08:37 UTC
Addon Validation Error occurs on General Tests:

Sorry, we couldn't load your WebExtension.

Error: Validation was unable to complete successfully due to an unexpected error.

* This error occurred during the submission of a new add-on

* Add-on is to be listed

* The URL where I submitted the add-on is: https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

* 10:37 CET
[im-a-puzzle-ff.zip](https://github.com/mozilla/addons/files/1219605/im-a-puzzle-ff.zip)

**Comment by wagnerand** [comment] 2017-08-12 10:20
Thank you for the report. This is a duplicate of https://github.com/mozilla/addons-server/issues/6111.

Microsoft already provided a fix, see https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator

**Closed by wagnerand** 2017-08-12 10:20 UTC

**Comment by bmarotta** [comment] 2017-08-12 13:52
Hi Wagnerand,

Thanks for the quick feedback. As Im not the first  (nor the last) I think that the validor should be enhanced to give a better error message in this case. Something like : An error ocurred unzipping your file. Please check for the zip correctness and try again.

Do you agree?

**Comment by wagnerand** [comment] 2017-08-12 16:09
That is what the linked issue is about.
