### ISSUE TITLE
TableTools

### ISSUE THREAD

**Issue by Nishi** [mozilla/addons#725] opened 2018-05-25 15:18 UTC
### Describe the problem and steps to reproduce it:
Extension search is stupid, if I search for "table tool", I don't need "tab management".
"Table" and "tab" are totally different things.

### What happened?
Impossible to find replacement of TableTools addon, too much spam in search results.

### What did you expect to happen?
I expected to get ONE result for the query - a replacement for the Table Tool extension.

**Comment by muffinresearch** [comment] 2018-05-30 11:31
Duplicate of https://github.com/mozilla/addons-server/issues/6837

**Closed by muffinresearch** 2018-05-30 11:31 UTC
