### ISSUE TITLE
No easy or clear way to get the source code for an addon

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/addons#463] opened 2017-08-10 03:09 UTC
For example https://addons.mozilla.org/en-US/firefox/addon/adblock-for-youtube is apparently licensed under the MPL but there's no clear way to get the source code.

**Comment by EnTeQuAk** [comment] 2017-08-10 06:34
We had that option in the past but had to disable it for various reasons. I'm closing this as a duplicate of https://github.com/mozilla/addons-server/issues/5135 which essentially tells the story.

We are aware and will be working towards a solution so that the author of an add-on can link their sources, this isn't done yet though.

**Closed by EnTeQuAk** 2017-08-10 06:34 UTC
