### ISSUE TITLE
Error: "Could not parse the manifest file" during autotest on addons.mozilla.org

### ISSUE THREAD

**Issue by artembowl** [mozilla/addons#85] opened 2016-04-08 12:29 UTC
Hello!

I'm trying to upload my addon on addons.mozilla.org, but at the stage of the automatic test get the error: Could not parse the manifest file.
The addon is made by a "jpm xpi" command. During packing no errors. 

My xpi: _deleted_

Best regards.

**Comment by jvillalobos** [comment] 2016-04-08 19:23
I [gave it a try](https://addons.mozilla.org/en-US/developers/upload/6bc0a13a0c5c49d4b82728d003dd1a4d) and the validation results don't show any errors. Can you please try again, to see if it was a temporary problem?

**Comment by artembowl** [comment] 2016-04-08 19:46
@jvillalobos [http://i.imgur.com/CX7ZCxt.png](url)

**Comment by jvillalobos** [comment] 2016-04-08 19:56
@andymckay This looks new, so maybe a regression from the last push. The XPI installs okay in Firefox and passes the standalone validator, but it's failing on submission with the `Could not parse the manifest file.` error.

**Comment by artembowl** [comment] 2016-04-08 19:57
@jvillalobos And what to do with it?(

**Comment by jvillalobos** [comment] 2016-04-08 20:51
I'd like to get a response from the developers first just to make sure there's nothing wrong with the file. If there isn't, I can upload it for you while the bug is being fixed.

**Comment by artembowl** [comment] 2016-04-08 20:57
@jvillalobos It would be nice if you uploaded! It can be tied to my account, so I edited the description, added screenshots, etc? (www.smarty.sale@gmail.com)

**Comment by jvillalobos** [comment] 2016-04-08 22:43
I can upload it and link it to your account, once I hear back from the devs.

**Comment by jvillalobos** [comment] 2016-04-14 16:39
@artembowl are you still having this problem? Can you please post the XPI again?

**Comment by EnTeQuAk** [comment] 2016-04-20 14:16
I'm closing this issue for now. @artembowl please let us know if the issue still exists and if it does it'd be awesome if you could post the XPI file again or email it if you want.

**Comment by Pugnator** [comment] 2016-06-01 15:47
@artembowl I'm experience the same issue at the moment. I can reproduce it in a stable way. The issue occurs when manifest is in UTF-8 encoding. Even if it does't content anything non-english. But it passes standalone validation though
[kanization.zip](https://github.com/mozilla/addons/files/293789/kanization.zip)

**Comment by EnTeQuAk** [comment] 2016-06-01 16:41
Thanks for the upload @Pugnator, that helps a lot!

it appears the problem is that there's a BOM in the manifest which the json parsing code in AMO doesn't handle. I guess I'm going to steal `unicodehelper` from `amo-validator.

**Closed** 2016-06-02 12:13 UTC
Labels: pull request ready

**Comment by artembowl** [comment] 2016-06-09 10:02
Hello! Error still exist..
[ext.zip](https://github.com/mozilla/addons/files/306628/ext.zip)

**Comment by muffinresearch** [comment] 2016-06-09 10:18
@artembowl looks like this fix will be only in production later today.

**Comment by artembowl** [comment] 2016-06-09 10:39
please tell me if I upload my addon here https://addons-dev.allizom.org (here unloading works and there are no errors), then it will appear in the main store - https://addons.mozilla.org/?

**Comment by muffinresearch** [comment] 2016-06-09 10:41
No - that's just -dev, it doesn't affect the production version.

**Comment by artembowl** [comment] 2016-06-15 12:49
Please, tell me, when upload add-ons will work? it's been two months... And I see all the same error when trying to upload our addon..

**Comment by artembowl** [comment] 2016-06-18 22:30
Heeeeeyyyyyyy!

**Comment by EnTeQuAk** [comment] 2016-06-20 15:58
hey @artembowl, sorry for the late reply. We were in London for an All Hands last week.

I fixed the problem @Pugnator reported regarding the manifest utf8 bom parsing which is now in production but apparently you see something different? Can you maybe upload the `manifest.json` file somewhere so that I can have a closer look and try to reproduce things?

**Comment by artembowl** [comment] 2016-06-21 11:01
@EnTeQuAk, i wrote earlier ...
 I do not manifest file, only package.json exist, generated by jpm..
My .xpi uploaded inside zip archive in this post: https://github.com/mozilla/addons/issues/85#issuecomment-224851993

**Comment by EnTeQuAk** [comment] 2016-06-21 11:04
ah, I didn't see that post. Thanks, I'll check :)

**Comment by artembowl** [comment] 2016-06-21 11:09
@EnTeQuAk, and... on https://addons-dev.allizom.org my addon passed tests without errors and uploaded successfully.

**Comment by EnTeQuAk** [comment] 2016-06-21 11:09
yeah, that's what I tried right now and it worked. So this happens only on production?

**Comment by EnTeQuAk** [comment] 2016-06-21 11:15
ah, it happens on stage too

**Comment by EnTeQuAk** [comment] 2016-06-21 11:20
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-29: ordinal not in range(128)` while extracting the zip, this is weird that it's not happening on -dev though.

**Comment by EnTeQuAk** [comment] 2016-06-22 17:12
We tagged yesterday and whatever was on `-dev` is now on http://addons.allizom.org/ too and it now works for me there. Not sure if we just failed to push the patch or whatever. This version will go live on Thursday sometime around 4-6pm UTC or a bit later and and you should be able to upload it then there too.
