### ISSUE TITLE
Scopus  download 

### ISSUE THREAD

**Issue by eholzbe** [mozilla/addons#1540] opened 2023-11-26 12:48 UTC
I tried to download a paper from Scopus. After clicking the button I got a small window with the note:

The Scopus Document Download Manager requires an extension Help/More Information
We created a fast and lightweight solution for the Firefox browser.
Click the button (Get extension) below to download the extension:

I clicked the button and obtained the message:
We're sorry, but we can't find what you're looking for.

under the header Firefox add-ons. Firefox is the standard browser on this computer.

**Comment by wagnerand** [comment] 2023-12-07 16:07
Likely a duplicate of https://github.com/mozilla/addons/issues/1546. I know this one is older, but some conversation to identify the issue is already happening over there.

**Closed** 2023-12-08 13:06 UTC
