### ISSUE TITLE
Image is truncated if description is too long

### ISSUE THREAD

**Issue by alice0775** [mozilla/addons#881] opened 2019-01-23 13:48 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
1. Open https://addons.mozilla.org/en-US/firefox/addon/scrapbookq/
2. Click thumbnail to see image
3. Click [>] icon several times so that 3rd image will be showing

### What happened?
Image is truncated, see screenshot https://screenshots.firefox.com/QKfNbWCJ3uljoPnr/addons.mozilla.org

### What did you expect to happen?
At least scrollbar should be provided to see whole image

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment] 2019-01-23 14:16
This looks like a duplicate of https://github.com/mozilla/addons-frontend/issues/4499

**Comment by eviljeff** [comment] 2019-01-25 06:57
yeah, it's a dupe

**Closed by eviljeff** 2019-01-25 06:57 UTC
