### ISSUE TITLE
"New Tab Override" 14.0.2: new bug with Firefox 16.0.1: can't type in URL bar

### ISSUE THREAD

**Issue by hbeckwith** [mozilla/addons#752] opened 2018-07-16 23:03 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
NEW BUG AFTER INSTALLING FF 61.0.1
WIndows 8.1, Firefox 61.0.1, newly downloaded New Tab Override 14.0.2, no other FF add-ons.
In FF, type Control-T or click the new-tab + 

### What happened?
New tab appears: blank page, furiously flashing top tab. It is impossible to type into the URL bar.  Attempting to type there opens a pull-down and each keystroke jumps to a different entry in it.
I have to click the Home button for the flashing to stop and the URL bar to accept typing.

### What did you expect to happen?
WHat always happened before FF 61.0.1: a usable new tab opens showing to the page I specified in New Tab Override setup.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Lots of Google searches to fine any recognition of this problem.  I'm not up to posting on techie forums.  I did find this Mozilla Foundation review (https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/reviews/) .  It mentions the blank page and the flashing, but nothing about the unusable URL bar.

How do I know about responses?  Just keep visiting this page?

**Comment by wagnerand** [comment] 2018-07-17 09:33
Duplicate of #751

**Closed by wagnerand** 2018-07-17 09:33 UTC
