### ISSUE TITLE
Can not Submit a New Add-on

### ISSUE THREAD

**Issue by ikukei** [mozilla/addons#904] opened 2019-02-10 14:21 UTC
### Describe the problem and steps to reproduce it:
Before 'Submit a New Add-on', I had to accept  Agreement and the Rules and Policies.
But I can not receive 'https://www.google.com/recaptcha/api.js?hl=zh' in China.
I can not see the validation image.

### What happened?
But I can not receive 'https://www.google.com/recaptcha/api.js?hl=zh' in China.
I can not see the validation image.

### What did you expect to happen?
You'd better to implement recaptcha api in your own sites.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment] 2019-02-13 13:52
This is a duplicate of mozilla/addons-server#9627 - caused by Google recaptcha (or anything Google) not being available in China.  We don't really have a workaround other than connecting via a VPN for that first submission (once you agree we don't show the validation image again)

**Closed by eviljeff** 2019-02-13 13:52 UTC

**Comment by raphj** [comment] 2019-07-07 16:29
Hello,

Being privacy conscious, I block code that I don't trust, and that includes reCAPTCHA which is a giant blob of proprietary code and relies on tracking its users.

I can't submit an addon for this reason. Mozilla being focused on privacy should do something about this issue. Please, consider getting rid of reCAPTCHA or provide an alternative method for submitting an addon. I'm using Firefox partly for its focus on privacy and for it being free software. It would be "funny" to have to run proprietary software for submitting an addon for it, don't you think?

Make the internet a better place Mozilla, get rid of the infamous reCaptcha!

Thanks for reading.
