### ISSUE TITLE
[Bug]: dev deploys don't seem to be working

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14964] opened 2024-08-14 08:39 UTC
### What happened?

I tried testing :
https://github.com/mozilla/addons/issues/14937
https://github.com/mozilla/addons/issues/14921
https://github.com/mozilla/addons/issues/14953

### What did you expect to happen?

I've noticed all being reproducible.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-984)

**Comment by eviljeff** [comment] 2024-08-14 08:41
https://github.com/mozilla/addons-server/commit/a80e4c63500bb1849630164b21d5d8f941e4ef6d is the last addons-server commit deployed to addons-dev. That commit may be the cause of the addons-dev breakage (the image registry changes blocked any further deploys), or https://github.com/mozilla-sre-deploy/deploy-amo/pull/15 - which landed a similar time - may instead have broken something)

**Closed** 2024-08-14 09:31 UTC
Labels: needs:info
