### ISSUE TITLE
Add-on rating - wrong number of reviews

### ISSUE THREAD

**Issue by mentallurg** [mozilla/addons#639] opened 2018-02-11 20:20 UTC
### The problem
FireFox add-on details page displays the number of reviews that is bigger that the actual number of reviews.

### Steps to reproduce
- In FireFox open Add-ons Manager
- Klick on "Extentions"
- In the field top right enter "KeePassHelper" and start search
- Result will return an entry for "KeePassHelper". In this entry, click on "More".
- As a result information about this add-on will be displayed.
- Scroll to the bottom of this description. There is field "Rating".
- This field displays the number of reviews 21.

### What happened?
Add-on details page displays the number of reviews 21.

### What did you expect to happen?
**Expected result:** The number of reviews should be 18.

Why 18 reviews, not 21? Here is why. Look at the add-on review page:
https://addons.mozilla.org/en-US/firefox/addon/keepasshelper/reviews/?src=api
There are 17 reviews.
One could argue that add-on details page is not up-to-date. But in such case this number would be smaller, say 16 instead of 17 would be acceptable. But it displays 21, where as there are only 17 reviews.

### Anything else we should know?
Add-on review page:
https://addons.mozilla.org/en-US/firefox/addon/keepasshelper/reviews/?src=api
I have reported another bug about rating, #638. May be they are related to each other.

**Comment by rctgamer3** [comment] 2018-02-11 21:39
This is likely the intended behaviour. There are 16 written reviews, and 4 ratings, making a total of 20 reviews.

**Comment by eviljeff** [comment] 2018-02-14 06:59
This is essentially a dupe of mozilla/addons-server#7557

**Closed by eviljeff** 2018-02-14 06:59 UTC
