### ISSUE TITLE
Leech Block removed from Android Firefox Add-ons.

### ISSUE THREAD

**Issue by Mojotechnical** [mozilla/addons#1545] opened 2023-12-04 19:25 UTC
Leach block no longer exists on Android firefox. This is not a developer issue. I directly contacted the developer. He said that Mozilla removed it and won't communicate with him. Please advise next steps that I as a user or the developer can take. This is not for the desktop platform. This is for android Firefox.

**Comment by willdurand** [comment] 2023-12-04 19:35
Duplicate of https://github.com/mozilla/addons/issues/1543

**Closed by willdurand** 2023-12-04 19:35 UTC
