### ISSUE TITLE
Version history source viewing link is 403 Forbidden

### ISSUE THREAD

**Issue by GreenReaper** [mozilla/addons#404] opened 2017-05-21 09:54 UTC
### Describe the problem and steps to reproduce it:

From a Google search, I visited the [U2F Support Add-on](https://addons.mozilla.org/en-GB/firefox/addon/u2f-support-add-on/) page and clicked the header for version 1.0.1, leading me to the [Version History page](https://addons.mozilla.org/en-GB/firefox/addon/u2f-support-add-on/versions/?page=1#version-1.0.1).

Beneath each version is a link to "View the source" for the specific revision, such as:
https://addons.mozilla.org/en-GB/firefox/files/browse/557965/

### What happened?

I received a 403 Forbidden page, stating:
```
**Oops! Not allowed.**

You tried to do something that you weren't allowed to.
```

### What did you expect to happen?

I expected to be able to download the source for the selected version of the add-on.

### Anything else we should know?

I started out not logged in to the Addons site. Logging in did not appear to help.

**Comment by jvillalobos** [comment] 2017-05-22 17:29
Closing as a dupe of https://github.com/mozilla/addons-server/issues/5135. See also https://github.com/mozilla/addons-server/issues/5431, which should land this week.

**Closed by jvillalobos** 2017-05-22 17:29 UTC
