### ISSUE TITLE
[Bug]: when new base filters are generated when nr of changes go over threshold, old stashed are still displayed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15222] opened 2024-12-04 14:57 UTC
### What happened?

May be expected, I'd just like a confirmation. 
Str: 
1. Config set to 2
2. Forced base
3. Made 2 changes : 2 blocks
4. Generated mlbf
5. I got a hard stash
6. Made a new block
7. Generated mlbf
8. Checked remote settings: a new hard filter is created (as expected) 

### What did you expect to happen?

+ The previous blocks (stash from 5) are present - should it have been deleted? 

[stash with 2 guidsrecords.json](https://github.com/user-attachments/files/18010000/stash.with.2.guidsrecords.json)

![stash](https://github.com/user-attachments/assets/cf97f15b-951f-4342-b04c-f304a8462ddf)

Same thing happens if I try the scenario with restrictions

[after step 4records.json](https://github.com/user-attachments/files/18010072/after.step.4records.json)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1289)

**Comment by KevinMind** [comment] 2024-12-04 15:32
Dupe of https://github.com/mozilla/addons/issues/15217

**Closed by KevinMind** 2024-12-04 15:32 UTC
Labels: needs:info
