### ISSUE TITLE
[Bug]: Report and Appeal Escalation don't seem to be working with reviewer actions - approve, deny, force disable

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14906] opened 2024-07-09 12:15 UTC
### What happened?

STR:
1. Sent a report for an extension or theme
2. Resolved the report from Cinder, decision is to take content down
3. The author is sending an appeal (meanwhile new reports are sent)
4. The appeal is forwarded to AMO (the appeal and new reports are present under the appeal)
5. Appeal escalation is resolved with Deny appeal (I also tried to force-enable)

### What did you expect to happen?

Flag for human review is still present, Add-on History shows the Appeal as being denied but the extension is still displayed in the manual review queue and the report is still available in the DSA section. 
At deny appeal , email is not sent to the author.
At force-enable, content is being enabled but email is not sent to the author.

Examples: 
extension with the appeal escalated and multiple new reports sent https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/631773#review-actions
theme with the appeal escalated and multiple new reports sent https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631774
an extension, doesn't have new reports attached  https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631775

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-912)

**Comment by ioanarusiczki** [comment] 2024-07-09 12:53
I've tried the following too:
1. a report is escalated to AMO (extension or theme)
2. reviewer tries to Force-disable

Results:
emails not sent to reporter/author and the report is still present in the dsa section. 
Flag for human review is removed in these cases. 

Examples: 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/631777#review-actions
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631779

**Comment by eviljeff** [comment] 2024-07-30 14:04
I've just tried to reproduce and was able to.  Cinder is raising a 500 error, so the job isn't being resolved with a decision.

**Comment by eviljeff** [comment] 2024-07-30 16:02
For reference, [AMO sentry traceback](https://mozilla.sentry.io/issues/5348822972/events/latest/?project=6224627&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=latest-event&stream_index=0), and [Cinder GCP log](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-07-30T12:37:42.441861915Z;endTime=2024-07-30T12:39:00.000Z;query=d5379908-85a8-4895-a9eb-69f95442a8d1%0Atimestamp%3D%222024-07-30T12:37:42.441861915Z%22%0AinsertId%3D%22n7s320ydewy8meos%22;startTime=2024-07-30T11:35:00.000Z;storageScope=storage,projects%2Fmoz-fx-cinder-nonprod%2Flocations%2Fglobal%2Fbuckets%2F_Default%2Fviews%2F_AllLogs,projects%2Fmoz-fx-cinder-nonprod%2Flocations%2Fglobal%2Fbuckets%2F_Default%2Fviews%2F_Default,projects%2Fmoz-fx-cinder-nonprod%2Flocations%2Fglobal%2Fbuckets%2F_Required%2Fviews%2F_AllLogs,projects%2Fmoz-fx-cinder-nonprod%2Flocations%2Fglobal%2Fbuckets%2Fgke-cinder-dev-log-bucket%2Fviews%2F_AllLogs,projects%2Fmoz-fx-cinder-nonprod%2Flocations%2Fglobal%2Fbuckets%2Fgke-cinder-stage-log-bucket%2Fviews%2F_AllLogs?project=moz-fx-cinder-nonprod)

**Comment by eviljeff** [comment] 2024-07-31 16:26
Note: I contacted the Cinder developers and am awaiting a reply on their initial investigations

**Comment by eviljeff** [comment] 2024-08-02 15:15
status update here: 
- I have a fix (mozilla/addons-server#22532) that works around the bug, by making the decision on the add-on, rather than the job. Which is what we were doing previously, so isn't terrible, but isn't ideal as the job is left without the correct decision, and then the actual decision is unconnected to the reports and/or appeal.
- The Cinder developers have now confirmed the suspicions of the cause, but a "fix" from their side isn't on the short term horizon, because what we're doing (resolving with one decision, then trying to override it) isn't seen as standard behaviour.  
- Medium-term we should rework how cinder->AMO escalations work, using a new webhook that wasn't present during original planning/implementation in 2023.

**Closed** 2024-08-06 12:58 UTC
Labels: needs:info, component:abuse_reports

**Comment by ioanarusiczki** [comment] 2024-08-12 13:55
I tested again the scenarios above and worked for me.
