### ISSUE TITLE
New additions to Featured Themes Collection not showing up 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons#742] opened 2018-06-24 15:30 UTC
Pam and Candelora have reported that since the last AMO push, they have not seen new additions to the featured themes collection show up on the site. 

I see the new changes additions from the Edit Collection view: 

![screen shot 2018-06-24 at 8 24 21 am](https://user-images.githubusercontent.com/23342476/41820570-922a7df4-7788-11e8-8982-3f05cab5e93d.png)

But everything added after lite_fox isn't showing up on AMO: 

![screen shot 2018-06-24 at 8 25 16 am](https://user-images.githubusercontent.com/23342476/41820565-7adb7658-7788-11e8-9752-242dc70f59e0.png)

Not sure if this is a frontend issue or a server issue. 

cc @devaneymoz

**Comment by bobsilverberg** [comment] 2018-06-25 17:47
The "Featured Themes" shelf does not use a collection as its source, but rather a query which selects themes with the `featured` flag. So this is expected, as far as the front end is concerned.

Is there supposed to be some magic in the back end that automatically sets the `featured` flag for themes after they are added to the collection mentioned above (which is no longer working)? Does the logic for the home page need to be changed to use this collection rather than a query?

**Comment by devaneymoz** [comment] 2018-06-25 17:55
Like other shelves that point to collections (typically for extensions content), could we do the same for Featured Themes? If so, when the "Featured Themes"  collection is programmed for the homepage, I could note the collection URL and the system pulls a randomized sampling from the collection into homepage view?

**Comment by bobsilverberg** [comment] 2018-06-25 17:57
Yes, we can do that. Do you want to wait for the next home page content update for that? If not we can just re-purpose this issue to be about changing that immediately.

**Comment by bobsilverberg** [comment] 2018-06-25 18:03
Actually, if you want that change made separately, then an issue should be opened at https://github.com/mozilla/addons-frontend/issues/new.

**Comment by devaneymoz** [comment] 2018-06-25 18:11
@bobsilverberg which path do you prefer? Because we'll likely leave that Featured Themes shelf in place during the next update, so if change made soon it would be relevant for next programming update.

**Comment by jvillalobos** [comment] 2018-06-25 19:37
Since this appears to be a regression due to a recent change, this should be fixed as soon as possible. Don't know if it's easier to restore the previous logic or just change the shelf to point to the collection. The latter I think is preferable, since it's what we do elsewhere and doesn't require a special flag.

**Comment by bobsilverberg** [comment] 2018-06-25 19:50
It's not a recent regression. The last time we had a "featured themes" shelf was for the April 5th update, and at that time it was using a query and not a collection. I'm not sure how long ago it was (if ever) that a "featured themes" shelf used the collection. I wonder if it's possible that there *was* some "magic" in the back end (as I mentioned above) which is now broken? @diox Can you comment on that?

**Comment by willdurand** [comment] 2018-06-25 19:57
I guess we always relied on the search: https://github.com/mozilla/addons-frontend/commit/53ed79afe0cb729a138308126c7b498e4a9371e5#diff-df1731d497fd6ce2503968e52e9dca2e

**Comment by bobsilverberg** [comment] 2018-06-25 20:49
So that begs the question of why this was expected to work, which is why I was thinking there may have been some magic at play.

**Comment by diox** [comment] 2018-06-26 10:43
There is some magic at play indeed :)

Add-on "featured" state depends on its presence in special featured collections for a given type/locale/app combination. We cache the list for every combination on access, as the query to determine that is nasty. When a featured collection is changed, that cache is invalidated.

When an add-on is indexed, we record its featured state in every locale/app combination in elasticsearch, allowing you to search for featured add-ons for a given locale/app later and find them.

I'd very much like for the frontend to continue using the search endpoint for this, it's likely going to be the most efficient way. I'm not sure what's preventing this to work, but we have a couple suspects as changes to caching and changes to collections went in that tag last week.

**Comment by bobsilverberg** [comment] 2018-06-26 11:09
Thanks for the info @diox, it does sound like some sort of back end regression then, and that we shouldn't change the logic on the front end to deal with this.

**Closed** 2018-06-26 12:35 UTC
Labels: priority: p2, type: regression

**Comment by bobsilverberg** [comment] 2018-06-26 16:44
Thanks @diox!

**Comment by AlexandraMoga** [comment] 2018-06-27 09:15
I've edited the featured persona collections and new theme addtiones are listed in the following pages on the new frontend:
https://addons.allizom.org/en-US/firefox/collections/mozilla/featured-personas/?page=1
https://addons.allizom.org/en-US/firefox/search/?featured=true&page=1&type=persona


![featured personas](https://user-images.githubusercontent.com/31961530/41964748-867968d0-7a03-11e8-8b8e-5592f36e9fae.gif)

Themes removed from the collections will be removed from 
https://addons.allizom.org/en-US/firefox/collections/mozilla/featured-personas/?page=1
_but are not removed from_ 
https://addons.allizom.org/en-US/firefox/search/?featured=true&page=1&type=persona

@diox, do you think that the last part is a separate issue?

**Comment by AlexandraMoga** [comment] 2018-06-27 13:57
Logged https://github.com/mozilla/addons-server/issues/8673 for the last issue.

Marking this issue as verified fixed on -dev and stage with FF60, WIn10x64
