### ISSUE TITLE
Add-on review page shows empty reviews

### ISSUE THREAD

**Issue by HattinGokbori87** [mozilla/addons#1111] opened 2019-10-06 10:50 UTC
Please consider not showing empty reviews (only ratings) for add-ons. They make real reviews hard to find and makes the review page less useful.
Example:- https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/reviews/

**Comment by jvillalobos** [comment] 2019-10-07 16:46
Looking at https://github.com/mozilla/addons-server/issues/4966, this should already be the case, so maybe something change since then. @eviljeff, do you know?

**Comment by eviljeff** [comment] 2019-10-07 17:06
@jvillalobos this issue is about frontend, and that addons-server issue is ancient, so I don't know.  (I tried a quick search on the frontend repo but there's a_lot_ of issues about ratings so couldn't see when it changed)

**Comment by muffinresearch** [comment] 2019-10-07 17:26
Looks like this is by design? https://github.com/mozilla/addons-frontend/issues/7200 see also https://github.com/mozilla/addons-frontend/issues/7411

**Comment by eviljeff** [comment] 2019-10-07 17:42
@jvillalobos You might want to look at https://github.com/mozilla/addons-server/issues/7540#issuecomment-534927064 too depending on the outcome of this issue.  It's not very clear what we want.

**Comment by bobsilverberg** [comment] 2019-10-07 18:17
> Looks like this is by design? [mozilla/addons-frontend#7200](https://github.com/mozilla/addons-frontend/issues/7200) see also [mozilla/addons-frontend#7411](https://github.com/mozilla/addons-frontend/issues/7411)

Yes, I remember implementing this. Is is by design.

**Comment by jvillalobos** [comment] 2019-10-07 20:47
Summarizing what I just read: we originally wanted the front-end to only show written reviews and the counts would reflect that; it got confusing because of the counts so the decision was reversed and now we show everything. We _want_ to eventually change the way reviews/ratings are sorted, but there are no plans for that right now.

So, to avoid causing more unnecessary work I'm going to close this as wontfix, because we want to keep empty ratings for now. I suppose mozilla/addons-server#7540 should also be dropped because - as I understood - it would re-introduce the old mismatch.

**Closed by jvillalobos** 2019-10-07 20:47 UTC
Labels: component: ratings and reviews

**Comment by HattinGokbori87** [comment] 2020-01-21 05:18
In EVERY modern app store only the written reviews of an app are shown to users and the rating is the arithmetic mean of all ratings (review+rating & just rating). Anyone who used one of those store (like Google Play, Apple's AppStore etc) shouldn't be confused. Thanks for the reply though.
