### ISSUE TITLE
[Bug]: Since 2 days a web site doesn't work properly when activating Adblock ultimate

### ISSUE THREAD

**Issue by philmont68** [mozilla/addons#14795] opened 2024-05-19 15:03 UTC
### What happened?

On one (and only one) of my favourite website (https://www.eurosport.fr/), where I spend more than one hour per day, always with Adblock Ultimate-Firefox on Linux-Mint, since 2 days it shows a gray banner on half of the page, and when I scroll down, the banner remains, only the lower half of the page displays content.
So I deactivated my extensions, one by one, and found that Adblock ultimate was generating the bug.
I contacted the support of the website but their reply was stereotyped, they made no effort.
I tried another adblock, Ghostery and the problem is similar.
Then I installed Adblock ultimate on Chromium and it works normally.
![ScreenshotPbmEurosport](https://github.com/mozilla/addons/assets/170251554/03785bed-26d4-453c-8cf6-6e21daa6d911)
Thanks to have a look.

### What did you expect to happen?

nothing to add

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-772)

**Comment by diox** [comment] 2024-05-19 19:26
Hi,

Sorry but this bugtracker is to report issues against addons.mozilla.org, not add-ons themselves. There is not much we can do about individual add-ons as we don't control them.

I suspect you're reproducing these issues with 2 different adblockers simply because they are sharing the same rules, which they download periodically from the same lists. One of these rules is likely broken and needs to be adapted to recent changes on that website. A few suggestions of things you can do:
- Find the rule responsible for your problem and deactivate it, and/or report the problem to the authors of the list.
- Deactivate your adblocker on this site, temporarily or permanently. I'm not familiar with the ones you tried, but I know it's easy to do using [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/).
- If your adblocker has an option to deactivate "cosmetic" rules, this might be the culprit and you could try deactivate them. On my machine with uBlock Origin this seems to fix the issue (see screenshot for where the option is in uBlock Origin - this menu is reachable from the toolbar icon)
![disable_cosmetic_filters](https://github.com/mozilla/addons/assets/187006/5aeaf4cc-c954-48bb-a312-4df80e29e35b)

Since we can't fix this problem ourselves, I'm closing this issue.

**Closed by diox** 2024-05-19 19:26 UTC
Labels: needs:info, type:bug
