### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by KlaasdeV** [mozilla/addons#914] opened 2019-02-16 10:39 UTC
It occurred during the submission of a new add-on.
[Timesearch.zip](https://github.com/mozilla/addons/files/2871817/Timesearch.zip)

Submitted at:
https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

When I tested it with Firefox and Chrome, the extension worked well.

If I try to upload an example extension of Firefox (f.e. Borderify), I get 
"Your add-on failed validation with 1 error." at the general tests, too.

**Comment by wagnerand** [comment] 2019-02-16 13:18
Duplicate of #896

The problem is, your add-on is packaged wrong. You don't have the `manifest.json` on the root of the folder, instead, there's a subfolder containing all the data.

[developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension)_

**Closed by wagnerand** 2019-02-16 13:18 UTC

**Comment by KlaasdeV** [comment] 2019-02-16 14:54
Thank's a lot! Didn't know that was possible...
Extension has been uploaded.

**Comment by KlaasdeV** [comment] 2019-02-16 14:55
Thank's a lot! ;-)
Didn't know that was possible...
Extension has been uploaded.
