### ISSUE TITLE
Signing unlisted addon fails with 500 error

### ISSUE THREAD

**Issue by ripdog** [mozilla/addons#449] opened 2017-07-25 11:13 UTC
### Describe the problem and steps to reproduce it:

1. Visit: https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted
2. Upload an addon.
3. Click "Sign Addon" after automated validation
4. Get internal server error.

Alternatively:

Using Chrome Store Foxified to automatically upload addons from the chrome store to AMO to get it signed, shows this:

>Signing failed, contacting server failed. Status: 500 Status Text: INTERNAL SERVER ERROR URL: https://addons.mozilla.org/api/v3/addons/hdokiejnpimakedhajhdlcegeplioahd%40chrome-store-foxified-4238113118/versions/4.1.60.112/

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I can't retry submitting my addon because it says "Duplicate add-on ID found". The addon was not signed when I last submitted it due to this error, and is not listed in my account anywhere. I guess it's stuck in a cache of some sort somewhere. If someone could clear out the cache for my account (ripdog), that'd be great. Thanks.

**Comment by wagnerand** [comment] 2017-07-25 11:24
Does it work if you submit the add-on file manually using the website?

**Comment by EnTeQuAk** [comment] 2017-07-25 11:42
I think this is another clean_slug runtime error problem 'caused by foxified https://sentry.prod.mozaws.net/operations/olympia-prod/issues/371002/

The problem here is that foxified re-uses the same slug over and over again, we increment a number but only up to 100 entries, once this is reached (meaning that we have 100 duplicates already) we raise an error.

**Comment by muffinresearch** [comment] 2018-02-01 15:03
Closing this since there's been no new activity for a while.  Please re-open if you think this should be looked at again.

**Closed by muffinresearch** 2018-02-01 15:03 UTC
Labels: triaged
