### ISSUE TITLE
(webext) validation hanging when the xpi doesn't contain manifest

### ISSUE THREAD

**Issue by gtdinbox** [mozilla/addons#252] opened 2016-10-15 11:11 UTC
### Describe the problem and steps to reproduce it:

1. Visit https://addons.mozilla.org/en-GB/developers/addon/activeinbox-gmail-gtd/versions#version-upload
2. Upload the attached XPI (note because of GitHub limitations, I simply renamed the .xpi to .zip. You can rename it back). 

### What happened?

1. It uploads fine. 
2. Then greys out buttons, and changes title to "Validating ActiveInbox.6.0.31.xpi"
3. It then remains in this state forever (I've left it for several hours; tried it in different locations; across the last week).

### What did you expect to happen?

Validation to complete, warnings to be shown, and the 'Add Version' to become available. 

### Anything else we should know?

I recently switched ActiveInbox to the Web Extensions architecture. 
It also shares a manifest.json file with the Chrome plugin, as they're packaged together for convenience (afaik both browsers look for that named file - they can't be split. But that works fine for loading it directly in Firefox via about:debugging. I don't believe there's anything inherently wrong with the manifest.json).

[ActiveInbox.6.0.31.zip](https://github.com/mozilla/addons/files/531094/ActiveInbox.6.0.31.zip)

**Comment by eviljeff** [comment] 2016-10-17 17:48
I don't see a manifest file in that .zip

**Comment by gtdinbox** [comment] 2016-10-17 22:22
@eviljeff You're absolutely correct, we're totally responsible for this. I'm eating very humble pie. (We re-architected everything around Web Extensions, and fell at the last hurdle of actually updating our build script to include the right files). 

It's a small point but the Validator probably should chastise anyone stupid enough not to include the manifest.json file.

**Comment by eviljeff** [comment] 2016-10-18 11:01
yeah, the validator should certainly report the error rather than never returning.

**Comment by EnTeQuAk** [comment] 2016-10-18 11:14
imho we do raise a proper exception if a manifest.json file is missing and the user should get a proper error. But maybe something else was itchy and thus preventing it? At least it should never hang because of that, I believe that https://github.com/mozilla/addons-server/issues/3778 is related to it since it's causing tasks to fail and thus never to return.

**Comment by muffinresearch** [comment] 2016-10-18 12:19
FWIW: Trying this locally, after removing content to avoid file size limitation that results in a 413. The first time I did see an error on the form which I think is this one [1].

However the second time running the same file I don't see the error and I see the validation appear to hang as per the OP's reported issue.

[1] https://github.com/mozilla/addons-server/blob/67af4276dc2f3d11ce1220bbbd2a89ed56ce9980/src/olympia/files/utils.py#L121

**Comment by muffinresearch** [comment] 2016-10-25 12:51
Marking this as a dupe of #230 since it's essentially the same bug.

**Closed by muffinresearch** 2016-10-25 12:51 UTC
