### ISSUE TITLE
New (beta) Statistic page does not show Active Daily Users

### ISSUE THREAD

**Issue by GAM3RG33K** [mozilla/addons#1216] opened 2020-07-03 14:32 UTC
### Describe the problem and steps to reproduce it:
I was visiting my Addon statistics page to check daily user data. 
I saw a link for the beta statistic page. When I visited I saw that the Daily user data is not available at all.

When I saw data for 90 days it shows some users but not after `1st June`.

Also, it seems that daily user avg is also not changing even though the graph clearly shows a rise in daily users.
But I am more concerned about the bug in the beta page.

### What happened?
I have `226` daily users according to the current statistic page but there are `0` Daily users shown in beta page.

### What did you expect to happen?
I expect the beta to show same information as the current page.

### Anything else we should know?
Current Page Screenshot [30 days]:
![image](https://user-images.githubusercontent.com/11572011/86477816-db31a880-bd66-11ea-9932-b5e783efbbb5.png)

New Page [30 days]:
![image](https://user-images.githubusercontent.com/11572011/86477962-13d18200-bd67-11ea-8b7e-e68d4a60f710.png)

Current Page Screenshot [90 days]:
![image](https://user-images.githubusercontent.com/11572011/86478135-6ad75700-bd67-11ea-8cdd-97c8b9227fdb.png)

New Page [90 days]:
![image](https://user-images.githubusercontent.com/11572011/86478102-5e52fe80-bd67-11ea-93c3-0a6a2ac60ebc.png)

**Comment by willdurand** [comment] 2020-07-03 14:44
Thanks for opening this issue. We're aware of this "bug", which was caused by a data update last night. This should be resolved on Monday (today, Friday, being a US public holiday).

**Comment by willdurand** [comment] 2020-07-06 15:23
This should be fixed now.

**Closed by willdurand** 2020-07-06 15:23 UTC
