### ISSUE TITLE
Static themes are using deprecated properties

### ISSUE THREAD

**Issue by mconca** [mozilla/addons#966] opened 2019-03-29 15:46 UTC
On December 3, 2018, we announced that Firefox would deprecate theme properties that had aliases to other properties. See https://bugzilla.mozilla.org/show_bug.cgi?id=1508425 and https://bugzilla.mozilla.org/show_bug.cgi?id=1472740.

Unfortunately, it looks like all LWT themes were converted to static themes using the deprecated theme properties.

The deprecated properties will be removed from Firefox in release 69. In order to avoid breakage, we probably need to convert all themes using the deprecated properties to the supported properties.

**Comment by muffinresearch** [comment] 2019-03-29 15:51
Dupe of https://github.com/mozilla/addons-server/issues/10627

**Closed by muffinresearch** 2019-03-29 15:51 UTC
