### ISSUE TITLE
Permissions descriptions on AMO are not descriptive enough to allow trust in addons

### ISSUE THREAD

**Issue by mcomella** [mozilla/addons#498] opened 2017-09-29 17:29 UTC
I'm looking for an add-on to blacklist websites I specify in order to avoid distractions. I used to use [Leechblock](http://www.proginosko.com/leechblock/) but I need to change due to WebExtensions.

**I'm trying to find an add-on that requires the minimum permissions in order to get the job done**. It needs to match against a URL so that permission could be, "Can see the metadata of the sites you visit: urls, titles, etc." It also needs to redirect me with a permission like, "Allows navigating to new pages in the browser."

I found one extension that kind of does the right thing, [Monastery](https://addons.mozilla.org/en-US/firefox/addon/monastery/?src=ss), and here are the permissions:
1. Access your data for all websites
1. Display notifications to you
1. Access browser tabs

**I feel these permissions fall short in that they are not specific as to what can be read and what can be modified.** For example, I assume this extension will redirect me when visiting sites on my blocklist once my time expires – which of these permissions clearly indicates the ability to do that? In particular...

For 1):
* What is "your data"? Is that the current content and state of the page? Can they modify it? Is it my browsing history? My bookmarked state?
* What are "all websites"? Are those websites I visit with the extension installed or can they access my history? Can they make arbitrary requests?

For 3):
* What does it mean to "access browser tabs"? Can they read the state of all open tabs? Can they read the content? Can they modify the content? Modify the existing tabs? Create new tabs?
* How does "Access browser tabs" differ from "Access your data from all websites"? In more lenient interpretations, there is a large overlap

**These permissions are not helpful because it sounds like the add-on can do anything it wants to. Therefore, I can't really trust this add-on** and I've found most have had similarly unhelpful descriptions so I'm forced to rely on trusting the brand or vetting the source code. Even then, these permissions are so broad that a hypothetical add-on with the "Access your data for all websites" permission, which formerly was used to retrieve URLs for blocking, could get an automatic update and start sending all my tab metadata to a remote server.

**Comment by mcomella** [comment] 2017-09-29 17:53
Another example: I vetted the source for [Simple Blocker](https://addons.mozilla.org/en-US/firefox/addon/simple-regex-blocker/?src=search) which can "Access your data for all websites". [The permissions they specify are](https://github.com/eryw/firefox-simple-blocker/blob/master/manifest.json):
* "webRequest",
* "webRequestBlocking",
* "storage",
* "<all_urls>"

"All data", in this case, is all urls/headers, but not the content of the page, which is unclear. Also, storage is not mentioned in the permissions (I take it that's a given?). The permissions feel really misleading.

**Comment by devaneymoz** [comment] 2017-09-29 18:26
@mcomella This is good feedback, thanks. 

You are right that especially in the case of "Access your data for all websites" that sounds pretty scary. The current messaging is the result of implementing uniform copy standards to account for the limited space of a pop-up (thus short bullet point blurbs). In some cases there are quite a lot of permissions involved with a single extensions so we strove to keep the messaging lean. However in some cases, like the ones you detailed, the practical impact is imperfect. 

We're looking at ways to address this.

**Comment by eviljeff** [comment] 2017-09-29 18:58
It might be worth checking with the Firefox developers about the scope of `<all_urls>` - afaik it _is_ as broad as it sounds.  Better copy may be solution, but it may actually be accurate as is.  (Changing/replacing the permission has cross-browser compatibility implications so it's probably not practical)

**Comment by yfdyh000** [comment] 2017-09-29 19:07
I agree this feedback and think this is not enough transparency to users. And, there is no ways to filter permissions for add-ons, https://github.com/mozilla/addons-server/issues/6048.

In addition, I don't understand why the "Display notifications to you" is necessary, except for browser compatibility. It usually does not cause trouble to the user, in my opinion.
These permissions description are lacking in priority and not comprehensive, such as I am more concerned with browsing history and make web requests to where (it seems implied).

**Comment by eviljeff** [comment] 2017-11-09 17:19
> I just installed an addon with these permissions and incorrectly assumed it was the legacy version because no permissions were listed.

That assumption was incorrect.  Legacy add-ons display a specific warning because they can do anything by design.

>contextMenus is also not mentioned.

AMO displays the same permissions as Firefox - and the same text pretty much (the text for `<all_urls>` is AMO specific but the more general permissions are pulled weekly from the Mozilla source code).  If you think contextMenus needs to be mentioned (and I'm not sure it does, tbh) then it's something to take up with the Firefox developers on (maybe a bug in this [Product](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit), by not 100% sure)

**Comment by chocolateboy** [comment] 2017-11-09 17:27
> Legacy add-ons display a specific warning because they can do anything by design.

They used to. I don't see one on the new site e.g. Classic Theme Restorer installs without any such warning.

**Comment by eviljeff** [comment] 2017-11-09 17:29
https://github.com/mozilla/addons-frontend/issues/2757 for adding the permissions stuff to the new front-end.

**Comment by bzm3r** [comment] 2018-04-20 02:10
It's also pretty scary that Mozilla's new [facebook containment extension](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) also requires "Access your data for all websites". As a user, I can't figure out if I am making a choice between giving data to facebook, or Mozilla.

**Comment by vertigo220** [comment] 2018-04-26 02:10
I see this as another example of Firefox becoming more like Google/Chrome. One of my biggest issues with Android is how poorly permissions are handled, and Chrome, in my limited experience with it, doesn't seem to be any better. It's a shame to see Mozilla being similarly irresponsible. Things Firefox needs to provide meaningful protection and usability with regards to permissions are:

- Permissions (or rather, if I'm understanding this thread correctly, what's actually being requested) need to be more granular
- about:permissions needs to be added back, or something with similar functionality needs to be added
- When viewing the details page for installed addons (in the local add-ons page, not AMO), the permissions that addon has should be listed
- As @yfdyh000 mentioned, the ability to filter addons by their required permissions would be very helpful, as would the ability to sort by them
- A better description of the permissions (e.g. with the "Access your data for all websites" permission, it's unclear if that means _everything_, such as passwords (and for that, is there a difference if having them entered automatically by a password manager?), all the text and images (contents of email, for example), etc. It seems this is the case, but it could be more clear.

> Legacy add-ons display a specific warning because they can do anything by design.

I know Legacy addons had significantly more access, but they're still limited by their permissions, right? Your statement makes it sound like they can do anything regardless of that.


As a side note, the editor doesn't seem to be working right for me, even if I disable uMatrix and uBo. The lists only generate a dash/number/etc for the first item, and hitting enter doesn't create a new one for the next item. Any ideas?

**Comment by jvillalobos** [comment] 2018-04-26 08:16
> I know Legacy addons had significantly more access, but they're still limited by their permissions, right? Your statement makes it sound like they can do anything regardless of that.

Legacy add-ons have no concept of permissions. They can do anything.

**Comment by jvillalobos** [comment] 2018-04-26 14:38
There's further discussion about this in https://github.com/mozilla/addons-frontend/issues/2757

In short, we need to maintain consistency with Firefox, (some) compatibility with other browsers, and set expectations for users as clearly as possible. "Access your data for all websites" is certainly a problem, and we've talked about it at length. Unfortunately there's no straightforward solution for it after considering API complexities and how to communicate them to our users.

There isn't anything concrete to do here, so I'm closing this issue.

**Closed by jvillalobos** 2018-04-26 14:38 UTC
Labels: component: ux, needs: editorial, needs: ux, priority: p4, triaged

**Comment by jvillalobos** [comment] 2018-04-26 14:39
Forgot to mention filtering or sorting by permissions. That would be a fairly complex AMO feature, and probably not useful for most users. I don't expect that to be added in the future.
