### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by dannyfreire76** [mozilla/addons#917] opened 2019-02-19 03:41 UTC
Please attach a copy of your add-on, and fill in the following information:

* New Add-in

* ? - Didn't get far enough to choose listed or unlisted

* https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

* 10:40 PM EST

Thanks in advance.

[njpwext.zip](https://github.com/mozilla/addons/files/2878133/njpwext.zip)

**Comment by EnTeQuAk** [comment] 2019-02-19 06:48
Duplicate of #896

The problem is, your add-on is packaged wrong. You don't have the `manifest.json` on the root of the folder, instead, there's a subfolder containing all the data.

[developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension)_

**Closed by EnTeQuAk** 2019-02-19 06:48 UTC
