### ISSUE TITLE
new addon submission page is broken

### ISSUE THREAD

**Issue by moribellamy** [mozilla/addons#1085] opened 2019-08-13 21:49 UTC
To repro: Try submitting a new addon on addons.mozilla.com, e.g. https://addons.mozilla.org/en-US/developers/addons.

expected: after successful completion of the form, some kind of success or error message

actual: https://www.youtube.com/watch?v=cB5y9asyTcA

**Comment by diox** [comment] 2019-08-13 22:03
Can you upload the zip/xpi of the add-on somewhere? I suspect this might be caused by something in it.

**Comment by diox** [comment] 2019-08-13 22:08
Actually, looking at the video more closely: when you select "Other" as the license, it should prompt you to add the name and text of the license. I don't see that in your video, maybe there is a JavaScript error preventing that from happening, maybe there is a bug in the logic somewhere, but that's probably the cause of the issue in any case.

Try changing license to something else and back to "Other" and see if you get the text & name fields.

**Comment by moribellamy** [comment] 2019-08-13 22:11
https://drive.google.com/file/d/1rxOoyq9a-eAXHbs5ziOtA9oSOmqn_UxR/view?usp=sharing

i tried submitting as an MIT license instead, same error.

source code if it helps: https://github.com/moribellamy/graytabby

**Comment by diox** [comment] 2019-08-13 22:14
Is that the actual zip you submitted? It has a `dist` top level directory where all the files reside, which would make it invalid (manifest needs to be at the root, not inside a directory)

**Comment by moribellamy** [comment] 2019-08-13 22:16
i will check but that would surprise me. At this stage in the flow, I've already uploaded my zip and passed verification. In fact, I failed verification because of a non-square icon. Then i fixed the icon and got verified. So that experience would compel me to believe that the zip file i submitted was well formed.

**Comment by diox** [comment] 2019-08-13 22:30
No idea what's going on yet - tried several things I suspected could go wrong, but haven't found anything so far. I did manage to grab the zip and the one you uploaded did *not* have the top-level directory, so it must have been generated differently.

**Comment by diox** [comment] 2019-08-13 23:24
Spent way too much time investigating this and got nowhere yet.

- Nothing in sentry - and we don't see a 500 anyway
- It works on stage (and dev, but it uses a different form because the content-optimization switch is on) with the same add-on - but obviously database wasn't necessarily in the same state
- Every form is shown correctly - the add-on is, in this state, missing a license, summary and category info, all relevant forms are shown.
- POST Data submitted appears correct as well (and it's a POST)
- We return a 200 as if one of the forms is invalid and there is an error to show
- No `.error` or `.errorlist` elements anywhere in the page, even hidden
- No JavaScript errors
- Looking at the template all forms that should display errors do display them when there is any
- More specifically:
  - The default locale is en-US, it matches the inputs & data sent when submitting
  - Summary is present. If I don't include it, it says it's required as normal.
  - There is only one applications versions attached, so only one category form, everything ok. Changing categories doesn't make a difference.
  - Selecting Custom or non custom-license doesn't make a difference
  - Sources were provided, but I don't see how this could change anything. I tried submitting with approval notes, doesn't make a difference.
  - Even tried changing name and slug, doesn't make a difference.

**Comment by moribellamy** [comment] 2019-08-13 23:48
thanks for digging. FWIW, i may have submitted this app (same app id of "graytabby", but different app contents) as a different user name. i had mori@invoked.net as an account, but i decided to do mori.michael.bellamy@gmail.com.

other than that..i've had issues with django prod mode falling back to a different behavior for uncaught exceptions in the past. but since you're not seeing anything in sentry, that seems unlikely

**Comment by moribellamy** [comment] 2019-08-14 23:23
Is there a workaround for me? Maybe I can try a different account or something?

**Comment by moribellamy** [comment] 2019-08-16 04:00
I tried deleting the addon and re-adding it. Same issue.

**Comment by eviljeff** [comment] 2019-08-16 11:16
I tried a different idea - I submitted your xpi myself to our production server and it seems to go through.  So (once you accept being the author on it - see email) it will be your addon and you can delete the other listing + change this submission to be as you need (summary, license, slug, etc etc)

**Comment by eviljeff** [comment] 2019-08-16 11:17
I tried all the things @diox detailed too and came to the same roadblock.  There are no errors shown, but there must be a form validation error (or other type of error) to stop the submission (it's possible we're not including all errors in the template).

**Comment by moribellamy** [comment] 2019-08-16 23:07
i'm unblocked, thanks @eviljeff  @diox !!

**Comment by eviljeff** [comment] 2019-08-19 11:22
Given we couldn't work out what happened or any STR I'm going to close this issue.  If it happens again or we get some more data points we can re-open / ref it.

**Closed by eviljeff** 2019-08-19 11:22 UTC
Labels: priority: p2
