### ISSUE TITLE
Can't install a "language pack" addon for the last version of firefox dev edition  (62.0b12 (64 bits))

### ISSUE THREAD

**Issue by boscs** [mozilla/addons#764] opened 2018-07-31 09:46 UTC
I installed firefox in french but expected to install the English language pack later.
Later is now

### What happened?
The addon page says the language pack is not compatible with my version of firefox
### What did you expect to happen?
this is the last version of firefox so I thought everything would  work.
### Anything else we should know?

Click o a forein word
![screen](https://user-images.githubusercontent.com/11486258/43451908-565c54f0-94b6-11e8-946c-59ac6e805216.jpg)
-> add languages
![image](https://user-images.githubusercontent.com/11486258/43451887-4abab2b8-94b6-11e8-8ebc-228d0841260f.png)
-> English language pack
![image](https://user-images.githubusercontent.com/11486258/43452056-cddd7086-94b6-11e8-8c14-0de2039e0755.png)

😞 
Even forcing the download doesen't work :
-> copy the download link
![image](https://user-images.githubusercontent.com/11486258/43452177-189dc33c-94b7-11e8-9f92-fb74b13e8b49.png)
->browsing it
![image](https://user-images.githubusercontent.com/11486258/43452205-2b7b68f6-94b7-11e8-9ec2-bf954ca6e9fa.png)

so I'm sad now....
except that firefox is still "the best browser ever"

**Comment by diox** [comment] 2018-07-31 09:52
Hi,

This is a known problem with langpacks: they are only compatible with one specific version at a time, and AMO always displays the latest one. The workaround is to go to the all versions page, select the language pack compatible with your version and install that one.

Duplicate of https://github.com/mozilla/addons-server/issues/8180

**Closed by diox** 2018-07-31 09:52 UTC
