### ISSUE TITLE
AutoReaderView is displayed with 3 download buttons in Chrome

### ISSUE THREAD

**Issue by dholbert** [mozilla/addons#104] opened 2016-04-29 19:54 UTC
STR:
 1. In Chrome (the browser), visit https://addons.mozilla.org/en-US/firefox/addon/autoreaderview/

ACTUAL RESULTS:
Three download-Firefox buttons are displayed, stacked on top of each other. ("Only with Firefox — Get Firefox Now!")

EXPECTED RESULTS:
At most one download-Firefox button.

If I inspect with devtools, it looks like there's one for Linux, one for Mac, and one for Windows, or something like that. We're probably trying to do platform-detection and failing.

![Screenshot](https://cloud.githubusercontent.com/assets/426803/14927878/66f83f1c-0e09-11e6-9b77-2d624fb482a9.png)

**Comment by dholbert** [comment] 2016-04-29 19:55
(DISCLAIMER: I know nothing about this particular (unreviewed) add-on, and I have no idea if it's useful or safe. I simply ran across a link to it and noticed that it broke AMO in Chrome.)

**Comment by tofumatt** [comment] 2016-05-11 14:39
@ValentinaPC noted this isn't fixed, looks like there's an Android style I missed too. 😞

**Comment by ValentinaPC** [comment] 2016-05-12 10:57
@tofumatt : The issue is not fixed. If the add-on is compatible with Firefox and Android there are still 2 buttons listed using Chrome. Please see the screenshots:
![add-on_details](https://cloud.githubusercontent.com/assets/15685960/15212463/71cd59dc-1849-11e6-9199-f42a436b2264.png)
![versions](https://cloud.githubusercontent.com/assets/15685960/15212468/777374f2-1849-11e6-87e0-1341b54ac86d.png)

**Comment by tofumatt** [comment] 2016-05-12 11:05
I looked and it seems the CSS isn't quite up to date.

@jasonthomas Is there a delay in the CSS getting updated on -dev?

**Comment by tofumatt** [comment] 2016-05-12 11:52
Forget it; this was closed prematurely but the fix hasn't been merged. Bit of a mixup!

**Closed** 2016-05-12 14:52 UTC
Labels: style refresh

**Comment by ValentinaPC** [comment] 2016-05-12 15:21
Verified as fixed on AMO-dev Chrome 50.0.2661.102 m (Win 7)
Postfix screenshot: 
![multiple-platforms](https://cloud.githubusercontent.com/assets/15685960/15219959/60cc87f0-186e-11e6-8c23-85cca7e6b14c.png)
