### ISSUE TITLE
No option to filter add-ons by OS = Android

### ISSUE THREAD

**Issue by yeswap** [mozilla/addons#773] opened 2018-08-20 02:03 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.) When I browse or search for add-ons in Firefox for Android the vast majority of the add-ons shown are not available for Android. Browsing and searching needs to be filtered by current platform.
### What did you expect to happen?
Searching for add-ons should only return add-ons that can be installed on Android.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by yeswap** [comment] 2018-08-20 17:27
I opened Firefox for Android 61.0.2, chose Add-ons from the three dot menu, tapped "Browse all Firefox add-ons", which was the only option for finding add-ins on that screen. That option took me to https://addons.mozilla.org/en-US/android/ where I entered "RSS" in the search box. I got a list of add-ons including  Awesome RSS, Feedbro, Really Simple Rss, Erinome RSS and many more. When I tapped each one, "This add-on is not available on your platform" was displayed. 

There was a Filter Results dropdown at the top of the results page with the only options for Operating System  being Windows, macOS and Linux. There was no option to filter by Android.

**Comment by jvillalobos** [comment] 2018-08-20 20:24
I would expect that searching for "rss" on Android would go to https://addons.mozilla.org/en-US/android/search/?q=rss&platform=android, but that doesn't seem to be the case. I don't have an Android device to confirm this, however.

@bobsilverberg, this seems to be a front-end issue. Can you verify?

**Comment by muffinresearch** [comment] 2018-10-15 11:36
@bobsilverberg did you have a chance to look into this?

**Comment by bobsilverberg** [comment] 2018-10-15 12:16
Sorry, I somehow totally missed this ping. I'll look into it now.

**Comment by bobsilverberg** [comment] 2018-10-16 11:55
Looking at the code for frontend, we do not seem to have any support for Android as an OS when searching. For example, our [code that looks up an OS](https://github.com/mozilla/addons-frontend/blob/2018.10.11/src/core/searchUtils.js#L13-L17) only supports Windows, Linux and Mac OS, and the [search filters provided in the search form](https://github.com/mozilla/addons-frontend/blob/2018.10.11/src/amo/components/SearchFilters/index.js#L122-L131) also only include those OSs.

I checked on the legacy site and notice that it also only provides options for those 3 OSs in the search form, so maybe this is intentional?

What do you think @jvillalobos?

**Comment by diox** [comment] 2018-10-16 12:02
Note that the concept of `platforms` (Windows, Linux, Mac) is going away. What will be kept is the concept of `applications` ("android" is both a platform and an app at the moment).

So to look for add-ons compatible with android, one should just use https://addons.mozilla.org/en-US/android/search/ which should send the right `app` parameter when doing the API request.

I think the problem is that some of the add-ons in the results are marked as compatible android but aren't compatible in reality, because we used to mark webextensions as compatible with android by default. And that's being handled in https://github.com/mozilla/addons-server/issues/6576 so I'm marking this as duplicate.

**Closed by diox** 2018-10-16 12:02 UTC
