### ISSUE TITLE
Always failed to submit form in Add-on Distribution Agreement page

### ISSUE THREAD

**Issue by mika-cn** [mozilla/addons#1061] opened 2019-06-14 13:42 UTC
### What happened?

Hi, I wanted to submit a new version of my add-on a few minutes ago. But AMO redirect me to a page called Add-on Distribution Agreement (https://addons.mozilla.org/en-US/developers/addon/maoxian-web-clipper/versions/submit/agreement). It's Ok, I read the policy and checked those checkbox, input my display name, clicked Accept button. But my submit failed. It said that i should fill this field.

So i checked the source code, and I found this web page use google's  recaptcha (https://www.google.com/recaptcha/api.js?hl=en). Because almost all google service is baned in China, this request failed and i've got nothing, not goolge's recaptcha input field. I'll alway failed to submit this form.

### What did you expect to happen?

I know this is not your fault. Politics always sucks in my country. But If it's possible, please avoid use google service in AMO. That will be very helpful.

**Comment by wagnerand** [comment] 2019-06-14 13:50
This is a duplicate of mozilla/addons-server#9627. We don't really have a workaround other than connecting via a VPN at the moment.

**Closed by wagnerand** 2019-06-14 13:50 UTC
