### ISSUE TITLE
Trouble signing addon. (Duplicate add-on ID found)

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/addons#172] opened 2016-08-01 20:11 UTC
Hello, I'm having an issue signing our unlisted addon.
- My addons email is `davejustishh @ gmail`
- the addon id is `min-vid`
- we are using https://github.com/mozilla/sign-addon in place of `jpm sign`
- repo/branch: https://github.com/meandavejustice/min-vid/tree/addon-signing
- IRC: JSON_voorhees (I'm in #amo)
- actual signing code https://github.com/meandavejustice/min-vid/blob/addon-signing/bin/sign

The error and result:

```
Server response: Duplicate add-on ID found. (status: 400)
{ success: false }
```

**Comment by eviljeff** [comment] 2016-08-01 20:17
I can confirm we got 3 files (1 each for each platform) for version 0.0.1.

**Comment by meandavejustice** [comment] 2016-08-02 17:23
@eviljeff Do I need to go in and delete those?

**Comment by eviljeff** [comment] 2016-08-02 17:36
You can delete them if you want, but you can't re-use those version numbers.  
Are you perhaps submitting as a new add-on each time, rather than a new version to an existing add-on.

**Comment by meandavejustice** [comment] 2016-08-02 19:03
@eviljeff Ahh I see, so we have been using this [script](https://github.com/meandavejustice/min-vid/blob/addon-signing/bin/update-version) to generate a fresh version so there shouldn't be a collision with the version. This is the same script we have been using on testpilot. Wondering why I would be getting the above error even when manually changing the version

**Comment by eviljeff** [comment] 2016-08-03 09:07
I'm not familiar with the script you're using - if you can replicate manually using jpm then we can try the same command ourselves.

**Comment by meandavejustice** [comment] 2016-08-03 15:53
That script simply generates a unique version number so that there should not be a conflict. @eviljeff Is there any other reason one might get that response when signing? Besides the version number?

**Comment by eviljeff** [comment] 2016-08-03 17:37
afaik you could only get that error response if a) you're submitting a new version as a new add-on or b) you don't 'own' that id (i.e. you're submitting under a different email address).  

Looks like you've discounted a) so is the API key the script uses linked to your AMO account?

**Comment by andymckay** [comment] 2016-11-08 01:14
No comments since August, so closing assuming that things are working. If not, please correct me.

**Closed by andymckay** 2016-11-08 01:14 UTC

**Comment by meandavejustice** [comment] 2016-11-08 23:15
I dropped the ball on this. The issue was that I had a stale `install.rdf` with an old version that jpm was picking up. It is resolved, sorry!
