### ISSUE TITLE
Download link for additional dictionary download leads to language pack download

### ISSUE THREAD

**Issue by Habesha-blonde** [mozilla/addons#665] opened 2018-03-15 12:37 UTC
###  the problem and steps to reproduce it:
When trying to install an additional spell check dictionary...
All in Thunderbird in German...
In Settings > ?authoring/composition? In the tab 'spell checking' (German: "Einstellungen > Verfassen > Rechtschreibung") I click the link to download more dictionaries.
like explained in this tutorial: https://support.mozilla.org/de/kb/sprachwoerterbuch-installieren-und-verwenden

### What happened?
The above mentioned link leads to the download page. The topmost line for my language (German) looks like a dictionary is not available. However I can find it in the middle of the page. 
https://addons.mozilla.org/de/thunderbird/language-tools/

### What did you expect to happen?
It would be helpful if the topmost line would include the available dictionaries as well. This would prevent confusion. I (and others) could not find the dictionaries and installed the language pack. This leaves people frustrated (and some give poor ratings because it does not what they expected).

### Anything else we should know?
I came here via Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1445611
It was the wrong place to report. I hope I am rihgt here :-)

**Comment by jvillalobos** [comment] 2018-03-15 18:11
The problem is that the language pack is set to work for all German variants, while the many dictionaries available are targeted for specific variants. Maybe it makes sense to favor the Germany (German) dictionaries in this section, but that would put other variants in a second-class position, which can be a contentious thing to do.

/cc @wagnerand @kewisch @EnTeQuAk for German opinions :)

**Comment by wagnerand** [comment] 2018-03-15 18:24
We could change the target locale for https://addons.mozilla.org/firefox/addon/deutsch-de-language-pack-thund/ to `de-DE` or change the algorithm that determines what to show on top to show `/^de(-[A-Z]+)?$/` instead of just `/^de$/`.

**Comment by Habesha-blonde** [comment] 2018-03-16 09:53
I do not understand wagnerand's comment. 
But maybe his second proposed solution would show all options for German languages (German (language pack) + German (Austria), German (Germany), German (Switzerland)) on top? That would be very helpful for unexperienced users!
If this schould not be possible, a secondbest solution could be, to show no "suggestion" on top for German. The user would find a list of languages and would understand he had to scroll to find his choice.

**Comment by jvillalobos** [comment] 2018-03-20 21:27
It does sound to me like the best solution here is to show all variants of the language in the suggestions. So if you're visiting from `/ab-CD/` or `/ab/`, we should suggest anything matching `ab(-[A-Z]+)?`.

**Comment by eviljeff** [comment] 2018-03-21 09:12
There's something to be said for showing more options for other languages that have locale variants where users might be interested in something different than the strict locale code in the url - e.g. English, Spanish, Portuguese, Norwegian, etc.

In regards to this issue specifically though: Thunderbird gets served legacy frontend pages and we aren't doing any more development on legacy frontend.  (The developers for https://github.com/thundernest/addons-server/ may want to address it in the future).  Firefox gets the new frontend, where this issue exists also, but would be fixed on the addons-frontend and it wouldn't help Thunderbird users.  Realistically this issue should be closed and a Firefox focused issue opened on addons-frontend if you want it fixed.

**Comment by Habesha-blonde** [comment] 2018-03-21 11:17
I can not reproduce the issue on my Firefox (59.0.1). The settings menu there shows a list of all(?) the dictionaries available to be added. There are no suggestions.

**Comment by eviljeff** [comment] 2018-03-29 06:26
Closing this for reasons [mentioned](https://github.com/mozilla/addons/issues/665#issuecomment-374873321)

**Closed by eviljeff** 2018-03-29 06:26 UTC
