### ISSUE TITLE
Not getting a confirmation email for resetting api key

### ISSUE THREAD

**Issue by stevenwong-okta** [mozilla/addons#1390] opened 2022-02-01 18:32 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I tried to re-generate the API key on this page: https://addons.mozilla.org/en-US/developers/addon/api/key/ . After clicking regenerate, I see this message but did not receive any email. `A confirmation link will be sent to your email address. After confirmation you will find your API keys on this page.
`

Is there any ways to retrigger the email? Note: I also changed my password and did receive an email confirming my password was changed; so my email is working. Also checked the spam/trash/all mail folder for emails
"
### What happened?
No API key displayed.

### What did you expect to happen?
I should have an email with the link to confirm
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
<img width="840" alt="Screen Shot 2022-02-01 at 10 30 45 AM" src="https://user-images.githubusercontent.com/31224795/152029158-1f2fdd6e-fbb2-4d57-9920-a53e62a9700b.png">

**Comment by ioanarusiczki** [comment] 2022-02-04 08:13
Yes, I seem to have the same problem, I tried to generate new credentials on one account, and on another they've been revoked and I asked for new ones but I did not get the e-mail.  I tested from -dev and -stage

CC @diox

**Comment by diox** [comment] 2022-02-04 10:56
dev and stage wouldn't send real emails - but that's a good test: I can see the mails in `FakeEmail` in both cases, so I don't think this is a code issue.

The problem is likely more, in production, at the email delivery service. It may have put the email in a deny list for delivery failures at some point. We don't get a notification when that happens, so the only solution for us is to wait for legitimate affected users to tell us so we can check. 

@stevenwong-okta, would you mind sharing your user ID in this issue? You'll find it in the URL of "My profile" link. Alternatively, send an email to amo-admins@ with the same email as your account.

**Comment by wagnerand** [comment] 2022-02-04 18:47
I'm closing this issue here since we handled this over email.

**Closed by wagnerand** 2022-02-04 18:47 UTC

**Comment by diox** [comment] 2022-03-01 15:46
@gaberger same as above:
> would you mind sharing your user ID in this issue? You'll find it in the URL of "My profile" link. Alternatively, send an email to amo-admins@ with the same email as your account.
