### ISSUE TITLE
Statistics missing for several days

### ISSUE THREAD

**Issue by mikel2000** [mozilla/addons#545] opened 2017-11-16 11:47 UTC
Download statistics are missing for these days: 6-8th, 14th of November.
Daily users statistics are missing for these days: 10th, 14th of November.
Please check here for example: https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30

**Comment by jvillalobos** [comment] 2017-11-16 14:08
Closing as duplicate of https://github.com/mozilla/addons/issues/510

**Closed by jvillalobos** 2017-11-16 14:08 UTC
