### ISSUE TITLE
AMO Rejects ZIP File Created With PowerShell

### ISSUE THREAD

**Issue by pastelmind** [mozilla/addons#769] opened 2018-08-14 07:22 UTC
Addon validation on AMO fails with "Validation was unable to complete successfully due to an unexpected error." even though the unpackaged extension works fine in Firefox 61.0.2 and passes `addons-linter` (with warnings).

* Error occurred during submission of new add-on
* Add-on is not listed yet, but will be once it passes the test.
* Addon was submitted to https://addons.mozilla.org/ko/developers/addon/submit/upload-listed (error report: https://addons.mozilla.org/ko/developers/upload/423b5ad894fa4e44b2c7e776108817c7 )
* Time of submission: approx. 16:18, UTC +09:00 (Seoul, Republic of Korea)

Addon file: [ruliweb-hots.0.7.0.zip](https://github.com/mozilla/addons/files/2285858/ruliweb-hots.0.7.0.zip)

Edit: After some testing, it seems that there is a problem with the ZIP file itself, rather than the contents. The AMO site fails to validate a ZIP file created using PowerShell ([`Compress-Archive`](https://docs.microsoft.com/powershell/module/microsoft.powershell.archive/compress-archive)). When I create the ZIP file with other tools, AMO happily accepts it. The zip file posted above was created with PowerShell, hope it helps.

**Comment by diox** [comment] 2018-08-29 16:10
FWIW that zip uses `\` instead of `/` as the separator and that seems to be what's causing the issue. Not entirely sure if it's fixable on our end (it would require repackaging it for our various tools).

**Comment by muffinresearch** [comment] 2018-08-30 10:03
This looks to be a duplicate of https://github.com/mozilla/addons-linter/issues/1426

**Closed by muffinresearch** 2018-08-30 10:03 UTC
