### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Fofonew** [mozilla/addons#897] opened 2019-02-08 09:09 UTC
Hello i can't upload my add on, he works perfectly and no error message in the console no idea what is the problem, i tried tu push the add on from this link: https://addons.mozilla.org/fr/developers/addon/submit/upload-listed

Just got a simple error but no error message if you can help me please its gonna be cool 🗡 Thanks.

[loe.zip](https://github.com/mozilla/addons/files/2844361/loe.zip)

**Comment by EnTeQuAk** [comment] 2019-02-08 09:10
Same problem as in https://github.com/mozilla/addons/issues/896

The problem is, your add-on is packaged wrong. You don't have the `manifest.json` on the root of the folder, instead, there's a subfolder containing all the data.

[developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension)_

We should issue a better error though, so I opened [mozilla/addons-server#10635](https://github.com/mozilla/addons-server/issues/10635) to fix that.

Closing here.

**Closed by EnTeQuAk** 2019-02-08 09:10 UTC
