### ISSUE TITLE
List of "Trending extensions" and "Top rated extensions" now contains only recommended extensions

### ISSUE THREAD

**Issue by icl7126** [mozilla/addons#1075] opened 2019-07-18 09:40 UTC
### Describe the problem and steps to reproduce it:
1. go to https://addons.mozilla.org/en-US/firefox/extensions/
2. click "[See more top rated extensions](https://addons.mozilla.org/en-US/firefox/search/?recommended=true&sort=rating&type=extension)" link
OR
"[See more trending extensions](https://addons.mozilla.org/en-US/firefox/search/?recommended=true&sort=hotness&type=extension)"

### What happened?
Bot list contains only recommended extensions
### What did you expect to happen?
It should filter from all addons

**Comment by willdurand** [comment] 2019-07-18 11:49
@bobsilverberg I see that we're passing `recommended=true` for each shelf. That explains what's described here, but was it intended? We only surface recommended extensions by default, right?

**Comment by bobsilverberg** [comment] 2019-07-18 12:25
> @bobsilverberg I see that we're passing `recommended=true` for each shelf. That explains what's described here, but was it intended? We only surface recommended extensions by default, right?

Yes, this is the intended behaviour. Both the shelves on the landing pages, and also the resulting "See more..." pages are meant to be restricted to recommended add-ons only. Therefore I am closing this issue.

**Closed by bobsilverberg** 2019-07-18 12:25 UTC
