### ISSUE TITLE
Cannot attach sources

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons#189] opened 2016-08-24 06:17 UTC
The dev had issues uploading his sources attachment. So I went in as admin and tried to upload, but I also
[hot_gia_tot-0.90.5-source-code.zip](https://github.com/mozilla/addons/files/434123/hot_gia_tot-0.90.5-source-code.zip)
 got a "Oops" page.

Here is the version of the addon I tried to upload for - https://addons.mozilla.org/en-US/developers/addon/h%E1%BB%91t-gi%C3%A1-t%E1%BB%91t/versions/1912511 - also attached to this issue.

And this is the attachment I was trying to upload - https://drive.google.com/file/d/0B5R2g5ny1rZyeFJjcm5QNDRYR3Rkc0k4MjdKamZfMnRvNkY4/view?usp=sharing

**Comment by diox** [comment] 2016-08-24 09:27
This is a duplicate of https://github.com/mozilla/addons/issues/132

**Closed by diox** 2016-08-24 09:27 UTC
