### ISSUE TITLE
[Task]: Implement Github Action based release workflow for addons-frontend

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons#15184] opened 2024-11-21 00:01 UTC
### Description

The `addons-server` has been utilizing GitHub Actions for code release for several months now. I propose that we implement the same system for `addons-frontend` to streamline our release process and avoid the overhead of managing two separate release systems.

### Acceptance Criteria

`addons-frontend` should use the same GitHub Actions workflows as `addons-server` for code release, ensuring consistency across the board.

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1248)

**Comment by diox** [comment] 2024-11-21 00:17
This is a duplicate of https://github.com/mozilla/addons/issues/15128

**Closed by diox** 2024-11-21 00:17 UTC
Labels: repository:addons-frontend
