### ISSUE TITLE
Addon Validation Error: Useless error message for missing manifest.json

### ISSUE THREAD

**Issue by quassy** [mozilla/addons#932] opened 2019-03-02 11:36 UTC
I tried to submit a new, listed add-on via the [Addons website](https://addons.mozilla.org/de/developers/addon/submit/upload-listed) at 11:20 UTC and got the following, pretty useless error message:

> Your add-on failed validation with 1 error.
> Sorry, we couldn't load your WebExtension.

The detailed report is also not really helpful (translated from German):

> General Tests
> 1 error, 0 warnings, 0 notices
> Security Tests
> 0 errors, 0 warnings, 0 notices
> Extension Tests
> 0 errors, 0 warnings, 0 notices
> Translation Tests
> 0 errors, 0 warnings, 0 notices
> Comapbility Tests
> 0 errors, 0 warnings, 0 notices

Instead, loading the add-on to about:debugging was much more helpful and pretty straightforward:

> File my-addon.zip does not contain a valid manifest

(I packaged the add-on in a wrong way as I had my-addon as a root folder inside the zip.)

The error message on the website should be more useful, especially if it's something as basic as a missing manifest.json (["Your extension must contain a valid manifest.json file at the root level."](https://developer.mozilla.org/de/docs/Mozilla/Add-ons/WebExtensions/manifest.json)), a root folder which has the same name as the archive (["The ZIP file must be a ZIP of the extension's files themselves, not of the directory containing them."](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension_)) but also an invalid manifest.json ("Your manifest.json is invalid because it's not valid json", "Your manifest.json is invalid because it is missing one of the mandatory keys "manifest_version", "version", and "name".", ""default_locale" must be present if the "_locales" directory is present and must be absent otherwise."...), which I haven't tried yet.

**Comment by DiegoFleitas** [comment] 2019-03-04 04:48
> 
> 
> I tried to submit a new, listed add-on via the [Addons website](https://addons.mozilla.org/de/developers/addon/submit/upload-listed) at 11:20 UTC and got the following, pretty useless error message:
> 
> > Your add-on failed validation with 1 error.
> > Sorry, we couldn't load your WebExtension.
> 
> The detailed report is also not really helpful (translated from German):
> 
> > General Tests
> > 1 error, 0 warnings, 0 notices
> > Security Tests
> > 0 errors, 0 warnings, 0 notices
> > Extension Tests
> > 0 errors, 0 warnings, 0 notices
> > Translation Tests
> > 0 errors, 0 warnings, 0 notices
> > Comapbility Tests
> > 0 errors, 0 warnings, 0 notices
> 
> Instead, loading the add-on to about:debugging was much more helpful and pretty straightforward:
> 
> > File my-addon.zip does not contain a valid manifest
> 
> (I packaged the add-on in a wrong way as I had my-addon as a root folder inside the zip.)
> 
> The error message on the website should be more useful, especially if it's something as basic as a missing manifest.json (["Your extension must contain a valid manifest.json file at the root level."](https://developer.mozilla.org/de/docs/Mozilla/Add-ons/WebExtensions/manifest.json)), a root folder which has the same name as the archive (["The ZIP file must be a ZIP of the extension's files themselves, not of the directory containing them."](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension_)) but also an invalid manifest.json ("Your manifest.json is invalid because it's not valid json", "Your manifest.json is invalid because it is missing one of the mandatory keys "manifest_version", "version", and "name".", ""default_locale" must be present if the "_locales" directory is present and must be absent otherwise."...), which I haven't tried yet.

you are the best, I was doing multiple of the things you listed wrong. You agree with you 100%

**Comment by EnTeQuAk** [comment] 2019-03-04 08:19
Duplicate of #908, please make sure to package your manifest.json at the root level - as the error in the error message notes.

We're working on a more reasonable error message in #908

**Closed by EnTeQuAk** 2019-03-04 08:19 UTC

**Comment by krishnadevz** [comment] 2020-02-09 04:41
<img src="https://github.com/krishnadevz/CoronavirusRemover/blob/master/firefox.gif" alt="click for detailed how to create folder and all">
after clicking on creating zip folder then you can upload that zip file in firefox extensions after that **your extension will be published only select files according to 
1. manifest.json
2.script.js
3.style.css**
