### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by santanp** [mozilla/addons#913] opened 2019-02-15 14:44 UTC
Please attach a copy of your add-on, and fill in the following information:
[https://mockphishpage.blob.core.windows.net/shareddata/old_dev_firefox.zip](url)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
Error during  upload to the standalone validator
* Whether your add-on is listed or unlisted.
unlisted
* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/developers/addon/b2fdf5ff0548492aabfd/versions/submit/
* The approximate time you submitted the add-on, with timezone.
15/02/2019 8.10 IST

**Comment by EnTeQuAk** [comment] 2019-02-15 14:47
Duplicate of #896

The problem is, your add-on is packaged wrong. You don't have the `manifest.json` on the root of the folder, instead, there's a subfolder containing all the data.

[developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension)_

We should issue a better error though, so I opened [mozilla/addons-server#10635](https://github.com/mozilla/addons-server/issues/10635) to fix that.

Closing here.

**Closed by EnTeQuAk** 2019-02-15 14:47 UTC
