### ISSUE TITLE
Addon Daily User Statistics showing zero (again)

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#366] opened 2017-04-06 07:54 UTC
There have been numerous bugs filed for this issue over the years, and all marked resolved.

However, the bug is back.
At the moment, daily users stats for March 29, 30, 31 and April 3, 4 all show zero users.

**Comment by jvillalobos** [comment] 2017-04-06 15:27
Confirmed in https://addons.mozilla.org/addon/adblock-plus/statistics/?last=30

**Comment by erosman** [comment] 2017-04-07 11:02
Mar 29 - Apr 3 have been fixed.
Now Apr 4-5 show zero across the board.

**Comment by erosman** [comment] 2017-04-09 08:23
Apr 4, 5, 6, 7 show zero at the moment across the board.
Download stats are working. Daily user stats aren't.

**Comment by MaDonnasPersonas** [comment] 2017-04-12 21:20
April 8th and part of the 9th across the board also.

**Comment by MaDonnasPersonas** [comment] 2017-04-27 18:55
User count on all designers themes not counted since sometime on April 23rd.

**Comment by muffinresearch** [comment] 2017-05-08 14:18
@MaDonnasPersonas are you still seeing a problem for stats?

**Comment by MaDonnasPersonas** [comment] 2017-05-08 15:18
The problem seems to be fixed.

**Comment by MaDonnasPersonas** [comment] 2017-05-11 18:47
Update on user count 0. No one's themes have been counted since Monday May 8th. So something isn't working right again.

**Comment by jasonthomas** [comment] 2017-05-11 20:12
I checked my theme stats - https://addons.mozilla.org/en-US/firefox/addon/one-punch-man-ok/statistics/usage/?last=30 - seems fine. Where are you seeing 0?

**Comment by jasonthomas** [comment] 2017-05-11 20:20
Okay I see, https://addons.mozilla.org/en-US/firefox/themes/?sort=created&page=4. I've added `update_theme_popularity_movers` as part of the retry. Should be fixed going forward.

**Comment by MaDonnasPersonas** [comment] 2017-05-11 20:21
When I checked this morning no themes had any users as far back as May 8th. but now it is May 9th so something got updated between now then.

**Comment by MaDonnasPersonas** [comment] 2017-08-18 19:32
Counter hasn't been updated since Aug. 15th on any themes.

**Comment by jvillalobos** [comment] 2017-08-18 20:27
See also https://github.com/mozilla/addons-server/issues/6199

**Comment by bqbn** [comment] 2017-08-18 21:48
I looked at this theme [1], and it has data up to 8/17 as of this comment.

[1] https://addons.mozilla.org/en-US/firefox/addon/dark-fox-18066/statistics/usage/?last=30

**Comment by MaDonnasPersonas** [comment] 2017-08-18 22:04
Yes, it is working now. Thank you.

**Comment by erosman** [comment] 2017-08-19 19:30
Stats show zero users on Aug 16 (and Aug 18)

**Comment by erosman** [comment] 2017-08-22 18:28
Aug 16 is still zero across the board

**Comment by MaDonnasPersonas** [comment] 2017-08-22 18:35
Last **all** themes counted was Aug 19.

**Comment by bqbn** [comment] 2017-08-22 23:50
8/20 and 8/21 data were delayed. They should be there now. We have a bugzilla ticket open with the data team to work on 8/16 data.

Going forward, please try to post a link to where you see the data is missing. This helps when we need to verify an issue is fixed or not.

**Comment by MaDonnasPersonas** [comment] 2017-08-23 00:29
I am sorry. I will do so in the future.

**Comment by bqbn** [comment] 2017-08-23 01:23
No worries! It meant to be a request not a complaint. Thank you for helping us make the site better! :)

**Comment by erosman** [comment] 2017-08-28 18:02
> Going forward, please try to post a link to where you see the data is missing. This helps when we need to verify an issue is fixed or not.

It seems to be across the abroad (i.e. all my addons).. but here is an example of missing data on Aug 16th:
`https://addons.mozilla.org/firefox/addon/copy-plaintext/statistics/?last=30`

**Comment by bqbn** [comment] 2017-08-29 04:06
Thanks for the link. Missing data on 8/16 is a known issue (As mentioned in https://github.com/mozilla/addons/issues/366#issuecomment-324182352), and we've filed a bugzilla ticket with our data team, who is still working on it.

**Comment by erosman** [comment] 2017-09-13 19:31
Addon's Daily Users on Sep 12 is zero across the board
Downloads are fine

**Comment by jasonthomas** [comment] 2017-09-13 19:53
Sept12 should update correctly later today.

**Comment by bqbn** [comment] 2017-09-13 20:40
8/16 data is restored. For example,
https://addons.mozilla.org/en-US/firefox/addon/copy-plaintext/statistics/usage/?last=30

**Comment by erosman** [comment] 2017-09-14 04:23
Confirmed ... both Aug 16 and Sep 12 data are displayed.

**Comment by jasonthomas** [comment] 2017-09-14 14:50
Marking this closed. Let us know if you see any other issues. Thanks!

**Closed by jasonthomas** 2017-09-14 14:50 UTC
Labels: needs: info, needs: ops, triaged

**Comment by MaDonnasPersonas** [comment] 2017-10-19 19:28
Theme counter quit sometime on Oct. 14th on **all** themes. [https://addons.mozilla.org/en-US/firefox/themes/?sort=created&page=9](url)

**Comment by erosman** [comment] 2017-10-19 20:12
All add-ons zero on Oct 17th

**Comment by bqbn** [comment] 2017-10-20 01:18
Restored data for 10/17 and 10/18.

Please feel free to file a new issue when this happens again.

**Comment by erosman** [comment] 2017-10-21 10:25
All add-ons zero on Oct 19th

**Comment by wagnerand** [comment] 2017-10-21 11:08
Please file a new issue.

**Comment by MaDonnasPersonas** [comment] 2017-10-25 19:58
Theme counter quit sometime during Sunday October 22. [https://addons.mozilla.org/en-US/firefox/themes/?sort=created&page=5](url)

**Comment by bqbn** [comment] 2017-10-26 00:31
How do I tell the counter quit during October 22? The page you linked above doesn't seem to have a date on it.

Also I looked at https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/statistics/usage/?last=30 and it has data for Oct. 22.

**Comment by MaDonnasPersonas** [comment] 2017-10-26 06:36
Go to Recently Added Themes and go to page 5 or 6 now and check the dates. They stop on Oct. 22md. Sorry the link didn't work....

**Comment by bqbn** [comment] 2017-10-26 22:46
I followed the steps and went to that page, and I still don't see a date on the page. Maybe you can indicate where I can see Oct 22?

**Comment by MaDonnasPersonas** [comment] 2017-10-26 22:55
Go to: https://addons.mozilla.org/en-US/firefox/themes/?sort=created&page=7

I attached a copy of the page and highlighted where the number of users is
shown. No users on any themes since sometime early Oct. 22nd.

Hope this helps.

**Comment by bqbn** [comment] 2017-10-27 00:08
I go to that page, and I can see the 0 daily users for most of the themes on that page. However, I still don't see Oct.22, or any date on that page.

Could you attach a screenshot with the dates shown?

Sorry for the request. I'm thinking that if I know where to see the dates, it'll help me quickly identify when the issue happened in the future, instead of having to bother you again.

**Comment by MaDonnasPersonas** [comment] 2017-10-27 00:44
Well, since I sent the last email, the counter is working up to the 24th.
Now this is just sent I sent the last email. I am attaching a screen shot
of where to find the date. You have to click on a theme to show the date.
Hope this helps and hope the counter is fixed. Does this help? If not, I
will try to explain it better...OK?

And thank you.

**Comment by bqbn** [comment] 2017-10-27 01:24
Your attachment must have got lost somewhere. I don't see it either in my email inbox, or on the github.com interface. However, I do see the date after clicking into a theme.

There was another issue https://github.com/mozilla/addons/issues/510#issuecomment-339598298 that reported missing stats for 10/24, which got fixed recently. That might have resolved the issue you saw as well.

Our log shows that 10/25 stats were run successfully, and we can see about 10/26 tomorrow.

However, I

**Comment by MaDonnasPersonas** [comment] 2017-10-27 01:31
I sent it as an attachment so will send it in the email
itself...hopefully:  [image: Inline image 2]
 I couldn't find how to add the capture to github. But you do have to click
on a theme itself to get the date. I should have been clearer in my
explanation.

**Comment by MaDonnasPersonas** [comment] 2017-11-07 22:41
I am not positive because of the different way to view the themes websites, BUT I don't think there has been any counting done since November 1st. or 2nd. You can go to page 6 of Recently Updated themes and currently you can go to page 6 to find the last one counted and there are no others counted far beyond that.

**Comment by MaDonnasPersonas** [comment] 2017-11-10 19:04
Daily usage of themes hasn't been updated since Nov. 4th.

**Comment by bqbn** [comment] 2017-11-11 07:04
I restored the theme stats for 11/7, because that's a date for which I can tell it's missing. Please let me know if you see differently.

Also there is a new issue for reporting missing stats, i.e. issue #510. 

Could you start to report issues and/or provide feedbacks in that issue? This one is closed.

**Comment by MaDonnasPersonas** [comment] 2018-01-31 21:15
User counts on themes haven't counted since sometime on Jan. 28th. 

[https://addons.mozilla.org/en-US/firefox/themes/?sort=created&page=5](url)
