### ISSUE TITLE
[Reviewer Tools] New Permissions display

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#390] opened 2017-05-05 13:13 UTC
The display of the **Permissions** was added to the latest push for May 5th, 2017. It is a good feature to have.

The following could improve the display:

- Some addon have a VERY long list of permissions
Adding a `max-height: **px; overflow: auto;` would prevent long stretching of the container.
Alternatively, adding an easy CSS selector would enable us to do it ourselves.
I actually do that for some other element on that page (eg .history-note etc) since some have LONG texts. 

- When addon has separate version for each platform, the long list gets even longer, eg:
`https://addons.mozilla.org/en-US/editors/review/734766/`

**Comment by muffinresearch** [comment] 2017-05-05 13:52
Duplicate of https://github.com/mozilla/addons-server/issues/5339

**Closed by muffinresearch** 2017-05-05 13:52 UTC
