### ISSUE TITLE
Can't find the existing "Search This On" add-on when editing collection

### ISSUE THREAD

**Issue by cc85** [mozilla/addons#359] opened 2017-03-25 19:39 UTC
My English is pretty limited, please don't mind.
The feedback use machine translation.

### Describe the problem and steps to reproduce it:
Edit Collections
Search for "Search This On"
Search results do not have "Search This On"

### What happened?
Can not add "Search This On" ( https://addons.mozilla.org/firefox/addon/597426 ) to the collection.

### What did you expect to happen?
Should search for "Search This On" and add the collection.

### Anything else we should know?
https://bugzilla.mozilla.org/show_bug.cgi?id=1349599

**Comment by diox** [comment] 2017-05-09 15:21
IMHO we should just boot exact matches more, I don't think we should bother with quotes. I already filed an issue a while ago, never had the time to work on it: https://github.com/mozilla/addons-server/issues/2661

**Comment by EnTeQuAk** [comment] 2017-08-18 17:57
I'm going to work on this next week together with other search related issues.

**Comment by irvinm** [comment] 2017-10-29 13:43
I have another example that doesn't work when trying to add it to a collection.  "View Image in New Tab" (https://addons.mozilla.org/en-US/firefox/addon/new-tab-image_exe-boss)  I do see it part of 2 other collections, but can't find it in the search results to add it to my collection which already has 25 items. (https://addons.mozilla.org/en-US/firefox/collections/irv66/webextensions/)

**Comment by diox** [comment] 2017-11-17 11:53
Note that we've opened up another issue about exact matching: https://github.com/mozilla/addons-server/issues/6837

**Comment by EnTeQuAk** [comment] 2018-01-30 06:39
https://github.com/mozilla/addons-server/pull/7303 has landed on master and will be deployed on Thursday and should fix this problem. I'm closing this issue but please feel free to re-file / re-open any time if things aren't working properly.

**Comment by AlexandraMoga** [comment] 2018-01-30 13:19
Verified on AMO-dev, FF58 (Win10, Android 7.0)
I've named one of my add-ons _'Search this on"_ and searched for it on AMO and in the Add to collection form. The add-on was listed low among search suggestions on AMO while in add to collection page wasn't listed at all

Add-on: https://addons-dev.allizom.org/en-US/firefox/addon/white-frost/

![image](https://user-images.githubusercontent.com/31961530/35568119-69d2c44e-05d0-11e8-8c84-e04894669965.png)
![image](https://user-images.githubusercontent.com/31961530/35568256-ebe8b11e-05d0-11e8-9c2b-f46a658f0797.png)

**Comment by diox** [comment] 2018-11-13 13:42
This was caused by https://github.com/mozilla/addons-server/issues/9196 which is now fixed.

**Closed by diox** 2018-11-13 13:42 UTC
Labels: component: search, priority: p3, triaged
