### ISSUE TITLE
Add-on submission version notes, details missing, never updated. Auto-update does not work as expected.

### ISSUE THREAD

**Issue by netquik** [mozilla/addons#1412] opened 2022-05-14 06:32 UTC
### Describe the problem and steps to reproduce it:
I'm finding some problems in submission of new versions of add-on.
First. it seems not possible to update new version notes for updated package.
When submitting the textarea for version notes does not appear (only notes for reviewers)
![image](https://user-images.githubusercontent.com/24799070/168413539-4b5bca75-04f3-4eb1-8b10-2fa72486a7f6.png)
Then also if we edit version notes manually for the version. They do not appear in add-on tab
![image](https://user-images.githubusercontent.com/24799070/168413603-e4c0f4be-afc0-4790-8ad8-f2f4039fc585.png)
Note that i'm seeing problems also for autoupdate.
In the above screenshot you see that Firefox found an update for the add-on.
Well updating does nothing. And after it find again the update.
![image](https://user-images.githubusercontent.com/24799070/168413665-0e8e28b8-2c2b-4643-89b5-01f6ff69c0ae.png)
![image](https://user-images.githubusercontent.com/24799070/168413732-1750cd28-4fb3-433c-9120-b3fbddb4aa9a.png)
Finally add-on details are never updated (that is the text of first submission)
![image](https://user-images.githubusercontent.com/24799070/168413801-0ac783ee-fb92-465d-892d-7462b5e6cb8c.png)

### What happened?
Add-on submission version notes, details never updated. Add-on update does not work as expected.

### What did you expect to happen?
Version notes updates should appear during submission and the whole update should get new details.

**Comment by Juraj-Masiar** [comment] 2022-05-14 08:43
Something's wrong with all addon updates, none of the recently released addon updates are available.
I've reported similar issue here:
https://github.com/mozilla/addons-server/issues/19243

**Comment by netquik** [comment] 2022-05-14 09:12
@Juraj-Masiar here there is no warning in console. just the GET for add-on icon.
For issues related to missing version notes I noticed them since months

**Comment by diox** [comment] 2022-05-14 09:27
Hi,

Your missing version notes issue is a duplicate of https://github.com/mozilla/addons-server/issues/4599 , which depends on locale. The updates being broken is new and unrelated, and a duplicate of https://github.com/mozilla/addons-server/issues/19243.

**Closed by diox** 2022-05-14 09:27 UTC
