### ISSUE TITLE
[Bug]: I have an addon with version 0.5.1, 0.5.2. and deleted 0.5.2. I am unable to upload a new version now.

### ISSUE THREAD

**Issue by indykish** [mozilla/addons#15118] opened 2024-10-30 09:01 UTC
### What happened?

I had an add on with the versions 
- 0.5.1
- 0.5.2

I tried to upload the same version 0.5.2, it said the version exists
Then i deleted the 0,5.2 and tried to upload 0.5.2, it said the version existed before and was deleted.
Then i changed my manifest version to 0.5.3
![image](https://github.com/user-attachments/assets/61426ced-1c7b-464e-a389-8c1fb8faa117)
When i try to upload this version, I see an error "Ops an error occurred.."

![image](https://github.com/user-attachments/assets/90190ff6-c0d6-4420-ab41-c6cac77fed34)

I tried refreshing the page, and going back and forth and doing uploads again.

I am unable to upload a new version, after having deleted the previous version.

### What did you expect to happen?

I expect a new version(0.5.3) to be uploaded and an xpi to be available upon approval.

I think this may be connected to this https://github.com/mozilla/addons/issues/15116

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1173)

**Comment by FirstTimeEZ** [comment] 2024-10-30 09:45
I get `500 Internal Server Error`

![Screenshot 2024-10-30 224420](https://github.com/user-attachments/assets/a74244e3-a06f-4456-a466-7aa562dc6a18)

**Comment by wagnerand** [comment] 2024-10-30 10:39
Thank you for the reporting. This is a duplicate of #15116

**Closed as not planned by wagnerand** 2024-10-30 10:39 UTC
Labels: needs:info
