### ISSUE TITLE
AMO Addon Validator breaks due to out-of-date JS validation not supporting optional catch bindings, preventing uploads

### ISSUE THREAD

**Issue by davegarrett** [mozilla/addons#744] opened 2018-06-29 20:54 UTC
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#The_exception_identifier

https://bugzilla.mozilla.org/show_bug.cgi?id=1380881

Firefox 58 (and Google Chrome 66) added support for optional catch bindings, e.g.:
`try { thing(); } catch { whatever(); }`
instead of always requiring, e.g.:
`try { thing(); } catch (e) { whatever(); }`

AMO did not. Whatever you currently use in the addon validator to validate JS is out-of-date and chokes when it doesn't see a binding after a catch. The error message doesn't even say that's the issue, but fortunately it gives exact line numbers so it's very easy to figure out. The main text of the error message given is:
> JavaScript syntax error
> Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.

The error completely prevents the upload and signing of any addons to AMO that use this newer JS feature. Fortunately, in this case, it's an easy fix; just sticking in a few pointless "(e)" where they used to be needed is not horrible. That said, having to do that is stupid. Please properly allow everything Firefox actually allows. (bonus points for still detecting this if the minversion is less than 58, but preferably with a real error message)

**Comment by muffinresearch** [comment] 2018-07-04 13:44
Duplicate of https://github.com/mozilla/addons-linter/issues/1958

**Closed by muffinresearch** 2018-07-04 13:44 UTC
