### ISSUE TITLE
[Bug]: 500 returned on a particular content review page

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#14864] opened 2024-06-19 15:49 UTC
### What happened?

When trying to access review page for add-on `1474217`, a 500 error is returned. This seems to trigger a `Version.file.RelatedObjectDoesNotExist` error on [Sentry](https://mozilla.sentry.io/issues/5419762234/?project=6310819)

### What did you expect to happen?

The content review page should open normally without an error

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-863)

**Comment by diox** [comment] 2024-06-19 15:52
Duplicate of https://github.com/mozilla/addons/issues/14813

**Closed by diox** 2024-06-19 15:52 UTC
Labels: needs:info
