### ISSUE TITLE
When a user updates their review and changes star rating, the average review doesn't change.

### ISSUE THREAD

**Issue by jeremybmerrill** [mozilla/addons#222] opened 2016-09-21 17:47 UTC
### Describe the problem and steps to reproduce it:
My add-on has only one review. The user who gave the review initially gave the add-on one star, but a few minutes later, updated their review to give five stars. The average review on my add-on still says one-star -- even though the only review is a five-star review.

1.) Create a new add-on.
2.) Have a user review it, giving it one star.
3.) Have the user update their review, giving it five stars.
4.) Observe how the add-on's average star review remains at one-star.

### What did you expect to happen?
The average should be correctly calculated from the updated star rating. I would hypothesize, naively, that perhaps average ratings are cached and an updated review doesn't trigger the app to recalculate the average rating.

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/adtrack-new-york-times/
![screenshot 2016-09-21 13 47 31](https://cloud.githubusercontent.com/assets/548250/18722214/f8a061e6-8001-11e6-9bc8-5bf04344156d.png)

**Comment by wagnerand** [comment] 2016-09-28 12:18
Duplicate of https://github.com/mozilla/addons-server/issues/1618

**Closed by wagnerand** 2016-09-28 12:18 UTC
