### ISSUE TITLE
install Extension bug

### ISSUE THREAD

**Issue by zorky01** [mozilla/addons#1027] opened 2019-05-04 22:12 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
tried to install some extensions. comes up with "Download failed. Please check your connection"
### What happened?
using latest ver of firefox "66.0.3" had to hunt for new extensions because all my standard "ad blocker extensions" stopped working or been removed due to build. tried to install extension as normal and got bug/error.  confirmed that my internet connection is good.
### What did you expect to happen?
![Screenshot (8)](https://user-images.githubusercontent.com/26033703/57185376-80f04a00-6f0d-11e9-9ea9-ccd5a3b9fa9d.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment] 2019-05-04 22:22
This is a duplicate of #1013.
Please refer to https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Closed by wagnerand** 2019-05-04 22:22 UTC
