### ISSUE TITLE
[Bug]: extension upload error

### ISSUE THREAD

**Issue by uaoleg** [mozilla/addons#15121] opened 2024-10-30 11:56 UTC
### What happened?

Trying to upload new version of my extension

### What did you expect to happen?

Success upload, but seeing this error page

![Oops](https://github.com/user-attachments/assets/074e8510-d5fc-4210-b989-cbbd26ac88c1)

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1176)

**Comment by wagnerand** [comment] 2024-10-30 11:58
Duplicate of #15116.

**Closed by wagnerand** 2024-10-30 11:58 UTC
Labels: needs:info
