### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by ntinkler-calendly** [mozilla/addons#1520] opened 2023-08-21 14:07 UTC
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

This is happening during an upload of a new version of an existing add-on.

* Whether your add-on is listed or unlisted.

Listed

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/calendly-meeting-scheduling/versions/submit/

* The approximate time you submitted the add-on, with timezone.

10:04 AM, Monday Aug 21st, EDT (GMT-04).

**Comment by ntinkler-calendly** [comment] 2023-08-21 14:08
[firefox_production_3.2.0.0.zip](https://github.com/mozilla/addons/files/12396857/firefox_production_3.2.0.0.zip)

**Comment by wagnerand** [comment] 2023-12-12 11:41
If you are using a lot of large or complex javascript files, that might be an issue yes. Closing as duplicate of https://github.com/mozilla/addons-linter/issues/4942.

**Closed by wagnerand** 2023-12-12 11:41 UTC
