### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by Vinnl** [mozilla/addons#950] opened 2019-03-12 10:30 UTC
> Please attach a copy of your add-on, 

I've attached two versions:

* The last working one: [plaudit-0.1.18-an+fx.zip](https://github.com/mozilla/addons/files/2956271/plaudit-0.1.18-an%2Bfx.zip)
* The failing one: [plaudit-0.1.19-an+fx.zip](https://github.com/mozilla/addons/files/2956270/plaudit-0.1.19-an%2Bfx.zip)

Except that the attached extensions _do_ work - it's only when I tried to install them from addons.mozilla.org that I ran into errors. The exact errors differ:

- On my regular Firefox, and Firefox Nightly:

![image](https://user-images.githubusercontent.com/4251/54193201-e13caf80-44b9-11e9-85f0-fb906572e5b4.png)

- In Tor browser:

![image](https://user-images.githubusercontent.com/4251/54193298-0df0c700-44ba-11e9-8bcf-f68c4b2ebda5.png)

and now also:

![image](https://user-images.githubusercontent.com/4251/54193330-1fd26a00-44ba-11e9-906e-094e0294a0ab.png)

There's also hardly any changes in the newer version.

> and fill in the following information:
> 
> * Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

A new version of an existing add-on.

> * Whether your add-on is listed or unlisted.

Listed.

> * The URL where you submitted the add-on.

I signed it using the `web-ext` CLI, then I submitted the generated `.xpi` (attached as a `.zip`) to AMO using the API. [Here](https://gitlab.com/Flockademic/plaudit/-/jobs/175136565)'s the console output, and [this](https://gitlab.com/Flockademic/plaudit/blob/master/extension/publish_firefox.js) is the script I use to submit it.

(For comparison: [here](https://gitlab.com/Flockademic/plaudit/-/jobs/172078789)'s the console output for the extension when it did work - it's practically identical.)

* The approximate time you submitted the add-on, with timezone.

Mar 11, 2019 10:52am GMT+0100

Apologies if this is not the correct place to report this; I copied the format of other bug reports, but don't know where that template came from.

**Comment by wagnerand** [comment] 2019-03-12 14:44
The attached plaudit-0.1.19-an+fx.zip works just fine for me. However, it is technically a different add-on (different ID) than the attached plaudit-0.1.18-an+fx.zip and both are different than your actual listed add-on: https://addons.mozilla.org/en-US/firefox/addon/plauditpub/

For the listed add-on, I can confirm that 0.1.19 is broken.

Here is what I found out so far:

`plaudit-0.1.19-an+fx.xpi/META-INF/manifest.mf` contains information about `META-INF/cose.manifest` and `META-INF/cose.sig` twice, respectively.

```
Name: META-INF/cose.manifest
Digest-Algorithms: SHA1 SHA256
SHA1-Digest: mGVRWGOClCIG6JcrKvaeaYcVCkE=
SHA256-Digest: IVH1DaTNKgYcrqjyYyhFXkZZqWz4oqWsWdoBqgiB9aM=

Name: META-INF/cose.sig
Digest-Algorithms: SHA1 SHA256
SHA1-Digest: SacH6z404fFDUikbJn0Jb350QpE=
SHA256-Digest: Ikm8qaSlD14V8cOrWhdbH40fmYn17aT/NOul/8Y6QO4=

Name: META-INF/cose.manifest
Digest-Algorithms: SHA1 SHA256
SHA1-Digest: u9PGz3I9uFqTCUendLdFk9DYVxw=
SHA256-Digest: BzBl64wJXVT0L61mCv8sRdYoUofCQuv1hIegP3pIon8=

Name: META-INF/cose.sig
Digest-Algorithms: SHA1 SHA256
SHA1-Digest: Q4yHsT8SEGuDubyaRxmw4fzLkdI=
SHA256-Digest: arCcrrIQSVLaKPRng9smv3zWEpNF+kEuA9A5Ht/2DUc=
```

`plaudit-0.1.19-an+fx.xpi/META-INF/cose.manifest` contains information about `META-INF/cose.sig` (which is odd, because that is not the case for `META-INF/manifest.mf`: It does not contain information on `META-INF/mozilla.rsa`. Even worse, `plaudit-0.1.19-an+fx.xpi/META-INF/cose.manifest` contains hash of itself, which seems impossible, as every time you add the hashsum it will inevitably change the file and thus change the hash.

**Comment by Vinnl** [comment] 2019-03-12 14:56
Thanks @wagnerand.

> both are different than your actual listed add-on

That is correct; I first package and sign the extension using `web-ext`, then I upload the signed `.xpi` through the API. Now that you mention it I realise this is probably redundant, and an artifact of back when I thought I could also use `web-ext` to publish new versions of my extension. Alternatively, I should be able to zip up the directory myself and upload that through the API, I presume? Would that also fix the other issues?

Of course, it's still odd that this was not a problem in 0.18 - it was uploaded using the exact same process.

**Comment by wagnerand** [comment] 2019-03-12 15:50
> I first package and sign the extension using `web-ext`, then I upload the signed `.xpi` through the API. Now that you mention it I realise this is probably redundant, and an artifact of back when I thought I could also use `web-ext` to publish new versions of my extension. Alternatively, I should be able to zip up the directory myself and upload that through the API, I presume? Would that also fix the other issues?

You can use web-ext to publish new versions, even for listed. Check the (updated) documentation on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign. Alternatively you can use `web-ext build` to just zip the directory and then submit manually using the website (not the API, because you'd use `web-ext sign` for that).

> Of course, it's still odd that this was not a problem in 0.18 - it was uploaded using the exact same process.

We changed some things regarding to signing in the background recently.

**Comment by g-k** [comment] 2019-03-12 15:57
working on a fix in https://bugzilla.mozilla.org/show_bug.cgi?id=1534659

**Comment by Vinnl** [comment] 2019-03-13 10:24
Awesome @g-k! Unfortunately access to that bug is restricted, so I can't subscribe to see its progress...

**Comment by g-k** [comment] 2019-03-14 00:35
@Vinnl My bad. Thought the bug was security-related, but opened it up. Have a PR out with a fix. Thanks for raising this! Nasty bug, really glad you and Andreas caught it early.

**Comment by Vinnl** [comment] 2019-03-14 07:44
Great, thanks @g-k. Meanwhile I modified my project to use `web-ext` v3 for publishing rather than the API. It now works again, though that might also be because the problematic changes were reverted?

(Btw, I assume this issue is the same as [this one](https://discourse.mozilla.org/t/add-on-corrupted-on-upload-to-add-on-store/36597/5?u=vinnl)?)

**Comment by g-k** [comment] 2019-03-14 15:28
> It now works again, though that might also be because the problematic changes were reverted?

Yeah, we turned off signing with the new signature format after Andreas identified this issue.

Didn't dig into the discourse issue, but it's does look like the same one.

Sorry for the inconvenience and thanks for responding to the discourse issue!

**Comment by Vinnl** [comment] 2019-03-14 15:42
Alright, let me know if it's turned back on, and I'll give it another shot (though with `web-ext` this time).

**Comment by EnTeQuAk** [comment] 2019-04-02 12:59
We'll have it turned on to 100% this Thursday.

Assigning the issue to myself for better tracking.

**Comment by muffinresearch** [comment] 2019-04-10 15:41
On the basis that COSE signing is back up to 100% now, I'm going to close this out, @Vinnl please let us know if you have any further issues.

**Closed by muffinresearch** 2019-04-10 15:41 UTC
Labels: component: signing, priority: p2, triaged
