### ISSUE TITLE
add NetBSD to known platform list

### ISSUE THREAD

**Issue by aniou** [mozilla/addons#1154] opened 2020-01-20 15:08 UTC
When I search something from about:addons search box it leads to message: "0 results / Invalid "platform" parameter" due to unknown value of "platform" parameter ("NetBSD").

Sample URL: https://addons.mozilla.org/en-US/firefox/search/?q=test&platform=NetBSD&appver=68.4.1

Manually changing "NetBSD" to - for example - "linux" in URL gave me expected results.

**Comment by jvillalobos** [comment] 2020-01-20 16:52
Related to https://github.com/mozilla/addons-frontend/issues/4610 and https://github.com/mozilla/addons/issues/708

**Comment by diox** [comment] 2020-04-20 11:27
Duplicate of either of those issues, no need to keep this one around.

**Closed by diox** 2020-04-20 11:27 UTC
