### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by haroldtreen** [mozilla/addons#926] opened 2019-02-27 02:31 UTC
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

Update to an existing add-on.

* Whether your add-on is listed or unlisted.

Currently listed.

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/epub-read-the-web-offline/versions/submit/

* The approximate time you submitted the add-on, with timezone.

February 26th - 9:29pm EST

[app.zip](https://github.com/mozilla/addons/files/2908317/app.zip)

**Comment by wagnerand** [comment] 2019-02-27 06:49
Duplicate of #896

**Closed by wagnerand** 2019-02-27 06:49 UTC
