### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by martini224** [mozilla/addons#911] opened 2019-02-14 10:14 UTC
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
a new version of an existing add-on

* Whether your add-on is listed or unlisted.
listed

* The URL where you submitted the add-on.
https://addons.mozilla.org/en-US/developers/addon/webdeb-extension/versions/submit/

* The approximate time you submitted the add-on, with timezone.
11h10 (GMT+1) 

[firefox extension.zip](https://github.com/mozilla/addons/files/2864435/firefox.extension.zip)

**Comment by wagnerand** [comment] 2019-02-14 18:07
The linter bails on the ZIP file with `TYPE_NO_MANIFEST_JSON` (no `manifest.json` found), but it succeeds just fine on the extracted folder, so I assume you are using a zip program we have trouble parsing. Could you try with a different one?

/cc @EnTeQuAk

**Comment by EnTeQuAk** [comment] 2019-02-15 14:48
Duplicate of #896

The problem is, your add-on is packaged wrong. You don't have the `manifest.json` on the root of the folder, instead, there's a subfolder containing all the data.

[developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension)_

We should issue a better error though, so I opened [mozilla/addons-server#10635](https://github.com/mozilla/addons-server/issues/10635) to fix that.

Closing here.

**Closed by EnTeQuAk** 2019-02-15 14:48 UTC
Labels: needs: info
