### ISSUE TITLE
Link to french dictionary is broken

### ISSUE THREAD

**Issue by RobSiklos** [mozilla/addons#124] opened 2016-06-02 14:20 UTC
On [this page](https://addons.mozilla.org/en-US/firefox/language-tools/), the link to "Install Dictionary" for French points here: https://addons.mozilla.org/en-US/firefox/addon/dictionnaires-fran%C3%A7ais/

Unfortunately, when I go to that page, I get a "Not Found" error.

This worked a few days ago.

**Comment by jvillalobos** [comment] 2016-06-02 14:48
Dupe of https://github.com/mozilla/addons-server/issues/2823

**Closed by jvillalobos** 2016-06-02 14:48 UTC
