### ISSUE TITLE
leech block on android firefox has been removed 

### ISSUE THREAD

**Issue by Mojotechnical** [mozilla/addons#1544] opened 2023-12-04 19:20 UTC
Leach block no longer exists on Android firefox. This is not a developer issue. I directly contacted the developer. He said you Mozilla removed it and won't communicate with him. Please advise next steps that I as a user or the developer can take. This is not for the desktop platform. This is for android Firefox.

**Comment by willdurand** [comment] 2023-12-04 19:35
Duplicate of https://github.com/mozilla/addons/issues/1543

**Closed by willdurand** 2023-12-04 19:35 UTC

**Comment by Mojotechnical** [comment] 2023-12-04 19:49
I already had it installed and it has not allowed me to keep it. If that worked we wouldn't be having this discussion.
