### ISSUE TITLE
Got a 404 response when downloading

### ISSUE THREAD

**Issue by AllworxAdvAppDev** [mozilla/addons#791] opened 2018-09-14 16:35 UTC
### Describe the problem and steps to reproduce it:

Command: `web-ext sign --api-key=${Env:FIREFOX_USER} --api-secret=${Env:FIREFOX_SECRET}`

### What happened?

Fails (every time) with message:

<pre>  Validating add-on [............................................................]
  Validation results: https://addons.mozilla.org/en-US/developers/upload/24da2523a0154318a07488f89015318b

  C:\Users\A-dhentschel\AppData\Roaming\npm\node_modules\web-ext\node_modules\sign-addon\dist\webpack:\src\amo-client.js:283
                throw new Error(
                      ^
EXEC : error : Got a 404 response when downloading https://addons.mozilla.org/api/v3/file/1077822/allworx_interact_sync_for_firefox-3.15.16.1921-an+fx.xpi?src=api
      at Request.<anonymous> (C:\Users\A-dhentschel\AppData\Roaming\npm\node_modules\web-ext\node_modules\sign-addon\dist\webpack:\src\amo-client.js:283:21)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.onRequestResponse (C:\Users\A-dhentschel\AppData\Roaming\npm\node_modules\web-ext\node_modules\sign-addon\node_modules\request\request.js:986:10)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at TLSSocket.socketOnData (_http_client.js:440:20)
      at emitOne (events.js:116:13)
      at TLSSocket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at TLSSocket.Readable.push (_stream_readable.js:208:10)
      at TLSWrap.onread (net.js:594:20)
  Downloading signed files: ...</pre>

### What did you expect to happen?

Add-on is signed and downloaded successfully.

### Anything else we should know?
This is very likely my own fault. I have done some strange things with my add-on recently, and I think that AMO might be in a bad state WRT it now. There's some history to this, so I will walk you through...

1) I didn't notice the blog post [Removing Support for Unpacked Extensions](https://blog.mozilla.org/addons/2018/02/22/removing-support-unpacked-extensions/)
2) My customer complained that the Firefox add-on stopped working in version 62 of Firefox
3) After attempting to investigate, I submitted [Bug 1490771](https://bugzilla.mozilla.org/show_bug.cgi?id=1490771)
4) I published my (previously unlisted) add-on to AMO so I could test loading it through the Firefox Add-ons website
5) I added my findings (loading from the web works fine) to the bug report, and was informed of the blog post linked above
6) I changed my build process to conform with said blog post, and attempted to build
7) The build failed with message:
<pre>Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
      FAIL</pre>
8) I removed the listed version of the add-on and attempted to build again
9) Now I get the above mentioned 404 error every time I try to build

**Comment by AllworxAdvAppDev** [comment] 2018-09-14 17:00
Apparently not just from the `web-ext` command line client. If I try to download from the Manage Version webpage (https://addons.mozilla.org/en-US/developers/addon/allworx-interact-sync/versions/2533374) I get a 404 error there as well.

**Comment by AllworxAdvAppDev** [comment] 2018-09-18 13:52
Just a quick update. This is still a show-stopper problem for my company. This is causing our Jenkins builds to fail since signing the Firefox add-on is part of the build procedure. I need to somehow resolve this. If this is not the correct place to be requesting help, please direct me. Thank you.

**Comment by diox** [comment] 2018-09-18 13:58
Hi,

This is a duplicate of a know issue, https://github.com/mozilla/addons/issues/324

**Closed by diox** 2018-09-18 13:58 UTC
