### ISSUE TITLE
I can't put on AMO the new version 

### ISSUE THREAD

**Issue by blr21560** [mozilla/addons#258] opened 2016-10-19 18:21 UTC
Hello,
### Describe the problem and steps to reproduce it:
I have a module on AMO : stataccueil.
I put on three versions. It's good.
I rewrite all codes with WebExtension method (zip file).
I have a problem because I can't put on AMO the new version (version 0.0.4).
The "add new version" dialog upload the file but the "add new version" button stay unable. (see below)
I have waited 30 minutes ago.
I include this file

Do you know this problem ?

(Please include a link to the page, screenshots and any relevant files.)
![dialog](https://cloud.githubusercontent.com/assets/201661/19531697/de683ff4-9638-11e6-9a0d-fc37eb533cf1.png)
[stataccueil-0.0.4.zip](https://github.com/mozilla/addons/files/539841/stataccueil-0.0.4.zip)

**Comment by muffinresearch** [comment] 2016-10-19 18:37
Looks like you have zipped a directory as well as the files which means that the extraction doesn't find the manifest.json. Move the files to the top level and it should work.

Note: a warning is shown that no install.rdf or manifest.json can be found the first time you upload. However for subsequent uploads the validation steps appears to have hung - See also https://github.com/mozilla/addons/issues/252 which describes the same problem.

**Comment by muffinresearch** [comment] 2016-10-19 18:40
Going to mark this as a duplicate of #252, but let us know if you have any further issues.

**Closed by muffinresearch** 2016-10-19 18:40 UTC

**Comment by blr21560** [comment] 2016-10-19 20:20
It's ok
Thanks you
