### ISSUE TITLE
Add a dark theme for the site

### ISSUE THREAD

**Issue by Rakleed** [mozilla/addons#1138] opened 2019-12-02 20:24 UTC
### Describe the problem and steps to reproduce it:
Due to the lack of a dark theme at night and in dark rooms, using the site is very unpleasant, because it is unpleasant for the eyes. At the same time, third-party extensions also do not have the ability to change the site (for example, [Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/)).

### What happened?
The background of the site is white anyway.

### What did you expect to happen?
It is possible to change the background of the site to black.

### Anything else we should know?
[Page](https://addons.mozilla.org/en-US/firefox/extensions/) for an example.
<details>
<summary>Screenshot https://addons.mozilla.org/en-US/firefox/extensions/ in Firefox</summary>

![image](https://user-images.githubusercontent.com/19418601/69992216-4362a680-155a-11ea-943d-031fb9fda8c6.png)

</details>

<details>
<summary>Screenshot https://addons.mozilla.org/en-US/firefox/extensions/ in Chrome with Dark Reader extension turned on</summary>

![image](https://user-images.githubusercontent.com/19418601/69992313-70af5480-155a-11ea-9965-08d9ad523f42.png)

</details>

**Comment by jvillalobos** [comment] 2020-01-03 15:40
Closing this as a duplicate of https://github.com/mozilla/addons-frontend/issues/7907

**Closed by jvillalobos** 2020-01-03 15:40 UTC
