### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by pf-tech** [mozilla/addons#896] opened 2019-02-07 18:32 UTC
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
~New submission (my very first, which is probably why I have an issue)

* Whether your add-on is listed or unlisted.
~listed

* The URL where you submitted the add-on.
~https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.
~12:26p central time
[authoravoidance_firefox.zip](https://github.com/mozilla/addons/files/2842196/authoravoidance_firefox.zip)

Notes:
I have been testing this code on my local instance of FireFox with no errors. The error message from the uploader: 
Error: Validation was unable to complete successfully due to an unexpected error.

Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU

This message is quite vague and I can't tell what I am doing wrong. Any help would be appreciated.

Thanks,
Mana

**Comment by EnTeQuAk** [comment] 2019-02-08 08:01
The problem is, your add-on is packaged wrong. You don't have the `manifest.json` on the root of the folder, instead there's a subfolder containing all the data.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension_

We should issue a better error though, so I opened https://github.com/mozilla/addons-server/issues/10635 to fix that.

Closing here.

**Closed by EnTeQuAk** 2019-02-08 08:01 UTC

**Comment by wagnerand** [comment] 2019-03-04 17:22
Given the amount of reports, we should probably get to this sooner rather than later.
