### ISSUE TITLE
Stats overview page shows numbers line-broken in middle 

### ISSUE THREAD

**Issue by rugk** [mozilla/addons#772] opened 2018-08-19 13:15 UTC
### Describe the problem and steps to reproduce it:
It affects the "Top Languages" list:

Here [PrivacyBagder's page](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/statistics/?last=30):
![image](https://user-images.githubusercontent.com/11966684/44309147-6d727280-a3c2-11e8-868a-c09d8ddf4a1e.png)

And my [Offline QR Code Generator add-on](https://addons.mozilla.org/en-US/firefox/addon/offline-qr-code-generator/statistics/?last=30):

![image](https://user-images.githubusercontent.com/11966684/44309154-88dd7d80-a3c2-11e8-9471-881cca3c953c.png)

### What happened?

In both cases, the absolute numbers have a line-break in the middle of the number, making them unreadable.

### What did you expect to happen?

No line break.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
see above

**Comment by muffinresearch** [comment] 2018-09-05 15:36
I can't repro this currently on FF63.0a1  OSX

**Comment by caitmuenster** [comment] 2018-09-05 15:37
We're unsure how easy this will be to replicate this bug (AMO staff haven't been able to do so). 

However, any contributor who can replicate this bug and would like to fix it is welcome to do so! Mentor @eviljeff.

**Comment by willdurand** [comment] 2020-07-07 17:32
Closing this issue as I can't reproduce anymore.

**Closed** 2020-07-07 17:32 UTC
Labels: component: legacy frontend, contrib: welcome, priority: p5
