### ISSUE TITLE
Terms in description are not found

### ISSUE THREAD

**Issue by vstepaniuk** [mozilla/addons#731] opened 2018-06-05 10:44 UTC
Search on addons.mozilla.org is just terrible!!!

Not to mention the enormously huge problem of not being able to get the bookmark folder path in the search results, it is also extremely hard to find an add-on on AMO web site that solves that.
I open your beautiful addons.mozilla.org, enter `bookmarks` in the search field, (found 565 results), and on the second page I find an add-on "Bookmark search plus 2" (https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/?src=search) which says in the description: 

> Displays and filters bookmarks on search string, show **parent folders**.

I think "hm, that is a dinosaur-old problem, and it might be a better solution for it... let's try also entering  `bookmarks parent folder` directly to check all the new solutions to this problem that appeared recently" Now! Just a second away!

5 pages, 125 results for "bookmarks **parent folder**", and NO EVEN "Bookmark search plus 2" !!!

**Comment by mazesy** [comment] 2018-06-05 11:44
Slightly off-topic but since the time the following bothers me and many, many others, here goes:

1- _Parent folder_ should be included in the _Library_ (Places, View all Bookmarks). When you search your library which holds many bookmarks, having the parent folder shown is invaluable. Big lack. This should not require a dedicated extension, this should absolutely be native.

2- _Library_ would always open in a separate window, but until Firefox 59 it could open in a tab (in-content) with `chrome://browser/content/places/places.xul` -- No longer works and I'm not aware of any link to open the _Library_ in a separate tab. This is nonsense. Far easier to deal with the _Library_ in a tab. In-content has been adopted for many Firefox pages, lastly with _Page Source_, why not with _Library_?

**Comment by EnTeQuAk** [comment] 2018-08-17 05:55
This may have been improved a bit by mozilla/addons-server#8868 but I can see that it's still hard to find yor mentioned add-on via the description. I guess the amount of users and downloads may be a factor here.

I'll keep this open as this could be a scenario where we have to continue to improve search.

**Comment by diox** [comment] 2018-10-23 13:39
The fix for https://github.com/mozilla/addons-server/issues/6838 which is going out this week should help this issue. Keeping it opened to check after the push on Thursday.

**Comment by diox** [comment] 2018-11-07 14:16
That wasn't enough. `bookmarks parent folders` does not find it, neither does `bookmark parent folder` (pluralization removed, which is trickier if we are not using the right analyzer). We have another chance with the fix for https://github.com/mozilla/addons-server/issues/6898 but I don't think it will be enough either.

My guess is that the `match_phrase` we're doing on the description and summary are not enough, even when using the right analyzer for the job. I'll have to look at what the analyzer output is for that summary/description compared to the query, and whether or not we can tweak the `match_phrase` parameters to make it match.

**Comment by diox** [comment] 2018-11-08 12:17
I've got a fix locally, we just need to change the `slop` of our `match_phrase` queries we run against the summary & description. It'd definitely be a good thing, but I want to test performance of https://github.com/mozilla/addons-server/issues/9771 first, so I'm planning to land the fix for the 2018.11.22 push. If it turns out to be affecting performance too much, then we can look into [just doing a regular `match`, moving the `match_phrase` to a `rescore` block](https://github.com/mozilla/addons-server/issues/9933).

**Comment by diox** [comment] 2018-11-15 15:04
This will be fixed in production next week.

**Closed** 2018-11-15 15:03 UTC
Labels: component: search, priority: p3

**Comment by AlexandraMoga** [comment] 2018-11-20 13:41
I've submitted a copy of Bookmark search plus 2 on AMO -dev and if I search for `bookmarks parent folder` the addon is returned in search results:

![image](https://user-images.githubusercontent.com/31961530/48777136-7719b800-ecda-11e8-9904-d77047b820f2.png)

This will be double checked on -prod at the end of the week, to make sure the issue is fixed there as well.

**Comment by AlexandraMoga** [comment] 2018-11-23 08:12
This looks fixed in -prod as well:

![image](https://user-images.githubusercontent.com/31961530/48933209-28e9fc00-ef08-11e8-92c2-743f38e91a56.png)
