### ISSUE TITLE
Option to add some extension/theme/etc. to collection is missing/deleted/removed from extension/theme/etc. page

### ISSUE THREAD

**Issue by ghost** [mozilla/addons#465] opened 2017-08-10 10:16 UTC
### Describe the problem and steps to reproduce it:
I'm now unable to add some extension/theme/etc., because option to add some extension/theme/etc. to collection is missing/deleted/removed from extension/theme/etc. page, and I unable to add it also under edit option in collection, because this addon specific doesn't show there.

Simply, try to add this addon to your collection "Download Star" - https://addons.mozilla.org/en-US/firefox/addon/download-star/ - and see that you will be unable to.

### What happened?
Option to add some extension/theme/etc. to collection is missing/deleted/removed from extension/theme/etc. page

### What did you expect to happen?
Option to add some extension/theme/etc. have to be on extension/theme/etc. page like some time ago.

### Anything else we should know?
See 2 attachments.
![ss1](https://user-images.githubusercontent.com/30896135/29165943-e0a8fbae-7dc4-11e7-93aa-e3ed3db8334a.PNG)
![ss2](https://user-images.githubusercontent.com/30896135/29165968-ed1107f6-7dc4-11e7-9c95-5fdc88668205.PNG)

**Comment by jvillalobos** [comment] 2017-08-10 19:51
This is a duplicate of https://github.com/mozilla/addons-server/issues/2264. After some discussion both in the issue and the forum thread, we decided to bring it back in the new AMO front end (https://github.com/mozilla/addons-frontend/issues/2768), which should be out within a couple of months.

**Closed by jvillalobos** 2017-08-10 19:51 UTC
