### ISSUE TITLE
Invalid link in email

### ISSUE THREAD

**Issue by crankycoder** [mozilla/addons#62] opened 2016-03-10 23:29 UTC
I get an email with an invalid link to my XPI when signing.

> Hello,
> Your add-on, Privacy Enhanced Locations 0.0.20, has passed our automatic tests and is 
> now signed and ready for you to 
> download at https://addons.mozilla.org/developers/addon/None/versions
> 
> Reviewer:
> Mozilla
> 
> Comments:
> automatic validation

This happened to me when I signed an addon which returned a JSON blob instead of my signed XPI: https://github.com/mozilla-jetpack/jpm/issues/515

**Comment by andymckay** [comment] 2016-03-11 00:35
@mstriemer could you take a look please?

**Comment by kewisch** [comment] 2016-03-11 09:30
This is likely due to my commit, I'll take a look.

**Comment by kewisch** [comment] 2016-03-11 15:22
@mstriemer I had assumed this is fallout https://github.com/mozilla/addons-server/commit/235e649fb124d71a9f3886dfbff99c6b463e41a5 but I could not reproduce this locally with a manually uploaded extension. I haven't been able to figure out how to enable the signing API on a local install so I could not reproduce this under exact circumstances. Maybe you can help me out here or take a look.

**Comment by mstriemer** [comment] 2016-03-11 15:40
@kewisch You'll need to flip the `signing-api` waffle switch to enable it locally. You should be able to do that with `python manage.py waffle_switch signing-api on --create`.

I don't see anything specific to signing in those changes. It does seem likely since they recently changed though.

**Comment by mstriemer** [comment] 2016-03-11 15:55
I uploaded the add-on through the API locally but didn't get an email. I think because signing is disabled. How do you normally generate these emails locally?

**Comment by kewisch** [comment] 2016-03-11 16:30
Emails are not delivered for local installs by default, but what I do is add `log.debug(message)` to the `send` function in `src/olympia/amo/utils.py` and then observe the debug log.

**Comment by mstriemer** [comment] 2016-03-11 17:47
I found the email in the fake mail section of the admin tools (I thought it got logged to console but I can't find it anywhere). The URL looks good locally.

It looks like the slug for this add-on is `None`. @crankycoder what URL works to manage your add-on's listing?

**Comment by crankycoder** [comment] 2016-03-11 17:49
I deleted the listing as the name was a problem for review process. 

So there isn't a listing anymore. 

On Mar 11, 2016 12:47 PM, Mark Striemer <notifications@github.com> wrote:

I found the email in the fake mail section of the admin tools (I thought it got logged to console but I can't find it anywhere). The URL looks good locally.

It looks like the slug for this add-on is None. @crankycoder what URL works to manage your add-on's listing?

**Comment by mstriemer** [comment] 2016-03-11 18:04
Looks like that's the culprit. I deleted the add-on locally and checking in the database we remove the slug from an add-on when we delete it but not the guid.

Since we use `Addon.unfiltered.get(guid=guid)` [1] we're finding deleted add-ons as well and will accept an upload for a deleted add-on. We should switch that to use `Addon.with_unlisted.get(guid=guid)` [2].

[1] https://github.com/mozilla/addons-server/blob/1384d23327b1d8066fc657d961740f69c28255b0/src/olympia/signing/views.py#L48
[2] https://github.com/mozilla/addons-server/blob/1384d23327b1d8066fc657d961740f69c28255b0/src/olympia/addons/models.py#L352

**Comment by muffinresearch** [comment] 2017-03-22 08:51
I think this should have been closed by https://github.com/mozilla/addons-server/issues/2000

**Closed by muffinresearch** 2017-03-22 08:51 UTC
Labels: component: signing
