### ISSUE TITLE
[Bug]: Can't submit a new version of an Add-on

### ISSUE THREAD

**Issue by MarinaPepper** [mozilla/addons#15120] opened 2024-10-30 11:08 UTC
### What happened?

When I try to submit a new version of the Add-on, I upload it, but when I click on "Continue" it shows an error page every time.
![Screenshot 2024-10-30 at 12 06 06](https://github.com/user-attachments/assets/ac8e2681-c9ba-412b-a7f6-27a2294f82d0)
![Screenshot 2024-10-30 at 12 06 15](https://github.com/user-attachments/assets/aacd2815-2298-4401-92cb-3ce616dbcb7f)

### What did you expect to happen?

Continue to sumbit an Add-on

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1175)

**Comment by indykish** [comment] 2024-10-30 11:09
This is a duplicate of this https://github.com/mozilla/addons/issues/15116

**Closed** 2024-10-30 11:11 UTC
Labels: needs:info
