### ISSUE TITLE
"validation took too long" using web-ext sign

### ISSUE THREAD

**Issue by jml674** [mozilla/addons#661] opened 2018-03-13 17:50 UTC
### Describe the problem and steps to reproduce it:
I was able to sign a previous extension version but all new attempts failed with the validation spinning.
I have attempted to upgrade web-ext to 2.4.0 but keep facing the issue.

### What did you expect to happen?
I was expecting web-ext to return signed xpi versions.

### Anything else we should know?
I have tried to shrink my extnsion files to the minimum volume, removing all js file from it but same issue.

I have collected the logs using --verbose
[logs.txt](https://github.com/mozilla/addons/files/1808055/logs.txt)
 and attached the file.

**Comment by jvillalobos** [comment] 2018-03-13 19:58
I see some files that were uploaded to your add-on, automatically approved, and later deleted. Did you delete those? Were those just tests for this issue?

**Comment by jml674** [comment] 2018-03-13 20:00
after failing the sript based approach I did some manual uploading that I subsequently deleted.

**Comment by jml674** [comment] 2018-03-14 11:52
ok, I pumped up the version of my add-on and retested. Works ! So the process seems to hang when a given version has been already uploaded and deleted. Any feedback form the tool in those circumstances would be appreciated!

**Comment by kumar303** [comment] 2018-03-14 14:13
Thanks for the bug report. This sounds confusing, sorry about that. I re-filed it here but can you confirm that I described the correct steps to reproduce? https://github.com/mozilla/sign-addon/issues/252

**Comment by jml674** [comment] 2018-03-14 14:42
perfect Kumar !

rgds, JM

**Comment by EnTeQuAk** [comment] 2018-03-20 08:51
Closing this since it's re-filed in https://github.com/mozilla/sign-addon/issues/252

**Closed by EnTeQuAk** 2018-03-20 08:51 UTC
