### ISSUE TITLE
Pagination cut off the category GET parameter.

### ISSUE THREAD

**Issue by mdnsk** [mozilla/addons#521] opened 2017-11-04 02:37 UTC
### Describe the problem and steps to reproduce it:
For example, if I go in the catalog, in the language-support category: https://addons.mozilla.org/en-US/firefox/search/?category=language-support&sort=rating&type=extension
I see there: "860 add-ons found", and when I click on the next page, I see "21,261 add-ons found" because now it is not the language-support category and all add-ons are listed there.

### What happened?
It happens because pagination link does not contain the category GET parameter.

### What did you expect to happen?
When I click the "next" link in the language-support category, I expect to see only add-ons related with the language-support category.

**Comment by muffinresearch** [comment] 2017-11-06 14:36
Hi thanks for filing, this is a duplicate of https://github.com/mozilla/addons-frontend/issues/3764

**Closed by muffinresearch** 2017-11-06 14:36 UTC
