### ISSUE TITLE
cannot make contributions

### ISSUE THREAD

**Issue by MarkCSmith** [mozilla/addons#456] opened 2017-08-02 15:07 UTC
The PayPal page is not loading when I (and other people) try to make an add-on contribution. Steps to reproduce:
1. Open Firefox 54.0.1 and go to a page for an add-on that accepts contributions, e.g., https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/
2. Click the "Contribute" button and then click "Make Contribution" on the in-page "popup."

Actual result: the in-page "popup" disappeared and the page stayed dim.
Expected result:  A PayPal page or overlaid iframe should open.

I see this on the web console:
`Load denied by X-Frame-Options: https://ic.paypal.com/webapps/adaptivepayment/flow/pay?paykey=AP-6XH050448F490184X does not permit cross-origin framing.`

I learned about this problem because a user wanted to make a contribution to one of my company's add-ons and could not do it.

**Comment by andymckay** [comment] 2017-08-02 22:20
Thanks, this is a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=802142. Because of problems like this there are plans to remove this flow and replace with another flow see mozilla/addons-server#6069

**Closed by andymckay** 2017-08-02 22:20 UTC
