### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by rishabhmw** [mozilla/addons#919] opened 2019-02-20 08:11 UTC
This is a chrome extension. The Extension Compatibility Test for Firefox shows that my extension is compatible. This is an open source project available here: https://github.com/rishabhmw/sauron/
Please attach a copy of your add-on, and fill in the following information:
[Sauron - Dark mode for all websites.zip](https://github.com/mozilla/addons/files/2883591/Sauron.-.Dark.mode.for.all.websites.zip)

This error occurred during the submission of a new add-on.

https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.
13:30 (GMT+5:30)

**Comment by wagnerand** [comment] 2019-02-20 08:13
Duplicate of #896

**Closed by wagnerand** 2019-02-20 08:13 UTC
