### ISSUE TITLE
bug in addon rating

### ISSUE THREAD

**Issue by mojtabadaneshi** [mozilla/addons#186] opened 2016-08-17 20:22 UTC
I develop popup blocker ultimate addon,It had soma rate and reveiw that i reported them and deleted,but in developer page my rating is 3 star,but i have two 5 star rating, also in addon page it tell 1 reveiw , but two review is there.
Sincerely

**Comment by wagnerand** [comment] 2016-08-18 10:33
I think this is a duplicate of https://github.com/mozilla/addons-server/issues/1618

**Closed by wagnerand** 2016-08-18 10:33 UTC
