### ISSUE TITLE
WebExtension installation issue on Linux with Firefox 49

### ISSUE THREAD

**Issue by caseyahenson** [mozilla/addons#260] opened 2016-10-20 20:06 UTC
When attempting to add EmojiOne Keyboard (https://addons.mozilla.org/en-US/firefox/addon/emoji-keyboard-by-emojione/) to a vanilla Firefox 49.0 stable build on Kubuntu 16.04 from AMO, I receive an error and the download/install will not complete.

--The Error--
![emojione_install_error](https://cloud.githubusercontent.com/assets/4519609/19575713/e36cf9ea-96c4-11e6-8486-47f9103c2bb9.png)

This error fires immediately after download progress reaches 100%, and the "Install" button never activates:
![emojione_install_error2](https://cloud.githubusercontent.com/assets/4519609/19575761/1341fe0e-96c5-11e6-8274-665075898c5a.png)

Steps to recreate (on Ubuntu 16.04 using Firefox 49.0 stable):
1) Open browser console
2) Go to https://addons.mozilla.org/en-US/firefox/addon/emoji-keyboard-by-emojione/versions/
3) On Version 0.15 click "Add to Firefox"

Thanks in advance for your assistance.

**Comment by andymckay** [comment] 2016-10-26 16:17
There is a note in the add-on "Due to installation issues, this Add-On is currently unavailable on Linux systems". No-one has figured out the cause yet, if this is a bug in WebExtensions (which it probably is) a bug in Bugzilla (https://bugzilla.mozilla.org) where the WebExtensions code lives and is maintained is probably the way to go.

**Comment by muffinresearch** [comment] 2016-10-28 13:40
I'm going to close this since there's no action needed from here at this point in time.

**Closed by muffinresearch** 2016-10-28 13:40 UTC
