### ISSUE TITLE
Can't upload source code for prelim-review

### ISSUE THREAD

**Issue by raggupta2** [mozilla/addons#188] opened 2016-08-21 16:38 UTC
I've uploaded [my addon](https://addons.mozilla.org/en-US/developers/addon/aam-aadmi-tatkal-%E0%A4%86%E0%A4%AE-%E0%A4%86%E0%A4%A6%E0%A4%AE-%E0%A4%A4%E0%A4%A4-%E0%A4%95-%E0%A4%B2/) for prelim review but when I try to attach source it simply hangs. I've tried several times in Chrome and Firefox. I even reduced the source size from 1.6 MB to 100KB but still the same response. The "Add Version" simply don't get enabled even after long time.

Also when I try to upload the source in "Notes" it does not work. I even created a zip file containing only a png image and tried to upload but it gives still the same error:

> "Oops! We had an error.We'll get to fixing that soon."

**Comment by wagnerand** [comment] 2016-08-22 10:15
Sounds like a duplicate of https://github.com/mozilla/addons/issues/132

**Closed by wagnerand** 2016-08-22 10:15 UTC
