### ISSUE TITLE
can't install addon after signing it from amo with self-hosting

### ISSUE THREAD

**Issue by abnud1** [mozilla/addons#671] opened 2018-03-20 14:57 UTC
### What happened?
I've made a webextensions addon and it works correctly through about:debugging
Now I uploaded fist version to amo and chose to distribute it on my own and signed it, I then downloaded the xpi file and drag-dropped it to addons page, it worked.  

Now I want to upload a new version of the addon and sign it, the upload is successful and the signed xpi is downloaded but when dragging-dropping it firefox says the addon appears to be corrupt and in browser console I see signature verification failed error.  

META-INF folder exists in the xpi file but in manifest.mf I noticed that checksums of files are wrong.

firefox version is 59, the addon url is https://addons.mozilla.org/en-US/developers/addon/1ea9282802614af8a363
### What did you expect to happen?
I expected the addon to be installed

**Comment by abnud1** [comment] 2018-03-21 08:25
Ok I verified that this only happens on firefox 59, firefox 58 installs the addon

**Comment by EnTeQuAk** [comment] 2018-03-21 08:40
Interesting, I'll have a look at this shortly. We updated our signing
libraries that calculate the checksums recently, primarily to add sha2
support. This doesn't sound like a huge regression, otherwise I'd guess
we should see more reports but I'm not sure yet.

On Wed, Mar 21, 2018, at 9:25 AM, abnud1 wrote:
> Ok I verified that this only happens on firefox 59, firefox 58
> installs the addon> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons/issues/671#issuecomment-374862886

**Comment by AlexandraMoga** [comment] 2018-03-21 09:20
I've tried to reproduce this issue on AMO-prod with FF59 Win10x64 but my unlisted extension was installed without errors.

**Comment by abnud1** [comment] 2018-03-21 11:55
my extension only installs with version 1.2.1, all above versions don't work but 1.2.1 has I bug that I must fix, anyway I tried reverting my files to version 1.2.1 then changed the version number to 1.2.9 and uploaded the extension, I downloaded the xpi and it showed the same error even when only the version number of extension is what has changed
my manifest.json is as follows:  
`{
  "name": "NasMtnBarcode",
  "version": "1.2.10",
  "manifest_version": 2,
  "description": "an extension to make mtn able to use their barcodes from inside chrome,firefox and opera",
  "update_url": "http://0.0.0.0",
  "icons": {
    "16": "icons/icon16.png",
    "48": "icons/icon48.png",
    "128": "icons/icon128.png"
  },
  "permissions": [
    "nativeMessaging"
  ],
  "background": {
    "scripts": [ "lib/background/background.js" ]
  },
  "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9b3mdqfF3KoJeCTmP+d1spvBkRBnuvQERmvt6cz4jY8Gf0vgTSGl7xghQBi4E3+JycXaY+0TOA9mURpnZJPYdWsN5zHnploTj4NMmCuNRa0ci8iLs9T/3RdtUFDsbD+JGzXYQJzxUgxL/xIEDe//ckZNIXniwFfg2GKkaWG6cf1EWvI2csJijD/PtbXUXcVC61ZKoNTMXZaP18Ork5JLOlYguVJmNTnpfpoXJzrvtdpM8dbK/EVem9irJCzVaEjb+E7Sdqfe/JMi8csZ9sP1C1u0W5JMDvGSdzDGbphNQJRJHdQa/Gz7BovTJxFnUtfLeADg0/e7wfcHPEuvAR1ASQIDAQAB",
  "applications": {
    "gecko": {
      "id": "mtn@nas.sy"
    }
  },
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "src/jquery.min.js",
        "lib/inject/inject.js"
      ],
      "run_at": "document_end"
    }
  ],
  "web_accessible_resources": [
    "lib/inject/mtnViewer.js"
  ]
}`

**Comment by abnud1** [comment] 2018-03-21 12:08
By the way firefox 58 no longer installs the extension and also firefox 57 and 56

**Comment by abnud1** [comment] 2018-03-25 13:50
by the way I took the borderify example from webextensions tutorial and verified it's working through about:debugging.  
Now I uploaded it to AMO using submit new add-on , I download the xpi file and drag-drop it and I see the same error message.
By this I confirmed that the issue isn't within my extension

**Comment by AlexandraMoga** [comment] 2018-03-26 12:01
@abnud1 have you tried to create a new Firefox profile and perform the same steps to see if the issue is still reproducing?

**Comment by abnud1** [comment] 2018-03-26 12:35
@AlexandraMoga  yes the same issue happens with the new profile

**Comment by muffinresearch** [comment] 2018-03-29 12:02
@abnud1 did you manage to resolve your issue with additional version uploads? I just installed the latest version of your add-on on 59 and nightly in new profiles and both installed cleanly without any corruption messages.

**Comment by abnud1** [comment] 2018-04-01 07:55
@muffinresearch I tried installing it while firefox is in private mode and it worked, I then removed the addon, left private mode and installed it and it worked again

**Comment by muffinresearch** [comment] 2018-04-03 10:51
@abnud1 Thanks for the update. Based on your [last comment](https://github.com/mozilla/addons/issues/671#issuecomment-377769917) I'm going to close this out.

**Closed by muffinresearch** 2018-04-03 10:51 UTC
Labels: needs: info
