### ISSUE TITLE
The Relevance search option buries exact name matches

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons#724] opened 2018-05-25 10:12 UTC
I've been annoyed with the Relevance sorting on AMO before, but today's example raised the bar. I searched for OpenDyslexic (which is the full name of an add-on) and the exact match was 16th in the results. Why wasn't the best hit displayed first? It should be easy to find an add-on when you know the name.

(I needed to hit page-down twice, and read lots of text to actually find the add-on. A pain for me, and worse for someone with dyslexia.)

When I typed OpenDyslexic in the search box I expected the auto-complete to present the add-on I wanted as the first option, but it isn't in the list. The auto-complete list appears to be the same as the first ten search results.

Steps to reproduce:
1) Place "OpenDyslexic" in the search box on https://addons.mozilla.org/en-US/firefox/ and look at the auto-complete options.
2) Press Enter and look at the search results.

Expected result:
1) https://addons.mozilla.org/en-US/firefox/addon/opendyslexic-for-firefox/ as the first option.
2) https://addons.mozilla.org/en-US/firefox/addon/opendyslexic-for-firefox/ as the first result.

Actual result:
1) OpenDyslexic isn't in the list.
2) OpenDyslexic is in the 16th position.

**Comment by muffinresearch** [comment] 2018-05-30 11:32
Duplicate of https://github.com/mozilla/addons-server/issues/6837

**Closed by muffinresearch** 2018-05-30 11:32 UTC
Labels: component: search
