### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by mindbreaker** [mozilla/addons#920] opened 2019-02-20 15:56 UTC
Please attach a copy of your add-on, and fill in the following information:

[h1ff.zip](https://github.com/mozilla/addons/files/2885329/h1ff.zip)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
I want to add this new extension. It works on my own firefox.
![grafik](https://user-images.githubusercontent.com/225204/53104846-658db980-3530-11e9-9283-d8768ebbb3cd.png)

**Comment by wagnerand** [comment] 2019-02-20 16:25
Duplicate of #896

**Closed by wagnerand** 2019-02-20 16:25 UTC

**Comment by mindbreaker** [comment] 2019-02-20 16:42
Thanks.
