### ISSUE TITLE
[Bug]: 404 when following link in "Mozilla Add-ons: $EXTENSION_NAME" email

### ISSUE THREAD

**Issue by remh** [mozilla/addons#15008] opened 2024-09-10 06:27 UTC
### What happened?

I've submitted a private extension, it was tentatively approved.
I've received the following email:
```
Subject: Mozilla Add-ons: $EXTENSION_NAME
Content:
Hello,


Your Extension has been automatically screened and tentatively approved. It is now available at https://addons.mozilla.org/developers/addon/$MY_EXTENSION_ID/versions.

Your add-on can be subject to human review at any time. Reviewers may determine that it requires changes or should be removed. If that occurs, you will receive a separate notification with details and next steps.


[UNRELATED_CONTENT]/
```

But the link in the email is a 404.

### What did you expect to happen?

Link should be valid

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1043)

**Comment by diox** [comment] 2024-09-10 08:53
@remh are you logged in with an account which is an author of that extension ? The link would only work for such a user and would 404 otherwise by design.

**Comment by wagnerand** [comment] 2024-09-10 09:00
@diox Maybe for unlisted only, we should add an explicit sentence like "This link is accessible only when logged in as the author of the add-on".

**Comment by diox** [comment] 2024-09-10 14:24
Good idea. Since https://github.com/mozilla/addons/issues/15005 was already opened I'm marking this as a duplicate.

**Closed by diox** 2024-09-10 14:24 UTC
Labels: needs:info
