### ISSUE TITLE
Extension gives 404 error

### ISSUE THREAD

**Issue by mshkurat** [mozilla/addons#343] opened 2017-03-07 10:56 UTC
### Describe the problem and steps to reproduce it:
Our ESR extension does not work and gives 404 error for some reason. Here is a link https://addons.mozilla.org/firefox/downloads/file/604550/email_signature_rescue-2.3.4-an+fx.xpi?src=devhub

### What happened?
Looks like there are some issues with your server

### What did you expect to happen?
This extesnion should be available for download.

### Anything else we should know?
https://addons.mozilla.org/firefox/downloads/file/604550/email_signature_rescue-2.3.4-an+fx.xpi?src=devhub

**Comment by diox** [comment] 2017-03-07 11:19
This looks like a duplicate of https://github.com/mozilla/addons/issues/324 : the add-on is set to invisible, so the path to newly uploaded files is wrong for a little while before it's automatically corrected by a cron.

There is an additional twist here (cc @eviljeff) : the add-on listed versions have been deleted since, only unlisted versions remain. Because of this, we hide the checkbox to make the add-on visible/invisible, making it impossible for the developer to fix the problem themselves.

**Comment by diox** [comment] 2017-04-19 07:53
Closing as dupe of #324

**Closed by diox** 2017-04-19 07:53 UTC
Labels: state: triaged
