### ISSUE TITLE
Missing form fields on AMO submission

### ISSUE THREAD

**Issue by tomagendium** [mozilla/addons#1103] opened 2019-09-26 10:25 UTC
### Describe the problem and steps to reproduce it:

When trying to fill out the addon submission form, the inputs for Name and Summary are missing, and therefore raise validation errors as they can't be filled in.

<img width="304" alt="Screenshot 2019-09-26 at 13 20 57" src="https://user-images.githubusercontent.com/50625328/65680984-b7676680-e060-11e9-91b9-46418656cc2f.png">

Tested with both Firefox and Chrome and confirmed the same issue for both.

**Comment by diox** [comment] 2019-09-26 10:50
Please attach the archive of the add-on you're trying to submit, if possible. Also, the URL used to submit (it includes the add-on slug & locale used, which matter in this case)

**Comment by tomagendium** [comment] 2019-09-27 06:22
I seem to have solved this by using the same workaround as mentioned in [this comment](https://github.com/mozilla/addons/issues/382#issuecomment-348780954) 

The addon has a `default_locale` of `en` but by default the translation inputs for title and summary were named `name_fi` and `summary_fi`(which is the location for the AMO account), while all other inputs were `input_name_en-US`. I changed those to en-US in the inspector and removed the init fields as mentioned in the comment and the submission seemed to go through correctly.

**Comment by muffinresearch** [comment] 2019-10-02 15:19
Duplicate of https://github.com/mozilla/addons/issues/382

**Closed by muffinresearch** 2019-10-02 15:19 UTC
