### ISSUE TITLE
MonthlyPick not translatable

### ISSUE THREAD

**Issue by zelitomas** [mozilla/addons#302] opened 2016-12-23 22:32 UTC
Hello,

there are some untranslatable strings in promo part of header on AMO homepage (highlighted on screenshot)

![AMO l10n](https://cloud.githubusercontent.com/assets/3105674/21463322/b6974d46-c967-11e6-97eb-a8595eea186b.png)

Could somebody please take a look at them? (similar to #165 and #244)

Many thanks,
Tomáš Zelina

**Comment by andymckay** [comment] 2017-01-03 17:37
Is this still the case? Those strings show up in the .po files.

https://github.com/mozilla/addons-server/search?utf8=%E2%9C%93&q=%22Take+better%22

**Comment by zelitomas** [comment] 2017-01-04 18:57
@andymckay 
I can't find this one: 

> Watch YouTube on your own terms! Tons of customizable features, like ad blocking, auto-play, mouse-controlled volume, cinema mode, and more.

https://github.com/mozilla/addons-server/search?utf8=%E2%9C%93&q=%22Watch+YouTube%22

Bugs #165 and #244 are fixed, and I am referencing them only to point out that it happens quite often and that there may be some problem with string extraction process.

**Comment by zelitomas** [comment] 2017-01-14 20:11
Is there any problem? Normally you just re-run extraction and it's fixed in day or so, but now it's almost a month and still no progress. (the string has been even replaced since! (new string is `Display tabs in a tile layout — arrange them however you like.` - https://down.zelitomas.cf/amol10n.png ))

**Comment by andymckay** [comment] 2017-01-16 19:24
I think its because its a collection and we don't have translations of those, was that right @diox?

**Comment by diox** [comment] 2017-01-16 19:33
It's actually a `MonthlyPick`, which is its own model, with its own quirky translation mechanism.

Users with the right permissions can add translations: go to https://addons.mozilla.org/en-US/admin/monthly-pick and add a new row with the correct `locale` set, and it'll get picked up when before the existing row that has no locale (which is more of a catch-all fallback) when rendering the pages in that same locale.

**Comment by zelitomas** [comment] 2017-01-16 22:59
Thanks for your reply.

So, what can I do to get Monthly Picks translated to Czech? Is there any way I or anyone else from Czech translation team can get those "right permissions"?

**Comment by diox** [comment] 2017-01-16 23:26
The issue is marked as "needs more triage", we'll figure something out during our next weekly meeting - my personal preference would be to get rid of it, replacing it with something that is translatable more easily (getting the translations in the current mechanism doesn't scale well, I personally don't think it's a good solution, even in the short term)

**Comment by devaneymoz** [comment] 2017-01-20 21:04
Given the likelihood of an AMO front-end redesign sometime this year (thus rendering this module a moot point), what are our realistic options here? 

@diox doesn't think tweaking the existing POTM module is a good solution (short or long-term). So is it worth looking at an entirely new of presenting POTM in the homepage carousel? Or is it determined that as well would require more work than it's worth given the impending redesign?

**Comment by zelitomas** [comment] 2017-03-16 12:53
Any news about this issue? It's been more almost 3 months and POTM still can't be translated.

**Comment by muffinresearch** [comment] 2017-03-16 16:16
@zelitomas Unfortunately as alluded to in earlier replies - since we have limited resources and this is ulitmately going to be replaced it's quite low down our list of priorities at the moment.

**Comment by peiying2** [comment] 2017-09-24 14:13
@muffinresearch meeting with @zelitomas this weekend, and he reminded me this issue he filed a while back. Will the new design make this issue automatically go away?  Please fill us in.

**Comment by muffinresearch** [comment] 2017-09-25 08:14
@peiying2 yes it will. Once the new frontend is released (and replacing the current user pages frontend) this content will no longer be visible.

**Comment by diox** [comment] 2017-11-17 11:51
The new frontend is live, and does not use monthly pick, so I'm closing this.

**Closed by diox** 2017-11-17 11:51 UTC
Labels: component: legacy frontend, triaged
