### ISSUE TITLE
[Task]: Investigate how we can avoid regressions with local nginx and docker configs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#14886] opened 2024-06-26 19:59 UTC
### Description

At some point when some docker files have been rewritten, the nginx config stopped working, preventing files from being served locally (e.g. XPIs in detail pages). This issue is about covering the docker volume config + nginx config for localdev with automated tests.

### Acceptance Criteria

```[tasklist]
  ### Acceptance Criteria
  - [ ] we have some test coverage
  ```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-891)

**Comment by diox** [comment] 2024-10-02 11:35
forward-dupe of https://github.com/mozilla/addons/issues/14895

**Closed by diox** 2024-10-02 11:35 UTC
Labels: repository:addons-server
