### ISSUE TITLE
Search option 'Search add-ons for "foo"' doesn't search when clicked

### ISSUE THREAD

**Issue by gene1wood** [mozilla/addons#317] opened 2017-01-22 23:47 UTC
### Describe the problem and steps to reproduce it:
1. Browse to AMO : https://addons.mozilla.org/en-US/firefox/
2. In the `search for add-ons` search field in the upper right enter some search terms
3. In the drop down that appears below the `search for add-ons` input box you'll see a list of items. The first item is a blue backgrounded option that says `Search add-ons for "foo"`. Following that are 10 items without a blue background which are specific add-ons which match your search terms. Click the `Search add-ons for "foo"` item in the list

### What happened?
The search box is cleared and no search is done. The user remains on the page and their search terms are deleted.

### What did you expect to happen?
When clicking `Search add-ons for "foo"` I would expect the site to search for "foo" in add-ons and go to a search results page.

### Anything else we should know?
If you press <kbd>Enter</kbd> instead of clicking the search works. If you click the green arrow the search works.

**Comment by eviljeff** [comment] 2017-01-24 18:06
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
mentor: @andymckay

**Comment by numrut** [comment] 2017-02-06 17:59
Hi @andymckay ! May I work on this issue?

**Comment by tofumatt** [comment] 2017-02-06 18:03
Hi @numrut,

You can feel free to work on the issue, because of GitHub limitations we can't assign it to you but feel free to start working on it. Please reference this issue number in your pull request as well 😄

**Comment by muffinresearch** [comment] 2017-02-23 14:46
Unfortunately the patch had to be backed out because it caused a regression https://github.com/mozilla/addons-server/issues/4755 

I think the best way to solve this would be to have the link submit the form instead of building a link with the search term as that should then ensure any filters within the form are taken into account.

**Comment by numrut** [comment] 2017-02-26 15:52
Hi, @muffinresearch!

I've made yet another attempt)

I also found a block of code that never runs. Should I open a new issue for that?

**Comment by muffinresearch** [comment] 2017-02-28 10:35
> I also found a block of code that never runs. Should I open a new issue for that?

Yes - please do. Thanks!

**Closed** 2017-02-28 10:35 UTC
Labels: contrib: assigned, contrib: good first bug
