### ISSUE TITLE
504 error when trying to upload the source code for a new version

### ISSUE THREAD

**Issue by ajayalli-msft** [mozilla/addons#1449] opened 2022-12-07 09:58 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Steps followed: 
1. Clicked on My Add-ons -> Selected the addon to update -> Submit a new version 
2. Uploaded the xpi file (validation passed)
3. Selected source code zip file and clicked continue

This is where the issue occurs. The upload seems to process for a while and then errors out with 504 response.

The size of the compressed file is 71.8MB
Size of uncompressed files is 75.5MB

### What happened?
Encountered the following error:
![image](https://user-images.githubusercontent.com/118729203/206109469-17f3a145-f7ab-4dcc-8eb2-9f183dc8aefa.png)

However, in the version details page, a source code attachment was found which built successfully. In other words, the source code was uploaded successfully but a timeout response was returned for some reason.

Moreover, it's not clear whether the review process will continue as expected.

### What did you expect to happen?
Upload source code successfully without errors.

**Comment by diox** [comment] 2023-04-05 13:12
Hi,

This is a duplicate of https://github.com/mozilla/addons-server/issues/18105 which we have mitigated but still seems to happen from time to time unfortunately ...

**Closed by diox** 2023-04-05 13:12 UTC
Labels: component:developer_hub, priority:p4
