### ISSUE TITLE
Permanent link to latest version of addon

### ISSUE THREAD

**Issue by bdcomp** [mozilla/addons#602] opened 2017-12-24 20:39 UTC
### Describe the problem and steps to reproduce it:
I need a permanent link to latest version of my addons' XPI files (for links on my GitHub, etc.).
It looks like the new addons site don't provide this anymore.

### What happened?
Right click on the "Add to Firefox" button on the add-on details page and "Save Link As..." linked to a specific version, without the word "latest".
[Link](https://addons.mozilla.org/firefox/downloads/file/798619/printprint_preview_context-1.2-an+fx-linux.xpi) as of now.

### What did you expect to happen?
The link should contain the "latest" directory and no specific version like "0.1".
The same [link](https://addons.mozilla.org/firefox/downloads/latest/print-print-preview-context/platform:2/addon-870538-latest.xpi) from about 2 weeks ago.

**Comment by tofumatt** [comment] 2017-12-24 20:43
Thanks for filing an issue! This is a duplicate of an existing, known issue tracked here: https://github.com/mozilla/addons-frontend/issues/4083

Feel free to follow along with that issue to know when the issue has been fixed 😄

**Closed by tofumatt** 2017-12-24 20:43 UTC
